"""Curated Minna no Nihongo learning content for lessons 11 through 15."""

from __future__ import annotations


def _sentence(
    japanese: str,
    romaji: str,
    vietnamese: str,
    chunks: list[tuple[str, str, bool]],
) -> dict[str, object]:
    return {
        "full_japanese": japanese,
        "full_romaji": romaji,
        "full_vietnamese": vietnamese,
        "chunks": [
            (index, text, meaning, is_key)
            for index, (text, meaning, is_key) in enumerate(chunks, start=1)
        ],
    }


S = _sentence


LESSON_SENTENCES = {
    11: [
        S("子どもが二人います。", "Kodomo ga futari imasu.", "Tôi có hai người con.", [("子どもが", "con", False), ("二人", "hai người", True), ("います。", "có", False)]),
        S("兄弟が三人います。", "Kyoudai ga sannin imasu.", "Tôi có ba anh chị em.", [("兄弟が", "anh chị em", False), ("三人", "ba người", True), ("います。", "có", False)]),
        S("りんごを四つ買いました。", "Ringo o yottsu kaimashita.", "Tôi đã mua bốn quả táo.", [("りんごを", "táo", False), ("四つ", "bốn quả", True), ("買いました。", "đã mua", False)]),
        S("みかんを五つください。", "Mikan o itsutsu kudasai.", "Cho tôi năm quả quýt.", [("みかんを", "quýt", False), ("五つ", "năm quả", True), ("ください。", "xin cho tôi", False)]),
        S("会社に車が二台あります。", "Kaisha ni kuruma ga nidai arimasu.", "Công ty có hai chiếc ô tô.", [("会社に", "ở công ty", False), ("車が", "ô tô", False), ("二台", "hai chiếc", True), ("あります。", "có", False)]),
        S("切手を十枚買います。", "Kitte o juumai kaimasu.", "Tôi mua mười con tem.", [("切手を", "tem", False), ("十枚", "mười tờ", True), ("買います。", "mua", False)]),
        S("先月、本を三冊読みました。", "Sengetsu, hon o sansatsu yomimashita.", "Tháng trước tôi đã đọc ba quyển sách.", [("先月、", "tháng trước", False), ("本を", "sách", False), ("三冊", "ba quyển", True), ("読みました。", "đã đọc", False)]),
        S("一週間に二回テニスをします。", "Isshuukan ni nikai tenisu o shimasu.", "Tôi chơi quần vợt hai lần một tuần.", [("一週間に", "trong một tuần", False), ("二回", "hai lần", True), ("テニスをします。", "chơi quần vợt", False)]),
        S("毎日二時間日本語を勉強します。", "Mainichi nijikan Nihongo o benkyou shimasu.", "Mỗi ngày tôi học tiếng Nhật hai tiếng.", [("毎日", "mỗi ngày", False), ("二時間", "hai tiếng", True), ("日本語を勉強します。", "học tiếng Nhật", False)]),
        S("日本に一年います。", "Nihon ni ichinen imasu.", "Tôi ở Nhật một năm.", [("日本に", "ở Nhật", False), ("一年", "một năm", True), ("います。", "ở", False)]),
        S("京都まで三時間かかります。", "Kyouto made sanjikan kakarimasu.", "Đến Kyoto mất ba tiếng.", [("京都まで", "đến Kyoto", False), ("三時間", "ba tiếng", True), ("かかります。", "mất", False)]),
        S("大阪から東京まで新幹線で二時間半かかります。", "Oosaka kara Toukyou made shinkansen de nijikanhan kakarimasu.", "Từ Osaka đến Tokyo bằng Shinkansen mất hai tiếng rưỡi.", [("大阪から東京まで", "từ Osaka đến Tokyo", False), ("新幹線で", "bằng Shinkansen", False), ("二時間半", "hai tiếng rưỡi", True), ("かかります。", "mất", False)]),
        S("この荷物を航空便で外国へ送ります。", "Kono nimotsu o koukuubin de gaikoku e okurimasu.", "Tôi gửi kiện hàng này ra nước ngoài bằng đường hàng không.", [("この荷物を", "kiện hàng này", False), ("航空便で", "bằng đường hàng không", True), ("外国へ送ります。", "gửi ra nước ngoài", False)]),
        S("船便で一か月ぐらいかかります。", "Funabin de ikkagetsu gurai kakarimasu.", "Gửi đường biển mất khoảng một tháng.", [("船便で", "bằng đường biển", False), ("一か月ぐらい", "khoảng một tháng", True), ("かかります。", "mất", False)]),
        S("この手紙は速達でお願いします。", "Kono tegami wa sokutatsu de onegai shimasu.", "Xin gửi lá thư này bằng chuyển phát nhanh.", [("この手紙は", "lá thư này thì", False), ("速達で", "bằng chuyển phát nhanh", True), ("お願いします。", "xin nhờ", False)]),
        S("封筒を一枚とはがきを二枚ください。", "Fuutou o ichimai to hagaki o nimai kudasai.", "Cho tôi một phong bì và hai bưu thiếp.", [("封筒を一枚と", "một phong bì và", True), ("はがきを二枚", "hai bưu thiếp", False), ("ください。", "xin cho tôi", False)]),
        S("りんごはいくつありますか。八つあります。", "Ringo wa ikutsu arimasu ka. Yattsu arimasu.", "Có bao nhiêu quả táo? Có tám quả.", [("りんごは", "táo thì", False), ("いくつありますか。", "có bao nhiêu", True), ("八つあります。", "có tám quả", False)]),
        S("学生が何人いますか。十五人います。", "Gakusei ga nannin imasu ka. Juugonin imasu.", "Có bao nhiêu học sinh? Có mười lăm người.", [("学生が", "học sinh", False), ("何人いますか。", "có bao nhiêu người", True), ("十五人います。", "có mười lăm người", False)]),
        S("日本にどのくらいいますか。三年います。", "Nihon ni dono kurai imasu ka. Sannen imasu.", "Bạn ở Nhật bao lâu? Ba năm.", [("日本に", "ở Nhật", False), ("どのくらいいますか。", "trong bao lâu", True), ("三年います。", "ở ba năm", False)]),
        S("全部でいくらですか。千二百円です。", "Zenbu de ikura desu ka. Sen nihyaku en desu.", "Tổng cộng bao nhiêu tiền? 1.200 yên.", [("全部で", "tổng cộng", True), ("いくらですか。", "bao nhiêu tiền", False), ("千二百円です。", "là 1.200 yên", False)]),
        S("先週、会社を一週間休みました。", "Senshuu, kaisha o isshuukan yasumimashita.", "Tuần trước tôi đã nghỉ công ty một tuần.", [("先週、", "tuần trước", False), ("会社を", "công ty", False), ("一週間", "một tuần", True), ("休みました。", "đã nghỉ", False)]),
        S("兄が一人と姉が二人います。", "Ani ga hitori to ane ga futari imasu.", "Tôi có một anh trai và hai chị gái.", [("兄が一人と", "một anh trai và", True), ("姉が二人", "hai chị gái", False), ("います。", "có", False)]),
        S("ちょっと郵便局まで。いっていらっしゃい。", "Chotto yuubinkyoku made. Itte irasshai.", "Tôi đi bưu điện một lát. Đi rồi về nhé.", [("ちょっと", "một lát", False), ("郵便局まで。", "đến bưu điện", True), ("いっていらっしゃい。", "đi rồi về nhé", False)]),
        S("いいお天気ですね。お出かけですか。", "Ii otenki desu ne. Odekake desu ka.", "Thời tiết đẹp nhỉ. Bạn ra ngoài à?", [("いいお天気ですね。", "thời tiết đẹp nhỉ", True), ("お出かけですか。", "bạn ra ngoài à", False)]),
    ],
    12: [
        S("きのうは雨でした。", "Kinou wa ame deshita.", "Hôm qua trời mưa.", [("きのうは", "hôm qua thì", False), ("雨でした。", "đã là trời mưa", True)]),
        S("おとといは雪でした。", "Ototoi wa yuki deshita.", "Hôm kia trời có tuyết.", [("おとといは", "hôm kia thì", False), ("雪でした。", "đã là trời tuyết", True)]),
        S("祇園祭はとてもにぎやかでした。", "Gion-matsuri wa totemo nigiyaka deshita.", "Lễ hội Gion đã rất nhộn nhịp.", [("祇園祭は", "lễ hội Gion thì", False), ("とても", "rất", False), ("にぎやかでした。", "đã nhộn nhịp", True)]),
        S("きのうのパーティーは静かじゃありませんでした。", "Kinou no paatii wa shizuka ja arimasen deshita.", "Bữa tiệc hôm qua không yên tĩnh.", [("きのうのパーティーは", "bữa tiệc hôm qua thì", False), ("静かじゃありませんでした。", "đã không yên tĩnh", True)]),
        S("大阪は暑かったですが、北海道は涼しかったです。", "Oosaka wa atsukatta desu ga, Hokkaidou wa suzushikatta desu.", "Osaka nóng, còn Hokkaido mát mẻ.", [("大阪は暑かったですが、", "Osaka đã nóng nhưng", True), ("北海道は", "Hokkaido thì", False), ("涼しかったです。", "đã mát mẻ", False)]),
        S("先週はとても忙しかったです。", "Senshuu wa totemo isogashikatta desu.", "Tuần trước tôi rất bận.", [("先週は", "tuần trước thì", False), ("とても", "rất", False), ("忙しかったです。", "đã bận", True)]),
        S("京都の旅行は楽しかったです。", "Kyouto no ryokou wa tanoshikatta desu.", "Chuyến du lịch Kyoto rất vui.", [("京都の旅行は", "chuyến du lịch Kyoto thì", False), ("楽しかったです。", "đã vui", True)]),
        S("ホテルの部屋はきれいでした。", "Hoteru no heya wa kirei deshita.", "Phòng khách sạn đã rất sạch đẹp.", [("ホテルの部屋は", "phòng khách sạn thì", False), ("きれいでした。", "đã sạch đẹp", True)]),
        S("ホテルの食事はおいしかったです。", "Hoteru no shokuji wa oishikatta desu.", "Bữa ăn tại khách sạn rất ngon.", [("ホテルの食事は", "bữa ăn khách sạn thì", False), ("おいしかったです。", "đã ngon", True)]),
        S("あの店のすしは高くなかったです。", "Ano mise no sushi wa takakunakatta desu.", "Sushi của cửa hàng kia đã không đắt.", [("あの店のすしは", "sushi của cửa hàng kia thì", False), ("高くなかったです。", "đã không đắt", True)]),
        S("きのうの天気はよくなかったです。", "Kinou no tenki wa yokunakatta desu.", "Thời tiết hôm qua không đẹp.", [("きのうの天気は", "thời tiết hôm qua thì", False), ("よくなかったです。", "đã không tốt", True)]),
        S("試験は簡単じゃありませんでした。", "Shiken wa kantan ja arimasen deshita.", "Bài thi đã không đơn giản.", [("試験は", "bài thi thì", False), ("簡単じゃありませんでした。", "đã không đơn giản", True)]),
        S("東京と大阪とどちらが大きいですか。", "Toukyou to Oosaka to dochira ga ookii desu ka.", "Tokyo và Osaka, nơi nào lớn hơn?", [("東京と大阪と", "Tokyo và Osaka", False), ("どちらが", "nơi nào", True), ("大きいですか。", "lớn hơn", False)]),
        S("東京のほうが大阪より大きいです。", "Toukyou no hou ga Oosaka yori ookii desu.", "Tokyo lớn hơn Osaka.", [("東京のほうが", "phía Tokyo", True), ("大阪より", "so với Osaka", False), ("大きいです。", "lớn hơn", False)]),
        S("飛行機と新幹線とどちらが速いですか。", "Hikouki to shinkansen to dochira ga hayai desu ka.", "Máy bay và Shinkansen, phương tiện nào nhanh hơn?", [("飛行機と新幹線と", "máy bay và Shinkansen", False), ("どちらが", "phương tiện nào", True), ("速いですか。", "nhanh hơn", False)]),
        S("飛行機のほうが新幹線より速いです。", "Hikouki no hou ga shinkansen yori hayai desu.", "Máy bay nhanh hơn Shinkansen.", [("飛行機のほうが", "phía máy bay", True), ("新幹線より", "so với Shinkansen", False), ("速いです。", "nhanh hơn", False)]),
        S("スポーツで何がいちばんおもしろいですか。", "Supootsu de nani ga ichiban omoshiroi desu ka.", "Trong các môn thể thao, môn nào thú vị nhất?", [("スポーツで", "trong các môn thể thao", False), ("何が", "môn nào", False), ("いちばんおもしろいですか。", "thú vị nhất", True)]),
        S("サッカーがいちばんおもしろいです。", "Sakkaa ga ichiban omoshiroi desu.", "Bóng đá thú vị nhất.", [("サッカーが", "bóng đá", False), ("いちばん", "nhất", True), ("おもしろいです。", "thú vị", False)]),
        S("日本の季節で春がいちばん好きです。", "Nihon no kisetsu de haru ga ichiban suki desu.", "Trong các mùa ở Nhật, tôi thích mùa xuân nhất.", [("日本の季節で", "trong các mùa ở Nhật", False), ("春が", "mùa xuân", False), ("いちばん好きです。", "thích nhất", True)]),
        S("山と海とどちらが好きですか。どちらも好きです。", "Yama to umi to dochira ga suki desu ka. Dochira mo suki desu.", "Bạn thích núi hay biển hơn? Tôi thích cả hai.", [("山と海と", "núi và biển", False), ("どちらが好きですか。", "thích bên nào hơn", True), ("どちらも好きです。", "thích cả hai", False)]),
        S("大阪と京都と奈良で奈良がいちばん静かです。", "Oosaka to Kyouto to Nara de Nara ga ichiban shizuka desu.", "Trong Osaka, Kyoto và Nara, Nara yên tĩnh nhất.", [("大阪と京都と奈良で", "trong Osaka, Kyoto và Nara", False), ("奈良が", "Nara", False), ("いちばん静かです。", "yên tĩnh nhất", True)]),
        S("冬は秋よりずっと寒いです。", "Fuyu wa aki yori zutto samui desu.", "Mùa đông lạnh hơn mùa thu rất nhiều.", [("冬は", "mùa đông thì", False), ("秋より", "so với mùa thu", False), ("ずっと寒いです。", "lạnh hơn nhiều", True)]),
        S("北海道は雪が多いです。", "Hokkaidou wa yuki ga ooi desu.", "Hokkaido có nhiều tuyết.", [("北海道は", "Hokkaido thì", False), ("雪が", "tuyết", False), ("多いです。", "nhiều", True)]),
        S("この荷物は重いですが、あの荷物は軽いです。", "Kono nimotsu wa omoi desu ga, ano nimotsu wa karui desu.", "Hành lý này nặng, còn hành lý kia nhẹ.", [("この荷物は重いですが、", "hành lý này nặng nhưng", True), ("あの荷物は", "hành lý kia thì", False), ("軽いです。", "nhẹ", False)]),
    ],
    13: [
        S("わたしは新しい車が欲しいです。", "Watashi wa atarashii kuruma ga hoshii desu.", "Tôi muốn một chiếc ô tô mới.", [("わたしは", "tôi thì", False), ("新しい車が", "ô tô mới", False), ("欲しいです。", "muốn có", True)]),
        S("誕生日にカメラが欲しいです。", "Tanjoubi ni kamera ga hoshii desu.", "Tôi muốn một chiếc máy ảnh vào sinh nhật.", [("誕生日に", "vào sinh nhật", False), ("カメラが", "máy ảnh", False), ("欲しいです。", "muốn có", True)]),
        S("今、何がいちばん欲しいですか。", "Ima, nani ga ichiban hoshii desu ka.", "Bây giờ bạn muốn thứ gì nhất?", [("今、", "bây giờ", False), ("何が", "thứ gì", False), ("いちばん欲しいですか。", "muốn nhất", True)]),
        S("時間が欲しいです。", "Jikan ga hoshii desu.", "Tôi muốn có thời gian.", [("時間が", "thời gian", False), ("欲しいです。", "muốn có", True)]),
        S("わたしは友達が欲しいです。", "Watashi wa tomodachi ga hoshii desu.", "Tôi muốn có bạn.", [("わたしは", "tôi thì", False), ("友達が", "bạn bè", False), ("欲しいです。", "muốn có", True)]),
        S("わたしは子どもが欲しくないです。", "Watashi wa kodomo ga hoshikunai desu.", "Tôi không muốn có con.", [("わたしは", "tôi thì", False), ("子どもが", "con", False), ("欲しくないです。", "không muốn có", True)]),
        S("夏休みに沖縄へ行きたいです。", "Natsuyasumi ni Okinawa e ikitai desu.", "Tôi muốn đi Okinawa vào kỳ nghỉ hè.", [("夏休みに", "vào kỳ nghỉ hè", False), ("沖縄へ", "đến Okinawa", False), ("行きたいです。", "muốn đi", True)]),
        S("週末は海で泳ぎたいです。", "Shuumatsu wa umi de oyogitai desu.", "Cuối tuần tôi muốn bơi ở biển.", [("週末は", "cuối tuần thì", False), ("海で", "ở biển", False), ("泳ぎたいです。", "muốn bơi", True)]),
        S("のどが渇きました。冷たい水を飲みたいです。", "Nodo ga kawakimashita. Tsumetai mizu o nomitai desu.", "Tôi khát rồi. Tôi muốn uống nước lạnh.", [("のどが渇きました。", "đã khát", False), ("冷たい水を", "nước lạnh", False), ("飲みたいです。", "muốn uống", True)]),
        S("おなかがすきました。何か食べたいです。", "Onaka ga sukimashita. Nanika tabetai desu.", "Tôi đói rồi. Tôi muốn ăn gì đó.", [("おなかがすきました。", "đã đói", False), ("何か", "thứ gì đó", False), ("食べたいです。", "muốn ăn", True)]),
        S("きょうは疲れましたから、何もしたくないです。", "Kyou wa tsukaremashita kara, nanimo shitakunai desu.", "Hôm nay vì mệt nên tôi không muốn làm gì cả.", [("きょうは疲れましたから、", "vì hôm nay đã mệt", False), ("何も", "không gì cả", False), ("したくないです。", "không muốn làm", True)]),
        S("どんな音楽を聞きたいですか。", "Donna ongaku o kikitai desu ka.", "Bạn muốn nghe loại nhạc nào?", [("どんな音楽を", "loại nhạc nào", False), ("聞きたいですか。", "muốn nghe", True)]),
        S("週末、何をしたいですか。映画を見たいです。", "Shuumatsu, nani o shitai desu ka. Eiga o mitai desu.", "Cuối tuần bạn muốn làm gì? Tôi muốn xem phim.", [("週末、何をしたいですか。", "cuối tuần muốn làm gì", True), ("映画を", "phim", False), ("見たいです。", "muốn xem", False)]),
        S("京都へ日本の文化を勉強しに行きます。", "Kyouto e Nihon no bunka o benkyou shi ni ikimasu.", "Tôi đi Kyoto để học văn hóa Nhật.", [("京都へ", "đến Kyoto", False), ("日本の文化を", "văn hóa Nhật", False), ("勉強しに行きます。", "đi để học", True)]),
        S("デパートへ買い物に行きます。", "Depaato e kaimono ni ikimasu.", "Tôi đi trung tâm thương mại để mua sắm.", [("デパートへ", "đến trung tâm thương mại", False), ("買い物に", "để mua sắm", True), ("行きます。", "đi", False)]),
        S("郵便局へ荷物を出しに行きます。", "Yuubinkyoku e nimotsu o dashi ni ikimasu.", "Tôi đi bưu điện để gửi kiện hàng.", [("郵便局へ", "đến bưu điện", False), ("荷物を", "kiện hàng", False), ("出しに行きます。", "đi để gửi", True)]),
        S("駅へ友達を迎えに行きます。", "Eki e tomodachi o mukae ni ikimasu.", "Tôi đi nhà ga để đón bạn.", [("駅へ", "đến nhà ga", False), ("友達を", "bạn", False), ("迎えに行きます。", "đi đón", True)]),
        S("喫茶店へコーヒーを飲みに行きませんか。", "Kissaten e koohii o nomi ni ikimasen ka.", "Bạn cùng đi quán cà phê uống cà phê không?", [("喫茶店へ", "đến quán cà phê", False), ("コーヒーを", "cà phê", False), ("飲みに行きませんか。", "cùng đi uống không", True)]),
        S("公園へ散歩に行きます。", "Kouen e sanpo ni ikimasu.", "Tôi đi công viên để đi dạo.", [("公園へ", "đến công viên", False), ("散歩に", "để đi dạo", True), ("行きます。", "đi", False)]),
        S("レストランへ昼ご飯を食べに行きました。", "Resutoran e hirugohan o tabe ni ikimashita.", "Tôi đã đi nhà hàng để ăn trưa.", [("レストランへ", "đến nhà hàng", False), ("昼ご飯を", "cơm trưa", False), ("食べに行きました。", "đã đi ăn", True)]),
        S("北海道へスキーに行きたいです。", "Hokkaidou e sukii ni ikitai desu.", "Tôi muốn đi Hokkaido để trượt tuyết.", [("北海道へ", "đến Hokkaido", False), ("スキーに", "để trượt tuyết", True), ("行きたいです。", "muốn đi", False)]),
        S("おなかがいっぱいですから、何も食べたくないです。", "Onaka ga ippai desu kara, nanimo tabetakunai desu.", "Vì no rồi nên tôi không muốn ăn gì cả.", [("おなかがいっぱいですから、", "vì đã no", False), ("何も", "không gì cả", False), ("食べたくないです。", "không muốn ăn", True)]),
        S("注文は何にしますか。カレーライスにします。", "Chuumon wa nani ni shimasu ka. Karee raisu ni shimasu.", "Bạn chọn gọi món gì? Tôi chọn cơm cà ri.", [("注文は何にしますか。", "chọn gọi món gì", True), ("カレーライスにします。", "chọn cơm cà ri", False)]),
        S("少々お待ちください。", "Shoushou omachi kudasai.", "Xin vui lòng đợi một chút.", [("少々", "một chút", False), ("お待ちください。", "xin vui lòng đợi", True)]),
    ],
    14: [
        S("ここに名前と住所を書いてください。", "Koko ni namae to juusho o kaite kudasai.", "Hãy viết tên và địa chỉ vào đây.", [("ここに", "vào đây", False), ("名前と住所を", "tên và địa chỉ", False), ("書いてください。", "hãy viết", True)]),
        S("ちょっと待ってください。", "Chotto matte kudasai.", "Xin hãy đợi một chút.", [("ちょっと", "một chút", False), ("待ってください。", "xin hãy đợi", True)]),
        S("右へ曲がってください。", "Migi e magatte kudasai.", "Xin hãy rẽ phải.", [("右へ", "sang phải", False), ("曲がってください。", "xin hãy rẽ", True)]),
        S("次の交差点を左へ曲がってください。", "Tsugi no kousaten o hidari e magatte kudasai.", "Xin hãy rẽ trái ở ngã tư tiếp theo.", [("次の交差点を", "tại ngã tư tiếp theo", False), ("左へ", "sang trái", False), ("曲がってください。", "xin hãy rẽ", True)]),
        S("まっすぐ行ってください。", "Massugu itte kudasai.", "Xin hãy đi thẳng.", [("まっすぐ", "thẳng", False), ("行ってください。", "xin hãy đi", True)]),
        S("信号を渡ってください。", "Shingou o watatte kudasai.", "Xin hãy đi qua chỗ đèn giao thông.", [("信号を", "chỗ đèn giao thông", False), ("渡ってください。", "xin hãy đi qua", True)]),
        S("急いでください。電車が来ます。", "Isoide kudasai. Densha ga kimasu.", "Xin hãy nhanh lên. Tàu sắp đến.", [("急いでください。", "xin hãy nhanh lên", True), ("電車が", "tàu điện", False), ("来ます。", "đến", False)]),
        S("この荷物を持ってください。", "Kono nimotsu o motte kudasai.", "Xin hãy cầm hành lý này.", [("この荷物を", "hành lý này", False), ("持ってください。", "xin hãy cầm", True)]),
        S("電気をつけてください。", "Denki o tsukete kudasai.", "Xin hãy bật đèn.", [("電気を", "đèn điện", False), ("つけてください。", "xin hãy bật", True)]),
        S("エアコンを消してください。", "Eakon o keshite kudasai.", "Xin hãy tắt điều hòa.", [("エアコンを", "điều hòa", False), ("消してください。", "xin hãy tắt", True)]),
        S("ドアを開けてください。", "Doa o akete kudasai.", "Xin hãy mở cửa.", [("ドアを", "cửa", False), ("開けてください。", "xin hãy mở", True)]),
        S("窓を閉めてください。", "Mado o shimete kudasai.", "Xin hãy đóng cửa sổ.", [("窓を", "cửa sổ", False), ("閉めてください。", "xin hãy đóng", True)]),
        S("コピーを十枚取ってください。", "Kopii o juumai totte kudasai.", "Xin hãy sao chép mười bản.", [("コピーを", "bản sao", False), ("十枚", "mười tờ", False), ("取ってください。", "xin hãy sao chép", True)]),
        S("この漢字を読んでください。", "Kono kanji o yonde kudasai.", "Xin hãy đọc chữ Kanji này.", [("この漢字を", "chữ Kanji này", False), ("読んでください。", "xin hãy đọc", True)]),
        S("先生は今学生と話しています。", "Sensei wa ima gakusei to hanashite imasu.", "Bây giờ giáo viên đang nói chuyện với học sinh.", [("先生は今", "bây giờ giáo viên", False), ("学生と", "với học sinh", False), ("話しています。", "đang nói chuyện", True)]),
        S("ミラーさんは電話をかけています。", "Miraa-san wa denwa o kakete imasu.", "Anh Miller đang gọi điện thoại.", [("ミラーさんは", "anh Miller thì", False), ("電話を", "điện thoại", False), ("かけています。", "đang gọi", True)]),
        S("マリアさんはレポートを書いています。", "Maria-san wa repooto o kaite imasu.", "Chị Maria đang viết báo cáo.", [("マリアさんは", "chị Maria thì", False), ("レポートを", "báo cáo", False), ("書いています。", "đang viết", True)]),
        S("子どもたちは公園で遊んでいます。", "Kodomotachi wa kouen de asonde imasu.", "Bọn trẻ đang chơi trong công viên.", [("子どもたちは", "bọn trẻ thì", False), ("公園で", "trong công viên", False), ("遊んでいます。", "đang chơi", True)]),
        S("雨が降っています。", "Ame ga futte imasu.", "Trời đang mưa.", [("雨が", "mưa", False), ("降っています。", "đang rơi", True)]),
        S("タクシーを呼びましょうか。", "Takushii o yobimashou ka.", "Tôi gọi taxi giúp nhé?", [("タクシーを", "taxi", False), ("呼びましょうか。", "tôi gọi giúp nhé", True)]),
        S("荷物を持ちましょうか。お願いします。", "Nimotsu o mochimashou ka. Onegai shimasu.", "Tôi cầm hành lý giúp nhé? Xin nhờ bạn.", [("荷物を", "hành lý", False), ("持ちましょうか。", "tôi cầm giúp nhé", True), ("お願いします。", "xin nhờ bạn", False)]),
        S("窓を開けましょうか。いいえ、けっこうです。", "Mado o akemashou ka. Iie, kekkou desu.", "Tôi mở cửa sổ nhé? Không, như vậy được rồi.", [("窓を", "cửa sổ", False), ("開けましょうか。", "tôi mở giúp nhé", True), ("いいえ、けっこうです。", "không, được rồi", False)]),
        S("駅までお願いします。", "Eki made onegai shimasu.", "Xin cho tôi đến nhà ga.", [("駅まで", "đến nhà ga", True), ("お願いします。", "xin nhờ", False)]),
        S("お釣りです。どうも。", "Otsuri desu. Doumo.", "Tiền thừa của bạn đây. Cảm ơn.", [("お釣りです。", "tiền thừa đây", True), ("どうも。", "cảm ơn", False)]),
    ],
    15: [
        S("ここで写真を撮ってもいいですか。", "Koko de shashin o totte mo ii desu ka.", "Tôi chụp ảnh ở đây được không?", [("ここで", "ở đây", False), ("写真を", "ảnh", False), ("撮ってもいいですか。", "chụp được không", True)]),
        S("このカタログを見てもいいですか。", "Kono katarogu o mite mo ii desu ka.", "Tôi xem cuốn catalog này được không?", [("このカタログを", "cuốn catalog này", False), ("見てもいいですか。", "xem được không", True)]),
        S("このパソコンを使ってもいいですか。", "Kono pasokon o tsukatte mo ii desu ka.", "Tôi dùng máy tính này được không?", [("このパソコンを", "máy tính này", False), ("使ってもいいですか。", "dùng được không", True)]),
        S("ここに座ってもいいですか。はい、どうぞ。", "Koko ni suwatte mo ii desu ka. Hai, douzo.", "Tôi ngồi đây được không? Vâng, xin mời.", [("ここに", "ở đây", False), ("座ってもいいですか。", "ngồi được không", True), ("はい、どうぞ。", "vâng, xin mời", False)]),
        S("窓を開けてもいいですか。", "Mado o akete mo ii desu ka.", "Tôi mở cửa sổ được không?", [("窓を", "cửa sổ", False), ("開けてもいいですか。", "mở được không", True)]),
        S("ここでたばこを吸ってはいけません。", "Koko de tabako o sutte wa ikemasen.", "Không được hút thuốc ở đây.", [("ここで", "ở đây", False), ("たばこを", "thuốc lá", False), ("吸ってはいけません。", "không được hút", True)]),
        S("美術館で写真を撮ってはいけません。", "Bijutsukan de shashin o totte wa ikemasen.", "Không được chụp ảnh trong bảo tàng mỹ thuật.", [("美術館で", "trong bảo tàng mỹ thuật", False), ("写真を", "ảnh", False), ("撮ってはいけません。", "không được chụp", True)]),
        S("ここに車を止めてはいけません。", "Koko ni kuruma o tomete wa ikemasen.", "Không được đỗ ô tô ở đây.", [("ここに", "ở đây", False), ("車を", "ô tô", False), ("止めてはいけません。", "không được đỗ", True)]),
        S("図書館で大きい声で話してはいけません。", "Toshokan de ookii koe de hanashite wa ikemasen.", "Không được nói lớn tiếng trong thư viện.", [("図書館で", "trong thư viện", False), ("大きい声で", "bằng giọng lớn", False), ("話してはいけません。", "không được nói", True)]),
        S("この部屋に入ってはいけません。", "Kono heya ni haitte wa ikemasen.", "Không được vào căn phòng này.", [("この部屋に", "vào căn phòng này", False), ("入ってはいけません。", "không được vào", True)]),
        S("ミラーさんは大阪に住んでいます。", "Miraa-san wa Oosaka ni sunde imasu.", "Anh Miller sống ở Osaka.", [("ミラーさんは", "anh Miller thì", False), ("大阪に", "ở Osaka", False), ("住んでいます。", "đang sống", True)]),
        S("佐藤さんは結婚しています。", "Satou-san wa kekkon shite imasu.", "Anh Sato đã kết hôn.", [("佐藤さんは", "anh Sato thì", False), ("結婚しています。", "đã kết hôn", True)]),
        S("田中さんは車を持っています。", "Tanaka-san wa kuruma o motte imasu.", "Anh Tanaka có ô tô.", [("田中さんは", "anh Tanaka thì", False), ("車を", "ô tô", False), ("持っています。", "có/sở hữu", True)]),
        S("わたしは山田さんを知っています。", "Watashi wa Yamada-san o shitte imasu.", "Tôi biết anh Yamada.", [("わたしは", "tôi thì", False), ("山田さんを", "anh Yamada", False), ("知っています。", "biết", True)]),
        S("あの人を知っていますか。いいえ、知りません。", "Ano hito o shitte imasu ka. Iie, shirimasen.", "Bạn có biết người kia không? Không, tôi không biết.", [("あの人を", "người kia", False), ("知っていますか。", "có biết không", True), ("いいえ、知りません。", "không, không biết", False)]),
        S("父は銀行で働いています。", "Chichi wa ginkou de hataraite imasu.", "Bố tôi làm việc tại ngân hàng.", [("父は", "bố tôi thì", False), ("銀行で", "tại ngân hàng", False), ("働いています。", "đang làm việc", True)]),
        S("母は大学で英語を教えています。", "Haha wa daigaku de Eigo o oshiete imasu.", "Mẹ tôi dạy tiếng Anh tại trường đại học.", [("母は大学で", "mẹ tại đại học", False), ("英語を", "tiếng Anh", False), ("教えています。", "đang dạy", True)]),
        S("姉はコンピューターの会社で働いています。", "Ane wa konpyuutaa no kaisha de hataraite imasu.", "Chị gái tôi làm việc tại công ty máy tính.", [("姉は", "chị gái tôi thì", False), ("コンピューターの会社で", "tại công ty máy tính", False), ("働いています。", "đang làm việc", True)]),
        S("弟は東京の大学で勉強しています。", "Otouto wa Toukyou no daigaku de benkyou shite imasu.", "Em trai tôi học tại một trường đại học ở Tokyo.", [("弟は", "em trai tôi thì", False), ("東京の大学で", "tại đại học ở Tokyo", False), ("勉強しています。", "đang học", True)]),
        S("ご家族はどこに住んでいますか。", "Gokazoku wa doko ni sunde imasu ka.", "Gia đình bạn sống ở đâu?", [("ご家族は", "gia đình bạn thì", False), ("どこに", "ở đâu", False), ("住んでいますか。", "đang sống", True)]),
        S("仕事は何ですか。日本語を教えています。", "Shigoto wa nan desu ka. Nihongo o oshiete imasu.", "Công việc của bạn là gì? Tôi dạy tiếng Nhật.", [("仕事は何ですか。", "công việc là gì", True), ("日本語を", "tiếng Nhật", False), ("教えています。", "đang dạy", False)]),
        S("市役所の電話番号を知っていますか。", "Shiyakusho no denwa bangou o shitte imasu ka.", "Bạn có biết số điện thoại tòa thị chính không?", [("市役所の電話番号を", "số điện thoại tòa thị chính", False), ("知っていますか。", "có biết không", True)]),
        S("資料をもらってもいいですか。はい、どうぞ。", "Shiryou o moratte mo ii desu ka. Hai, douzo.", "Tôi nhận tài liệu này được không? Vâng, xin mời.", [("資料を", "tài liệu", False), ("もらってもいいですか。", "nhận được không", True), ("はい、どうぞ。", "vâng, xin mời", False)]),
        S("残念ですが、きょうはちょっと……。", "Zannen desu ga, kyou wa chotto...", "Rất tiếc nhưng hôm nay tôi hơi bận...", [("残念ですが、", "rất tiếc nhưng", True), ("きょうは", "hôm nay thì", False), ("ちょっと……。", "hơi không tiện", False)]),
    ],
}


LESSON_PASSAGES = {
    11: {
        "title": "郵便局で — Tại bưu điện",
        "content": [
            {"text": "外国の友達に荷物を送ります。", "furigana": "がいこくのともだちにもつをおくります", "meaning": "Tôi gửi kiện hàng cho người bạn ở nước ngoài.", "note": "人に物を送ります: gửi một vật cho ai."},
            {"text": "箱の中に本が二冊あります。", "furigana": "はこのなかにほんがにさつあります", "meaning": "Trong hộp có hai quyển sách.", "note": "冊 là lượng từ đếm sách và quyển."},
            {"text": "CDが三枚あります。", "furigana": "シーディーがさんまいあります", "meaning": "Có ba đĩa CD.", "note": "枚 đếm vật mỏng và phẳng, bao gồm đĩa."},
            {"text": "航空便でお願いします。", "furigana": "こうくうびんでおねがいします", "meaning": "Xin gửi bằng đường hàng không.", "note": "で chỉ phương thức gửi."},
            {"text": "外国まで一週間ぐらいかかります。", "furigana": "がいこくまでいっしゅうかんぐらいかかります", "meaning": "Đến nước ngoài mất khoảng một tuần.", "note": "Khoảng thời gian + かかります diễn tả thời gian cần thiết."},
            {"text": "全部で三千円です。", "furigana": "ぜんぶでさんぜんえんです", "meaning": "Tổng cộng là 3.000 yên.", "note": "全部で nghĩa là tổng cộng."},
            {"text": "切手を五枚とはがきを二枚買いました。", "furigana": "きってをごまいとはがきをにまいかいました", "meaning": "Tôi cũng đã mua năm con tem và hai bưu thiếp.", "note": "Số + 枚 đứng trước động từ để nêu số lượng."},
        ],
    },
    12: {
        "title": "北海道の旅行 — Chuyến đi Hokkaido",
        "content": [
            {"text": "先週、家族と北海道へ行きました。", "furigana": "せんしゅう、かぞくとほっかいどうへいきました", "meaning": "Tuần trước tôi đã đi Hokkaido cùng gia đình.", "note": "と chỉ người đồng hành."},
            {"text": "北海道は大阪よりずっと寒かったです。", "furigana": "ほっかいどうはおおさかよりずっとさむかったです", "meaning": "Hokkaido lạnh hơn Osaka rất nhiều.", "note": "AはBより… diễn tả A hơn B."},
            {"text": "雪がとても多かったです。", "furigana": "ゆきがとてもおおかったです", "meaning": "Tuyết đã rất nhiều.", "note": "多い đổi sang quá khứ là 多かったです."},
            {"text": "ホテルは静かできれいでした。", "furigana": "ホテルはしずかできれいでした", "meaning": "Khách sạn yên tĩnh và sạch đẹp.", "note": "な-adjective ở quá khứ kết thúc bằng でした."},
            {"text": "食事もおいしかったです。", "furigana": "しょくじもおいしかったです", "meaning": "Bữa ăn cũng ngon.", "note": "い-adjective đổi い thành かったです ở quá khứ."},
            {"text": "北海道の食べ物で魚がいちばんおいしかったです。", "furigana": "ほっかいどうのたべものでさかながいちばんおいしかったです", "meaning": "Trong đồ ăn Hokkaido, cá là ngon nhất.", "note": "Phạm vi で Nがいちばん… diễn tả nhất trong một nhóm."},
            {"text": "旅行はとても楽しかったです。", "furigana": "りょこうはとてもたのしかったです", "meaning": "Chuyến đi rất vui.", "note": "楽しい có dạng quá khứ là 楽しかったです."},
        ],
    },
    13: {
        "title": "夏休みの予定 — Kế hoạch nghỉ hè",
        "content": [
            {"text": "夏休みに沖縄へ行きたいです。", "furigana": "なつやすみにおきなわへいきたいです", "meaning": "Tôi muốn đi Okinawa vào kỳ nghỉ hè.", "note": "Gốc ます + たいです diễn tả mong muốn làm việc gì."},
            {"text": "青い海で泳ぎたいです。", "furigana": "あおいうみでおよぎたいです", "meaning": "Tôi muốn bơi ở biển xanh.", "note": "で chỉ nơi thực hiện hành động bơi."},
            {"text": "きれいな写真も撮りたいです。", "furigana": "きれいなしゃしんもとりたいです", "meaning": "Tôi cũng muốn chụp những bức ảnh đẹp.", "note": "も mang nghĩa cũng."},
            {"text": "沖縄の料理を食べたいです。", "furigana": "おきなわのりょうりをたべたいです", "meaning": "Tôi muốn ăn món Okinawa.", "note": "を đánh dấu đối tượng của 食べたいです."},
            {"text": "新しいカメラが欲しいです。", "furigana": "あたらしいカメラがほしいです", "meaning": "Tôi muốn một chiếc máy ảnh mới.", "note": "Nが欲しいです diễn tả mong muốn sở hữu."},
            {"text": "週末、デパートへカメラを買いに行きます。", "furigana": "しゅうまつ、デパートへカメラをかいにいきます", "meaning": "Cuối tuần tôi đi trung tâm thương mại để mua máy ảnh.", "note": "Gốc ます + に行きます nêu mục đích di chuyển."},
            {"text": "沖縄でゆっくり休みたいです。", "furigana": "おきなわでゆっくりやすみたいです", "meaning": "Tôi muốn thư giãn thong thả ở Okinawa.", "note": "ゆっくり bổ nghĩa cho hành động nghỉ ngơi."},
        ],
    },
    14: {
        "title": "駅までお願いします — Xin cho đến nhà ga",
        "content": [
            {"text": "タクシーに乗ります。", "furigana": "タクシーにのります", "meaning": "Tôi lên taxi.", "note": "乗ります dùng に với phương tiện lên."},
            {"text": "駅までお願いします。", "furigana": "えきまでおねがいします", "meaning": "Xin cho tôi đến nhà ga.", "note": "Địa điểm までお願いします là cách nói với tài xế."},
            {"text": "次の交差点を右へ曲がってください。", "furigana": "つぎのこうさてんをみぎへまがってください", "meaning": "Xin hãy rẽ phải ở ngã tư tiếp theo.", "note": "Vてください tạo lời yêu cầu lịch sự."},
            {"text": "それから、まっすぐ行ってください。", "furigana": "それから、まっすぐいってください", "meaning": "Sau đó xin hãy đi thẳng.", "note": "行きます có thể て là 行って."},
            {"text": "あの信号の前で止めてください。", "furigana": "あのしんごうのまえでとめてください", "meaning": "Xin hãy dừng trước đèn giao thông kia.", "note": "止めます đổi sang て-form là 止めて."},
            {"text": "運転手さんは今道を見ています。", "furigana": "うんてんしゅさんはいまみちをみています", "meaning": "Bây giờ tài xế đang nhìn đường.", "note": "Vています diễn tả hành động đang diễn ra."},
            {"text": "お釣りをもらって、タクシーを降ります。", "furigana": "おつりをもらって、タクシーをおります", "meaning": "Tôi nhận tiền thừa rồi xuống taxi.", "note": "Câu ôn các từ hội thoại của bài; chuỗi hành động sẽ học sâu hơn ở bài sau."},
        ],
    },
    15: {
        "title": "図書館のルール — Quy định thư viện",
        "content": [
            {"text": "図書館で本を読んでもいいです。", "furigana": "としょかんでほんをよんでもいいです", "meaning": "Bạn được phép đọc sách trong thư viện.", "note": "Vてもいいです diễn tả sự cho phép."},
            {"text": "図書館のパソコンを使ってもいいです。", "furigana": "としょかんのパソコンをつかってもいいです", "meaning": "Bạn được phép dùng máy tính của thư viện.", "note": "Vてもいいですか dùng để xin phép."},
            {"text": "でも、大きい声で話してはいけません。", "furigana": "でも、おおきいこえではなしてはいけません", "meaning": "Nhưng không được nói lớn tiếng.", "note": "Vてはいけません diễn tả điều bị cấm."},
            {"text": "ここで食べ物を食べてはいけません。", "furigana": "ここでたべものをたべてはいけません", "meaning": "Không được ăn ở đây.", "note": "で chỉ nơi áp dụng hành động bị cấm."},
            {"text": "あの人は図書館で働いています。", "furigana": "あのひとはとしょかんではたらいています", "meaning": "Người kia làm việc tại thư viện.", "note": "Vています có thể diễn tả nghề nghiệp hoặc thói quen."},
            {"text": "田中さんは近くに住んでいます。", "furigana": "たなかさんはちかくにすんでいます", "meaning": "Anh Tanaka sống ở gần đây.", "note": "住んでいます diễn tả trạng thái đang cư trú."},
            {"text": "田中さんは図書館の電話番号も知っています。", "furigana": "たなかさんはとしょかんのでんわばんごもしっています", "meaning": "Anh Tanaka cũng biết số điện thoại thư viện.", "note": "知っています nghĩa là đang có thông tin, biết."},
        ],
    },
}
