"""Comprehensive chunk-based seed content for Minna no Nihongo lessons 31-35."""

LESSON_SENTENCES = {
    31: [
        {
            "full_japanese": "週末は海へ行こうと思っています。",
            "full_romaji": "Shuumatsu wa umi e ikou to omotte imasu.",
            "full_vietnamese": "Cuối tuần tôi dự định sẽ đi biển.",
            "chunks": [
                (1, "週末は", "cuối tuần thì", False),
                (2, "海へ", "đến biển", False),
                (3, "行こうと", "đi (thể ý chí)", False),
                (4, "思っています。", "tôi đang dự định", True),
            ],
        },
        {
            "full_japanese": "将来、自分の会社を作るつもりです。",
            "full_romaji": "Shourai, jibun no kaisha o tsukuru tsumori desu.",
            "full_vietnamese": "Tương lai, tôi dự định sẽ thành lập công ty của riêng mình.",
            "chunks": [
                (1, "将来、", "trong tương lai,", False),
                (2, "自分の会社を", "công ty của chính mình", False),
                (3, "作る", "làm / thành lập", False),
                (4, "つもりです。", "tôi dự định sẽ", True),
            ],
        },
        {
            "full_japanese": "来年からはタバコを吸わないつもりです。",
            "full_romaji": "Rainen kara wa tabako o suwanai tsumori desu.",
            "full_vietnamese": "Từ năm sau tôi dự định sẽ không hút thuốc nữa.",
            "chunks": [
                (1, "来年からは", "từ năm sau thì", False),
                (2, "タバコを", "thuốc lá", False),
                (3, "吸わない", "không hút", False),
                (4, "つもりです。", "tôi dự định sẽ", True),
            ],
        },
        {
            "full_japanese": "７月の終わりに、ドイツへ出張する予定です。",
            "full_romaji": "Shichigatsu no owari ni, Doitsu e shucchou suru yotei desu.",
            "full_vietnamese": "Vào cuối tháng 7, theo kế hoạch tôi sẽ đi công tác ở Đức.",
            "chunks": [
                (1, "７月の終わりに、", "vào cuối tháng 7,", False),
                (2, "ドイツへ", "đến Đức", False),
                (3, "出張する", "đi công tác", False),
                (4, "予定です。", "theo kế hoạch là", True),
            ],
        },
        {
            "full_japanese": "会議は10時からの予定です。",
            "full_romaji": "Kaigi wa juuji kara no yotei desu.",
            "full_vietnamese": "Cuộc họp dự kiến bắt đầu từ 10 giờ.",
            "chunks": [
                (1, "会議は", "cuộc họp thì", False),
                (2, "10時からの", "từ 10 giờ", False),
                (3, "予定です。", "theo kế hoạch là", True),
            ],
        },
        {
            "full_japanese": "明日から毎日作文を書こうと思っています。",
            "full_romaji": "Ashita kara mainichi sakubun o kakou to omotte imasu.",
            "full_vietnamese": "Từ ngày mai tôi định viết văn mỗi ngày.",
            "chunks": [
                (1, "明日から", "từ ngày mai", False),
                (2, "毎日", "mỗi ngày", False),
                (3, "作文を", "bài văn", False),
                (4, "書こうと", "sẽ viết (ý chí)", True),
                (5, "思っています。", "đang định", False),
            ],
        },
        {
            "full_japanese": "大学院の試験を受けるつもりです。",
            "full_romaji": "Daigakuin no shiken o ukeru tsumori desu.",
            "full_vietnamese": "Tôi định dự thi cao học.",
            "chunks": [
                (1, "大学院の試験を", "kỳ thi cao học", False),
                (2, "受ける", "dự thi", False),
                (3, "つもりです。", "dự định sẽ", True),
            ],
        },
        {
            "full_japanese": "卒業してから、本社で働く予定です。",
            "full_romaji": "Sotsugyou shite kara, honsha de hataraku yotei desu.",
            "full_vietnamese": "Sau khi tốt nghiệp, theo kế hoạch tôi sẽ làm việc ở trụ sở chính.",
            "chunks": [
                (1, "卒業してから、", "sau khi tốt nghiệp,", False),
                (2, "本社で", "ở trụ sở chính", False),
                (3, "働く", "làm việc", False),
                (4, "予定です。", "theo kế hoạch", True),
            ],
        },
        {
            "full_japanese": "展覧会に出席しようと思っています。",
            "full_romaji": "Tenrankai ni shusseki shiyou to omotte imasu.",
            "full_vietnamese": "Tôi định tham dự buổi triển lãm.",
            "chunks": [
                (1, "展覧会に", "buổi triển lãm", False),
                (2, "出席しようと", "định tham dự", True),
                (3, "思っています。", "đang nghĩ/dự định", False),
            ],
        },
        {
            "full_japanese": "来月の連休は温泉へ行くつもりです。",
            "full_romaji": "Raigetsu no renkyuu wa onsen e iku tsumori desu.",
            "full_vietnamese": "Kỳ nghỉ liền ngày tháng sau tôi định đi suối nước nóng.",
            "chunks": [
                (1, "来月の連休は", "kỳ nghỉ liền ngày tháng sau thì", False),
                (2, "温泉へ", "đến suối nước nóng", False),
                (3, "行く", "đi", False),
                (4, "つもりです。", "dự định sẽ", True),
            ],
        },
    ],
    32: [
        {
            "full_japanese": "毎日、運動したほうがいいですよ。",
            "full_romaji": "Mainichi, undou shita hou ga ii desu yo.",
            "full_vietnamese": "Mỗi ngày bạn nên vận động thì tốt hơn đấy.",
            "chunks": [
                (1, "毎日、", "mỗi ngày,", False),
                (2, "運動した", "đã vận động", False),
                (3, "ほうがいいですよ。", "thì tốt hơn đấy (khuyên nhủ)", True),
            ],
        },
        {
            "full_japanese": "熱があるんですか。じゃ、お風呂に入らないほうがいいですよ。",
            "full_romaji": "Netsu ga arun desu ka. Ja, ofuro ni hairanai hou ga ii desu yo.",
            "full_vietnamese": "Bạn bị sốt à? Thế thì không nên tắm đâu.",
            "chunks": [
                (1, "熱が", "sốt", False),
                (2, "あるんですか。", "bị (sốt) à?", False),
                (3, "じゃ、", "thế thì,", True),
                (4, "お風呂に", "vào bồn tắm", False),
                (5, "入らないほうがいいですよ。", "không nên vào thì tốt hơn đấy.", True),
            ],
        },
        {
            "full_japanese": "明日は雨が降るでしょう。",
            "full_romaji": "Ashita wa ame ga furu deshou.",
            "full_vietnamese": "Có lẽ ngày mai trời sẽ mưa.",
            "chunks": [
                (1, "明日は", "ngày mai thì", False),
                (2, "雨が降る", "trời mưa", False),
                (3, "でしょう。", "có lẽ (phỏng đoán)", True),
            ],
        },
        {
            "full_japanese": "午後は雪になるかもしれません。",
            "full_romaji": "Gogo wa yuki ni naru kamo shiremasen.",
            "full_vietnamese": "Biết đâu chiều nay trời sẽ có tuyết.",
            "chunks": [
                (1, "午後は", "buổi chiều thì", False),
                (2, "雪になる", "trở thành tuyết", False),
                (3, "かもしれません。", "cũng không biết chừng (xác suất thấp)", True),
            ],
        },
        {
            "full_japanese": "約束の時間に間に合わないかもしれません。",
            "full_romaji": "Yakusoku no jikan ni maniawanai kamo shiremasen.",
            "full_vietnamese": "Không chừng chúng ta sẽ không kịp giờ hẹn mất.",
            "chunks": [
                (1, "約束の時間に", "vào giờ hẹn", False),
                (2, "間に合わない", "không kịp", False),
                (3, "かもしれません。", "cũng không biết chừng", True),
            ],
        },
        {
            "full_japanese": "咳が出ますから、無理をしないほうがいいです。",
            "full_romaji": "Seki ga demasu kara, muri o shinai hou ga ii desu.",
            "full_vietnamese": "Vì bạn bị ho nên không nên làm quá sức.",
            "chunks": [
                (1, "咳が", "cơn ho", False),
                (2, "出ますから、", "vì xuất hiện/bị", False),
                (3, "無理をしない", "không làm quá sức", True),
                (4, "ほうがいいです。", "thì tốt hơn", False),
            ],
        },
        {
            "full_japanese": "今夜は風が強くなるでしょう。",
            "full_romaji": "Konya wa kaze ga tsuyoku naru deshou.",
            "full_vietnamese": "Tối nay có lẽ gió sẽ mạnh lên.",
            "chunks": [
                (1, "今夜は", "tối nay thì", False),
                (2, "風が", "gió", False),
                (3, "強くなる", "trở nên mạnh", False),
                (4, "でしょう。", "có lẽ", True),
            ],
        },
        {
            "full_japanese": "薬を飲めば、すぐ治るかもしれません。",
            "full_romaji": "Kusuri o nomeba, sugu naoru kamo shiremasen.",
            "full_vietnamese": "Nếu uống thuốc, có thể sẽ khỏi ngay.",
            "chunks": [
                (1, "薬を", "thuốc", False),
                (2, "飲めば、", "nếu uống,", False),
                (3, "すぐ", "ngay", False),
                (4, "治る", "khỏi", False),
                (5, "かもしれません。", "có thể", True),
            ],
        },
        {
            "full_japanese": "試験は難しいかもしれません。",
            "full_romaji": "Shiken wa muzukashii kamo shiremasen.",
            "full_vietnamese": "Bài thi có thể sẽ khó.",
            "chunks": [
                (1, "試験は", "bài thi thì", False),
                (2, "難しい", "khó", False),
                (3, "かもしれません。", "có thể", True),
            ],
        },
        {
            "full_japanese": "十分休んだほうがいいですよ。",
            "full_romaji": "Juubun yasunda hou ga ii desu yo.",
            "full_vietnamese": "Bạn nên nghỉ ngơi đầy đủ thì tốt hơn đấy.",
            "chunks": [
                (1, "十分", "đầy đủ", False),
                (2, "休んだ", "đã nghỉ", False),
                (3, "ほうがいいですよ。", "nên... thì tốt hơn đấy", True),
            ],
        },
    ],
    33: [
        {
            "full_japanese": "早く起きろ！",
            "full_romaji": "Hayaku okiro!",
            "full_vietnamese": "Dậy sớm đi!",
            "chunks": [
                (1, "早く", "sớm", False),
                (2, "起きろ！", "hãy dậy! (mệnh lệnh)", True),
            ],
        },
        {
            "full_japanese": "ここに車を止めるな！",
            "full_romaji": "Koko ni kuruma o tomeru na!",
            "full_vietnamese": "Không được đỗ xe ở đây!",
            "chunks": [
                (1, "ここに", "ở đây", False),
                (2, "車を止める", "đỗ xe", False),
                (3, "な！", "cấm! (cấm chỉ)", True),
            ],
        },
        {
            "full_japanese": "あそこに「止まれ」と書いてあります。",
            "full_romaji": "Asoko ni 'tomare' to kaite arimasu.",
            "full_vietnamese": "Ở đằng kia có viết chữ 'Dừng lại'.",
            "chunks": [
                (1, "あそこに", "ở đằng kia", False),
                (2, "「止まれ」と", "rằng 'Hãy dừng lại'", False),
                (3, "書いてあります。", "có viết (trạng thái)", True),
            ],
        },
        {
            "full_japanese": "「立入禁止」は入るなという意味です。",
            "full_romaji": "'Tachiiri kinshi' wa hairu na to iu imi desu.",
            "full_vietnamese": "'Tachiiri kinshi' có nghĩa là cấm vào.",
            "chunks": [
                (1, "「立入禁止」は", "chữ 'Cấm vào' thì", False),
                (2, "入るなと", "cấm vào", False),
                (3, "いう意味です。", "có ý nghĩa là", True),
            ],
        },
        {
            "full_japanese": "田中さんは明日休むと言っていました。",
            "full_romaji": "Tanaka-san wa ashita yasumu to itte imashita.",
            "full_vietnamese": "Anh Tanaka đã nói là ngày mai anh ấy sẽ nghỉ.",
            "chunks": [
                (1, "田中さんは", "anh Tanaka thì", False),
                (2, "明日休むと", "rằng ngày mai nghỉ", False),
                (3, "言っていました。", "đã nói", True),
            ],
        },
        {
            "full_japanese": "非常口には「走るな」と書いてあります。",
            "full_romaji": "Hijouguchi ni wa 'hashiru na' to kaite arimasu.",
            "full_vietnamese": "Ở cửa thoát hiểm có viết 'Không được chạy'.",
            "chunks": [
                (1, "非常口には", "ở cửa thoát hiểm thì", False),
                (2, "「走るな」と", "rằng 'không được chạy'", True),
                (3, "書いてあります。", "có viết", False),
            ],
        },
        {
            "full_japanese": "先生はボールを投げろと言いました。",
            "full_romaji": "Sensei wa booru o nagero to iimashita.",
            "full_vietnamese": "Thầy/cô đã nói: 'Hãy ném bóng'.",
            "chunks": [
                (1, "先生は", "thầy/cô thì", False),
                (2, "ボールを", "quả bóng", False),
                (3, "投げろと", "rằng hãy ném", True),
                (4, "言いました。", "đã nói", False),
            ],
        },
        {
            "full_japanese": "このマークは写真を撮るなという意味です。",
            "full_romaji": "Kono maaku wa shashin o toru na to iu imi desu.",
            "full_vietnamese": "Ký hiệu này có nghĩa là cấm chụp ảnh.",
            "chunks": [
                (1, "このマークは", "ký hiệu này thì", False),
                (2, "写真を撮るなと", "cấm chụp ảnh", True),
                (3, "いう意味です。", "có nghĩa là", False),
            ],
        },
        {
            "full_japanese": "規則を守れと注意されました。",
            "full_romaji": "Kisoku o mamore to chuui saremashita.",
            "full_vietnamese": "Tôi đã bị nhắc là hãy tuân thủ quy tắc.",
            "chunks": [
                (1, "規則を", "quy tắc", False),
                (2, "守れと", "rằng hãy tuân thủ", True),
                (3, "注意されました。", "đã bị nhắc nhở", False),
            ],
        },
        {
            "full_japanese": "警察はここに入るなと言っています。",
            "full_romaji": "Keisatsu wa koko ni hairu na to itte imasu.",
            "full_vietnamese": "Cảnh sát đang nói rằng không được vào đây.",
            "chunks": [
                (1, "警察は", "cảnh sát thì", False),
                (2, "ここに", "vào đây", False),
                (3, "入るなと", "rằng cấm vào", True),
                (4, "言っています。", "đang nói", False),
            ],
        },
    ],
    34: [
        {
            "full_japanese": "私が言うとおりに、書いてください。",
            "full_romaji": "Watashi ga iu toori ni, kaite kudasai.",
            "full_vietnamese": "Xin hãy viết đúng như những gì tôi nói.",
            "chunks": [
                (1, "私が言う", "những gì tôi nói", False),
                (2, "とおりに、", "đúng theo như,", True),
                (3, "書いてください。", "xin hãy viết.", False),
            ],
        },
        {
            "full_japanese": "線のとおりに、紙を切ってください。",
            "full_romaji": "Sen no toori ni, kami o kitte kudasai.",
            "full_vietnamese": "Xin hãy cắt giấy theo đúng đường kẻ.",
            "chunks": [
                (1, "線の", "đường kẻ", False),
                (2, "とおりに、", "đúng theo như,", True),
                (3, "紙を切ってください。", "xin hãy cắt giấy.", False),
            ],
        },
        {
            "full_japanese": "仕事のあとで、飲みに行きませんか。",
            "full_romaji": "Shigoto no ato de, nomi ni ikimasen ka.",
            "full_vietnamese": "Sau khi xong việc, có muốn đi uống chút gì không?",
            "chunks": [
                (1, "仕事の", "công việc", False),
                (2, "あとで、", "sau khi,", True),
                (3, "飲みに", "để uống", False),
                (4, "行きませんか。", "đi... không?", False),
            ],
        },
        {
            "full_japanese": "新しいのを買ったあとで、なくした時計が見つかりました。",
            "full_romaji": "Atarashii no o katta ato de, nakushita tokei ga mitsukarimashita.",
            "full_vietnamese": "Sau khi tôi đã mua cái mới thì lại tìm thấy cái đồng hồ bị mất.",
            "chunks": [
                (1, "新しいのを", "cái (đồng hồ) mới", False),
                (2, "買った", "đã mua", False),
                (3, "あとで、", "sau khi,", True),
                (4, "なくした時計が", "cái đồng hồ đã mất", False),
                (5, "見つかりました。", "đã được tìm thấy.", False),
            ],
        },
        {
            "full_japanese": "コーヒーに砂糖を入れないで飲みます。",
            "full_romaji": "Koohii ni satou o irenaide nomimasu.",
            "full_vietnamese": "Tôi uống cà phê mà không bỏ đường.",
            "chunks": [
                (1, "コーヒーに", "vào cà phê", False),
                (2, "砂糖を", "đường", False),
                (3, "入れないで", "không bỏ (mà để nguyên trạng thái)", True),
                (4, "飲みます。", "uống.", False),
            ],
        },
        {
            "full_japanese": "説明書のとおりに組み立ててください。",
            "full_romaji": "Setsumeisho no toori ni kumitatete kudasai.",
            "full_vietnamese": "Xin hãy lắp ráp theo đúng sách hướng dẫn.",
            "chunks": [
                (1, "説明書の", "của sách hướng dẫn", False),
                (2, "とおりに", "đúng theo như", True),
                (3, "組み立てて", "lắp ráp", False),
                (4, "ください。", "xin hãy", False),
            ],
        },
        {
            "full_japanese": "歯を磨いたあとで、寝ます。",
            "full_romaji": "Ha o migaita ato de, nemasu.",
            "full_vietnamese": "Sau khi đánh răng, tôi đi ngủ.",
            "chunks": [
                (1, "歯を", "răng", False),
                (2, "磨いた", "đã đánh", False),
                (3, "あとで、", "sau khi", True),
                (4, "寝ます。", "ngủ", False),
            ],
        },
        {
            "full_japanese": "茶道の先生がするように、お茶をたてます。",
            "full_romaji": "Sadou no sensei ga suru you ni, ocha o tatemasu.",
            "full_vietnamese": "Tôi pha trà giống như thầy/cô trà đạo làm.",
            "chunks": [
                (1, "茶道の先生が", "thầy/cô trà đạo", False),
                (2, "するように、", "theo như cách làm", True),
                (3, "お茶を", "trà", False),
                (4, "たてます。", "pha trà", False),
            ],
        },
        {
            "full_japanese": "朝ご飯を食べないで会社へ行きました。",
            "full_romaji": "Asagohan o tabenaide kaisha e ikimashita.",
            "full_vietnamese": "Tôi đã đi làm mà không ăn sáng.",
            "chunks": [
                (1, "朝ご飯を", "bữa sáng", False),
                (2, "食べないで", "không ăn mà", True),
                (3, "会社へ", "đến công ty", False),
                (4, "行きました。", "đã đi", False),
            ],
        },
        {
            "full_japanese": "矢印のとおりに進んでください。",
            "full_romaji": "Yajirushi no toori ni susunde kudasai.",
            "full_vietnamese": "Xin hãy đi theo đúng mũi tên.",
            "chunks": [
                (1, "矢印の", "của mũi tên", False),
                (2, "とおりに", "đúng theo", True),
                (3, "進んで", "tiến đi", False),
                (4, "ください。", "xin hãy", False),
            ],
        },
    ],
    35: [
        {
            "full_japanese": "ボタンを押せば、窓が開きます。",
            "full_romaji": "Botan o oseba, mado ga akimasu.",
            "full_vietnamese": "Nếu bấm nút, cửa sổ sẽ mở.",
            "chunks": [
                (1, "ボタンを", "nút", False),
                (2, "押せば、", "nếu bấm (thể điều kiện),", True),
                (3, "窓が", "cửa sổ", False),
                (4, "開きます。", "sẽ mở.", False),
            ],
        },
        {
            "full_japanese": "天気がよければ、山が見えます。",
            "full_romaji": "Tenki ga yokereba, yama ga miemasu.",
            "full_vietnamese": "Nếu thời tiết đẹp, sẽ có thể nhìn thấy núi.",
            "chunks": [
                (1, "天気が", "thời tiết", False),
                (2, "よければ、", "nếu tốt,", True),
                (3, "山が", "núi", False),
                (4, "見えます。", "có thể nhìn thấy.", False),
            ],
        },
        {
            "full_japanese": "明日、時間がなければ、行きません。",
            "full_romaji": "Ashita, jikan ga nakereba, ikimasen.",
            "full_vietnamese": "Ngày mai nếu không có thời gian, tôi sẽ không đi.",
            "chunks": [
                (1, "明日、", "ngày mai,", False),
                (2, "時間が", "thời gian", False),
                (3, "なければ、", "nếu không có,", True),
                (4, "行きません。", "tôi sẽ không đi.", False),
            ],
        },
        {
            "full_japanese": "パソコンを買いたいんですが、どこで買えばいいですか。",
            "full_romaji": "Pasokon o kaitain desu ga, doko de kaeba ii desu ka.",
            "full_vietnamese": "Tôi muốn mua máy tính, nên mua ở đâu thì tốt nhỉ?",
            "chunks": [
                (1, "パソコンを", "máy tính", False),
                (2, "買いたいんですが、", "tôi muốn mua (trình bày hoàn cảnh),", False),
                (3, "どこで", "ở đâu", False),
                (4, "買えばいい", "nếu mua thì tốt", True),
                (5, "ですか。", "nhỉ?", False),
            ],
        },
        {
            "full_japanese": "温泉なら、白馬がいいですよ。",
            "full_romaji": "Onsen nara, Hakuba ga ii desu yo.",
            "full_vietnamese": "Nếu là suối nước nóng thì Hakuba được đấy.",
            "chunks": [
                (1, "温泉", "suối nước nóng", False),
                (2, "なら、", "nếu là (giới hạn phạm vi),", True),
                (3, "白馬が", "Hakuba (địa danh)", False),
                (4, "いいですよ。", "tốt đấy.", False),
            ],
        },
        {
            "full_japanese": "春になれば、桜が咲きます。",
            "full_romaji": "Haru ni nareba, sakura ga sakimasu.",
            "full_vietnamese": "Nếu đến mùa xuân, hoa anh đào sẽ nở.",
            "chunks": [
                (1, "春に", "thành mùa xuân", False),
                (2, "なれば、", "nếu trở thành/đến", True),
                (3, "桜が", "hoa anh đào", False),
                (4, "咲きます。", "sẽ nở", False),
            ],
        },
        {
            "full_japanese": "操作方法がわからなければ、係の人に聞いてください。",
            "full_romaji": "Sousa houhou ga wakaranakereba, kakari no hito ni kiite kudasai.",
            "full_vietnamese": "Nếu không hiểu cách thao tác, hãy hỏi nhân viên phụ trách.",
            "chunks": [
                (1, "操作方法が", "cách thao tác", False),
                (2, "わからなければ、", "nếu không hiểu", True),
                (3, "係の人に", "người phụ trách", False),
                (4, "聞いてください。", "hãy hỏi", False),
            ],
        },
        {
            "full_japanese": "正しければ、丸を付けてください。",
            "full_romaji": "Tadashikereba, maru o tsukete kudasai.",
            "full_vietnamese": "Nếu đúng, xin hãy đánh dấu tròn.",
            "chunks": [
                (1, "正しければ、", "nếu đúng", True),
                (2, "丸を", "dấu tròn", False),
                (3, "付けて", "đánh dấu", False),
                (4, "ください。", "xin hãy", False),
            ],
        },
        {
            "full_japanese": "海外旅行なら、旅行社に相談したほうがいいです。",
            "full_romaji": "Kaigai ryokou nara, ryokousha ni soudan shita hou ga ii desu.",
            "full_vietnamese": "Nếu là du lịch nước ngoài thì nên trao đổi với công ty du lịch.",
            "chunks": [
                (1, "海外旅行", "du lịch nước ngoài", False),
                (2, "なら、", "nếu là", True),
                (3, "旅行社に", "với công ty du lịch", False),
                (4, "相談したほうがいいです。", "nên trao đổi thì tốt hơn", False),
            ],
        },
        {
            "full_japanese": "時間があれば、山登りに行きたいです。",
            "full_romaji": "Jikan ga areba, yamanobori ni ikitai desu.",
            "full_vietnamese": "Nếu có thời gian, tôi muốn đi leo núi.",
            "chunks": [
                (1, "時間が", "thời gian", False),
                (2, "あれば、", "nếu có", True),
                (3, "山登りに", "để leo núi", False),
                (4, "行きたいです。", "muốn đi", False),
            ],
        },
    ],
}

LESSON_PASSAGES = {
    31: [
        {
            "title": "夏休みの予定 — Kế hoạch nghỉ hè",
            "content": [
                {"text": "今年の", "meaning": "Của năm nay"},
                {"text": "夏休みは", "meaning": "kỳ nghỉ hè thì"},
                {"text": "国へ", "meaning": "về nước"},
                {"text": "帰るんですか。", "meaning": "bạn sẽ về chứ?"},
                {"text": "いいえ、", "meaning": "Không,"},
                {"text": "帰らないつもりです。", "meaning": "tôi dự định sẽ không về.", "note": "つもりです dùng để diễn tả ý định đã được quyết định."},
                {"text": "大学院の", "meaning": "Của cao học"},
                {"text": "試験が", "meaning": "kỳ thi"},
                {"text": "ありますから。", "meaning": "vì có."},
                {"text": "そうですか。", "meaning": "Vậy à."},
                {"text": "がんばってくださいね。", "meaning": "Hãy cố gắng lên nhé."}
            ],
        },
        {
            "title": "連休の計画 — Kế hoạch kỳ nghỉ liền ngày",
            "content": [
                {"text": "来月の連休は", "meaning": "Kỳ nghỉ liền ngày tháng sau thì"},
                {"text": "どこへ", "meaning": "đi đâu"},
                {"text": "行く予定ですか。", "meaning": "theo kế hoạch sẽ đi?", "note": "予定です dùng cho kế hoạch hoặc lịch trình đã được sắp xếp."},
                {"text": "温泉へ", "meaning": "đến suối nước nóng"},
                {"text": "行こうと", "meaning": "sẽ đi"},
                {"text": "思っています。", "meaning": "tôi đang định.", "note": "意向形 + と思っています diễn tả ý định đang giữ trong đầu."},
                {"text": "でも、", "meaning": "Nhưng,"},
                {"text": "雨なら", "meaning": "nếu trời mưa thì"},
                {"text": "家で", "meaning": "ở nhà"},
                {"text": "作文を", "meaning": "bài văn"},
                {"text": "書くつもりです。", "meaning": "tôi định viết.", "note": "Vる + つもりです nói dự định làm."},
            ],
        },
    ],
    32: [
        {
            "title": "天気予報 — Dự báo thời tiết",
            "content": [
                {"text": "今日の", "meaning": "Của hôm nay"},
                {"text": "天気予報", "meaning": "dự báo thời tiết"},
                {"text": "見ましたか。", "meaning": "bạn đã xem chưa?"},
                {"text": "ええ。", "meaning": "Rồi."},
                {"text": "午後は", "meaning": "Buổi chiều thì"},
                {"text": "雨が", "meaning": "mưa"},
                {"text": "降るかもしれません。", "meaning": "có thể sẽ rơi.", "note": "かもしれません diễn tả phỏng đoán với xác suất thấp (khoảng 50%)."},
                {"text": "じゃ、", "meaning": "Vậy thì,"},
                {"text": "傘を", "meaning": "cái ô"},
                {"text": "持って行った", "meaning": "mang đi"},
                {"text": "ほうがいいですね。", "meaning": "thì tốt hơn nhỉ.", "note": "ほうがいいです dùng để khuyên nhủ ai đó nên làm gì."}
            ],
        },
        {
            "title": "体の調子 — Tình trạng cơ thể",
            "content": [
                {"text": "昨日から", "meaning": "Từ hôm qua"},
                {"text": "せきが", "meaning": "cơn ho"},
                {"text": "続いています。", "meaning": "vẫn tiếp tục."},
                {"text": "それはいけませんね。", "meaning": "Vậy thì không ổn rồi."},
                {"text": "今日は", "meaning": "Hôm nay"},
                {"text": "無理をしない", "meaning": "không làm quá sức"},
                {"text": "ほうがいいですよ。", "meaning": "thì tốt hơn đấy.", "note": "Vない + ほうがいいです dùng để khuyên không nên làm."},
                {"text": "熱も", "meaning": "Sốt cũng"},
                {"text": "あるかもしれませんから、", "meaning": "có thể có nên,"},
                {"text": "病院へ", "meaning": "đến bệnh viện"},
                {"text": "行ったほうがいいです。", "meaning": "nên đi."},
            ],
        },
    ],
    33: [
        {
            "title": "標識の意味 — Ý nghĩa của biển báo",
            "content": [
                {"text": "あそこに", "meaning": "Ở đằng kia"},
                {"text": "何と", "meaning": "(là) chữ gì"},
                {"text": "書いてあるんですか。", "meaning": "có viết thế?"},
                {"text": "「止まれ」と", "meaning": "Rằng 'Hãy dừng lại'"},
                {"text": "書いてあります。", "meaning": "có viết."},
                {"text": "どういう", "meaning": "Thế nào"},
                {"text": "意味ですか。", "meaning": "là ý nghĩa?"},
                {"text": "車を", "meaning": "Xe ô tô"},
                {"text": "止めるなと", "meaning": "rằng cấm đỗ"},
                {"text": "いう意味です。", "meaning": "là có ý nghĩa đó.", "note": "～という意味です dùng để giải thích ý nghĩa của một từ hoặc ký hiệu."}
            ],
        },
        {
            "title": "学校の規則 — Nội quy trường học",
            "content": [
                {"text": "先生は", "meaning": "Thầy/cô thì"},
                {"text": "教室で", "meaning": "trong lớp học"},
                {"text": "騒ぐなと", "meaning": "rằng không được ồn ào", "note": "辞書形 + な là dạng cấm mạnh."},
                {"text": "言っていました。", "meaning": "đã nói."},
                {"text": "壁には", "meaning": "Trên tường thì"},
                {"text": "「携帯電話使用禁止」と", "meaning": "rằng 'Cấm dùng điện thoại'"},
                {"text": "書いてあります。", "meaning": "có viết."},
                {"text": "これは", "meaning": "Điều này"},
                {"text": "授業中に", "meaning": "trong giờ học"},
                {"text": "電話を使うな", "meaning": "không được dùng điện thoại"},
                {"text": "という意味です。", "meaning": "có nghĩa là."},
            ],
        },
    ],
    34: [
        {
            "title": "料理の作り方 — Cách nấu ăn",
            "content": [
                {"text": "この料理の", "meaning": "Của món ăn này"},
                {"text": "作り方を", "meaning": "cách làm"},
                {"text": "教えてください。", "meaning": "hãy chỉ cho tôi."},
                {"text": "はい。", "meaning": "Vâng."},
                {"text": "私が", "meaning": "Tôi"},
                {"text": "するとおりに、", "meaning": "theo đúng như tôi làm,", "note": "とおりに nghĩa là làm giống y hệt một mẫu hoặc hành động trước đó."},
                {"text": "やってください。", "meaning": "hãy làm theo."},
                {"text": "野菜を", "meaning": "Rau"},
                {"text": "切ったあとで、", "meaning": "sau khi cắt,", "note": "Vた + あとで nghĩa là sau khi hoàn tất việc V."},
                {"text": "肉と", "meaning": "với thịt"},
                {"text": "炒めます。", "meaning": "sẽ xào."}
            ],
        },
        {
            "title": "家具を組み立てる — Lắp đồ nội thất",
            "content": [
                {"text": "この家具は", "meaning": "Đồ nội thất này thì"},
                {"text": "説明書の", "meaning": "của sách hướng dẫn"},
                {"text": "とおりに", "meaning": "đúng theo như", "note": "Nのとおりに nghĩa là theo đúng danh từ/mẫu đã nêu."},
                {"text": "組み立ててください。", "meaning": "hãy lắp ráp."},
                {"text": "線のとおりに", "meaning": "theo đúng đường kẻ"},
                {"text": "板を", "meaning": "tấm ván"},
                {"text": "折らないで、", "meaning": "không bẻ/gấp mà,"},
                {"text": "矢印の方向へ", "meaning": "về hướng mũi tên"},
                {"text": "動かします。", "meaning": "di chuyển."},
                {"text": "終わったあとで、", "meaning": "sau khi xong,"},
                {"text": "ねじを", "meaning": "ốc vít"},
                {"text": "もう一度確認してください。", "meaning": "hãy kiểm tra lại lần nữa."},
            ],
        },
    ],
    35: [
        {
            "title": "電化製品の使い方 — Cách dùng đồ điện",
            "content": [
                {"text": "この", "meaning": "Cái này"},
                {"text": "コピー機は", "meaning": "máy photocopy thì"},
                {"text": "どうやって", "meaning": "làm thế nào"},
                {"text": "使うんですか。", "meaning": "để dùng vậy?"},
                {"text": "ここに", "meaning": "Ở đây"},
                {"text": "紙を", "meaning": "giấy"},
                {"text": "入れれば、", "meaning": "nếu cho vào,", "note": "Vれば là thể điều kiện, nếu làm V thì kết quả sẽ xảy ra."},
                {"text": "動きますよ。", "meaning": "nó sẽ hoạt động đấy."},
                {"text": "もし", "meaning": "Giả sử"},
                {"text": "動かなければ、", "meaning": "nếu nó không hoạt động,"},
                {"text": "あの", "meaning": "cái kia"},
                {"text": "赤いボタンを", "meaning": "nút màu đỏ"},
                {"text": "押してください。", "meaning": "hãy bấm."}
            ],
        },
        {
            "title": "旅行の相談 — Tư vấn du lịch",
            "content": [
                {"text": "海外旅行なら、", "meaning": "Nếu là du lịch nước ngoài thì", "note": "Nなら dùng để nêu chủ đề giả định hoặc phạm vi."},
                {"text": "旅行社に", "meaning": "với công ty du lịch"},
                {"text": "相談したほうがいいです。", "meaning": "nên trao đổi thì tốt hơn."},
                {"text": "時間が", "meaning": "Thời gian"},
                {"text": "あれば、", "meaning": "nếu có,"},
                {"text": "詳しい", "meaning": "chi tiết"},
                {"text": "パンフレットを", "meaning": "tờ thông tin"},
                {"text": "もらえます。", "meaning": "có thể nhận."},
                {"text": "山登りなら、", "meaning": "Nếu là leo núi thì"},
                {"text": "春に", "meaning": "vào mùa xuân"},
                {"text": "行けば", "meaning": "nếu đi"},
                {"text": "花が咲いていて、", "meaning": "hoa đang nở,"},
                {"text": "きれいですよ。", "meaning": "đẹp đấy."},
            ],
        },
    ],
}
