"""Curated Minna no Nihongo learning content for lessons 16 through 20."""

from __future__ import annotations


def _sentence(japanese: str, romaji: str, vietnamese: str, chunks: list[tuple[str, str, bool]]) -> dict[str, object]:
    return {
        "full_japanese": japanese,
        "full_romaji": romaji,
        "full_vietnamese": vietnamese,
        "chunks": [(i, text, meaning, key) for i, (text, meaning, key) in enumerate(chunks, 1)],
    }


S = _sentence


LESSON_SENTENCES = {
    16: [
        S("朝起きて、顔を洗って、朝御飯を食べます。", "Asa okite, kao o aratte, asagohan o tabemasu.", "Buổi sáng tôi thức dậy, rửa mặt rồi ăn sáng.", [("朝起きて、", "buổi sáng thức dậy rồi", True), ("顔を洗って、", "rửa mặt rồi", False), ("朝御飯を食べます。", "ăn sáng", False)]),
        S("シャワーを浴びて、会社へ行きます。", "Shawaa o abite, kaisha e ikimasu.", "Tôi tắm vòi sen rồi đi làm.", [("シャワーを浴びて、", "tắm vòi sen rồi", True), ("会社へ行きます。", "đi công ty", False)]),
        S("駅まで歩いて、電車に乗ります。", "Eki made aruite, densha ni norimasu.", "Tôi đi bộ đến ga rồi lên tàu.", [("駅まで歩いて、", "đi bộ đến ga rồi", True), ("電車に乗ります。", "lên tàu", False)]),
        S("京都駅で電車を降りて、バスに乗り換えます。", "Kyouto-eki de densha o orite, basu ni norikaemasu.", "Tôi xuống tàu ở ga Kyoto rồi chuyển sang xe buýt.", [("京都駅で", "tại ga Kyoto", False), ("電車を降りて、", "xuống tàu rồi", True), ("バスに乗り換えます。", "chuyển sang xe buýt", False)]),
        S("十六番のバスに乗って、大学前で降ります。", "Juurokuba n no basu ni notte, daigaku-mae de orimasu.", "Tôi lên xe buýt số 16 rồi xuống trước trường đại học.", [("十六番のバスに乗って、", "lên xe buýt số 16 rồi", True), ("大学前で降ります。", "xuống trước đại học", False)]),
        S("銀行へ行って、お金を下ろします。", "Ginkou e itte, okane o oroshimasu.", "Tôi đến ngân hàng rồi rút tiền.", [("銀行へ行って、", "đến ngân hàng rồi", True), ("お金を下ろします。", "rút tiền", False)]),
        S("お金を下ろしてから、買い物に行きます。", "Okane o oroshite kara, kaimono ni ikimasu.", "Sau khi rút tiền, tôi đi mua sắm.", [("お金を下ろしてから、", "sau khi rút tiền", True), ("買い物に行きます。", "đi mua sắm", False)]),
        S("晩御飯を食べてから、宿題をします。", "Bangohan o tabete kara, shukudai o shimasu.", "Sau khi ăn tối, tôi làm bài tập.", [("晩御飯を食べてから、", "sau khi ăn tối", True), ("宿題をします。", "làm bài tập", False)]),
        S("大学を出てから、日本の会社に入りました。", "Daigaku o dete kara, Nihon no kaisha ni hairimashita.", "Sau khi tốt nghiệp đại học, tôi đã vào một công ty Nhật.", [("大学を出てから、", "sau khi tốt nghiệp đại học", True), ("日本の会社に入りました。", "đã vào công ty Nhật", False)]),
        S("仕事が終わってから、ジョギングをします。", "Shigoto ga owatte kara, jogingu o shimasu.", "Sau khi làm việc xong, tôi chạy bộ.", [("仕事が終わってから、", "sau khi công việc kết thúc", True), ("ジョギングをします。", "chạy bộ", False)]),
        S("この部屋は広くて、明るいです。", "Kono heya wa hirokute, akarui desu.", "Căn phòng này rộng và sáng.", [("この部屋は", "căn phòng này thì", False), ("広くて、", "rộng và", True), ("明るいです。", "sáng", False)]),
        S("このかばんは軽くて、便利です。", "Kono kaban wa karukute, benri desu.", "Chiếc cặp này nhẹ và tiện lợi.", [("このかばんは", "chiếc cặp này thì", False), ("軽くて、", "nhẹ và", True), ("便利です。", "tiện lợi", False)]),
        S("奈良は静かで、緑が多いです。", "Nara wa shizuka de, midori ga ooi desu.", "Nara yên tĩnh và có nhiều cây xanh.", [("奈良は", "Nara thì", False), ("静かで、", "yên tĩnh và", True), ("緑が多いです。", "có nhiều cây xanh", False)]),
        S("ミラーさんは若くて、元気です。", "Miraa-san wa wakakute, genki desu.", "Anh Miller trẻ và khỏe mạnh.", [("ミラーさんは", "anh Miller thì", False), ("若くて、", "trẻ và", True), ("元気です。", "khỏe mạnh", False)]),
        S("山田さんは親切で、頭がいいです。", "Yamada-san wa shinsetsu de, atama ga ii desu.", "Anh Yamada tốt bụng và thông minh.", [("山田さんは", "anh Yamada thì", False), ("親切で、", "tốt bụng và", True), ("頭がいいです。", "thông minh", False)]),
        S("大阪は食べ物がおいしいです。", "Oosaka wa tabemono ga oishii desu.", "Osaka có đồ ăn ngon.", [("大阪は", "Osaka thì", False), ("食べ物が", "đồ ăn", True), ("おいしいです。", "ngon", False)]),
        S("マリアさんは髪が長いです。", "Maria-san wa kami ga nagai desu.", "Chị Maria có mái tóc dài.", [("マリアさんは", "chị Maria thì", False), ("髪が", "tóc", True), ("長いです。", "dài", False)]),
        S("あの男の人は背が高いです。", "Ano otoko no hito wa se ga takai desu.", "Người đàn ông kia cao.", [("あの男の人は", "người đàn ông kia thì", False), ("背が", "chiều cao", True), ("高いです。", "cao", False)]),
        S("あの女の子は目が大きいです。", "Ano onna no ko wa me ga ookii desu.", "Bé gái kia có đôi mắt to.", [("あの女の子は", "bé gái kia thì", False), ("目が", "mắt", True), ("大きいです。", "to", False)]),
        S("大学までどうやって行きますか。", "Daigaku made douyatte ikimasu ka.", "Bạn đến trường đại học bằng cách nào?", [("大学まで", "đến đại học", False), ("どうやって", "bằng cách nào", True), ("行きますか。", "đi", False)]),
        S("駅からバスに乗って、大学前で降ります。", "Eki kara basu ni notte, daigaku-mae de orimasu.", "Từ ga tôi lên xe buýt rồi xuống trước đại học.", [("駅から", "từ ga", False), ("バスに乗って、", "lên xe buýt rồi", True), ("大学前で降ります。", "xuống trước đại học", False)]),
        S("山田さんはどの人ですか。", "Yamada-san wa dono hito desu ka.", "Anh Yamada là người nào?", [("山田さんは", "anh Yamada thì", False), ("どの人ですか。", "là người nào", True)]),
        S("あの背が高くて、髪が短い人です。", "Ano se ga takakute, kami ga mijikai hito desu.", "Là người cao và tóc ngắn kia.", [("あの", "kia", False), ("背が高くて、", "cao và", True), ("髪が短い人です。", "là người tóc ngắn", False)]),
        S("まずカードを入れて、次に暗証番号を押してください。", "Mazu kaado o irete, tsugi ni anshou bangou o oshite kudasai.", "Trước hết hãy cho thẻ vào, tiếp theo hãy bấm mã PIN.", [("まずカードを入れて、", "trước hết cho thẻ vào", True), ("次に", "tiếp theo", False), ("暗証番号を押してください。", "hãy bấm mã PIN", False)]),
    ],
    17: [
        S("ここで写真を撮らないでください。", "Koko de shashin o toranaide kudasai.", "Xin đừng chụp ảnh ở đây.", [("ここで", "ở đây", False), ("写真を", "ảnh", False), ("撮らないでください。", "xin đừng chụp", True)]),
        S("この部屋に入らないでください。", "Kono heya ni hairanaide kudasai.", "Xin đừng vào căn phòng này.", [("この部屋に", "vào căn phòng này", False), ("入らないでください。", "xin đừng vào", True)]),
        S("大切な書類をなくさないでください。", "Taisetsu na shorui o nakusanaide kudasai.", "Xin đừng làm mất tài liệu quan trọng.", [("大切な書類を", "tài liệu quan trọng", False), ("なくさないでください。", "xin đừng làm mất", True)]),
        S("パスポートを忘れないでください。", "Pasupooto o wasurenaide kudasai.", "Xin đừng quên hộ chiếu.", [("パスポートを", "hộ chiếu", False), ("忘れないでください。", "xin đừng quên", True)]),
        S("ここに車を止めないでください。", "Koko ni kuruma o tomenaide kudasai.", "Xin đừng đỗ xe ở đây.", [("ここに", "ở đây", False), ("車を", "ô tô", False), ("止めないでください。", "xin đừng đỗ", True)]),
        S("あしたまでにレポートを出さなければなりません。", "Ashita made ni repooto o dasanakereba narimasen.", "Tôi phải nộp báo cáo trước ngày mai.", [("あしたまでに", "trước ngày mai", False), ("レポートを", "báo cáo", False), ("出さなければなりません。", "phải nộp", True)]),
        S("毎日漢字を覚えなければなりません。", "Mainichi kanji o oboenakereba narimasen.", "Mỗi ngày tôi phải học thuộc Kanji.", [("毎日", "mỗi ngày", False), ("漢字を", "Kanji", False), ("覚えなければなりません。", "phải học thuộc", True)]),
        S("銀行へ行って、お金を払わなければなりません。", "Ginkou e itte, okane o harawanakereba narimasen.", "Tôi phải đến ngân hàng và trả tiền.", [("銀行へ行って、", "đến ngân hàng rồi", False), ("お金を", "tiền", False), ("払わなければなりません。", "phải trả", True)]),
        S("九時までに会社へ行かなければなりません。", "Kuji made ni kaisha e ikanakereba narimasen.", "Tôi phải đến công ty trước chín giờ.", [("九時までに", "trước chín giờ", False), ("会社へ", "đến công ty", False), ("行かなければなりません。", "phải đi", True)]),
        S("日本のうちで靴を脱がなければなりません。", "Nihon no uchi de kutsu o nuganakereba narimasen.", "Trong nhà Nhật phải cởi giày.", [("日本のうちで", "trong nhà Nhật", False), ("靴を", "giày", False), ("脱がなければなりません。", "phải cởi", True)]),
        S("薬を一日三回飲まなければなりません。", "Kusuri o ichinichi sankai nomanakereba narimasen.", "Tôi phải uống thuốc ba lần một ngày.", [("薬を", "thuốc", False), ("一日三回", "ba lần một ngày", False), ("飲まなければなりません。", "phải uống", True)]),
        S("きょうは残業しなければなりません。", "Kyou wa zangyou shinakereba narimasen.", "Hôm nay tôi phải làm thêm giờ.", [("きょうは", "hôm nay thì", False), ("残業しなければなりません。", "phải làm thêm giờ", True)]),
        S("あしたは早く起きなくてもいいです。", "Ashita wa hayaku okinakute mo ii desu.", "Ngày mai không cần dậy sớm.", [("あしたは", "ngày mai thì", False), ("早く", "sớm", False), ("起きなくてもいいです。", "không cần thức dậy", True)]),
        S("土曜日は会社へ行かなくてもいいです。", "Doyoubi wa kaisha e ikanakute mo ii desu.", "Thứ Bảy không cần đến công ty.", [("土曜日は", "thứ Bảy thì", False), ("会社へ", "đến công ty", False), ("行かなくてもいいです。", "không cần đi", True)]),
        S("この薬は飲まなくてもいいです。", "Kono kusuri wa nomanakute mo ii desu.", "Thuốc này không cần uống.", [("この薬は", "thuốc này thì", False), ("飲まなくてもいいです。", "không cần uống", True)]),
        S("上着を脱がなくてもいいです。", "Uwagi o nuganakute mo ii desu.", "Bạn không cần cởi áo khoác.", [("上着を", "áo khoác", False), ("脱がなくてもいいです。", "không cần cởi", True)]),
        S("宿題はきょう出さなくてもいいです。", "Shukudai wa kyou dasanakute mo ii desu.", "Bài tập không cần nộp hôm nay.", [("宿題は", "bài tập thì", False), ("きょう", "hôm nay", False), ("出さなくてもいいです。", "không cần nộp", True)]),
        S("金曜日までに本を返してください。", "Kinyoubi made ni hon o kaeshite kudasai.", "Hãy trả sách trước thứ Sáu.", [("金曜日までに", "trước thứ Sáu", True), ("本を", "sách", False), ("返してください。", "hãy trả", False)]),
        S("会議は五時までに終わります。", "Kaigi wa goji made ni owarimasu.", "Cuộc họp sẽ kết thúc trước năm giờ.", [("会議は", "cuộc họp thì", False), ("五時までに", "trước năm giờ", True), ("終わります。", "kết thúc", False)]),
        S("どうしましたか。頭が痛いです。", "Dou shimashita ka. Atama ga itai desu.", "Bạn bị sao vậy? Tôi đau đầu.", [("どうしましたか。", "bạn bị sao vậy", True), ("頭が痛いです。", "đau đầu", False)]),
        S("熱がありますから、二、三日休んでください。", "Netsu ga arimasu kara, ni-sannichi yasunde kudasai.", "Vì bạn bị sốt nên hãy nghỉ hai, ba ngày.", [("熱がありますから、", "vì bị sốt", False), ("二、三日", "hai, ba ngày", False), ("休んでください。", "hãy nghỉ", True)]),
        S("今晩はお風呂に入らないでください。", "Konban wa ofuro ni hairanaide kudasai.", "Tối nay xin đừng tắm bồn.", [("今晩は", "tối nay thì", False), ("お風呂に", "vào bồn tắm", False), ("入らないでください。", "xin đừng vào", True)]),
        S("保険証を持って来なければなりません。", "Hokenshou o motte konakereba narimasen.", "Tôi phải mang thẻ bảo hiểm đến.", [("保険証を", "thẻ bảo hiểm", False), ("持って来なければなりません。", "phải mang đến", True)]),
        S("もう大丈夫です。お大事に。", "Mou daijoubu desu. Odaiji ni.", "Giờ tôi ổn rồi. Chúc bạn mau khỏe.", [("もう大丈夫です。", "giờ đã ổn", True), ("お大事に。", "chúc mau khỏe", False)]),
    ],
    18: [
        S("わたしは車を運転することができます。", "Watashi wa kuruma o unten suru koto ga dekimasu.", "Tôi có thể lái ô tô.", [("わたしは", "tôi thì", False), ("車を運転することが", "việc lái ô tô", False), ("できます。", "có thể", True)]),
        S("ミラーさんは日本語を話すことができます。", "Miraa-san wa Nihongo o hanasu koto ga dekimasu.", "Anh Miller có thể nói tiếng Nhật.", [("ミラーさんは", "anh Miller thì", False), ("日本語を話すことが", "việc nói tiếng Nhật", False), ("できます。", "có thể", True)]),
        S("ここで馬に乗ることができます。", "Koko de uma ni noru koto ga dekimasu.", "Ở đây có thể cưỡi ngựa.", [("ここで", "ở đây", False), ("馬に乗ることが", "việc cưỡi ngựa", False), ("できます。", "có thể", True)]),
        S("このカードで現金を下ろすことができます。", "Kono kaado de genkin o orosu koto ga dekimasu.", "Có thể rút tiền mặt bằng thẻ này.", [("このカードで", "bằng thẻ này", False), ("現金を下ろすことが", "việc rút tiền mặt", False), ("できます。", "có thể", True)]),
        S("このホテルでインターネットができます。", "Kono hoteru de intaanetto ga dekimasu.", "Có thể sử dụng Internet tại khách sạn này.", [("このホテルで", "tại khách sạn này", False), ("インターネットが", "Internet", False), ("できます。", "có thể dùng", True)]),
        S("マリアさんはピアノができます。", "Maria-san wa piano ga dekimasu.", "Chị Maria biết chơi piano.", [("マリアさんは", "chị Maria thì", False), ("ピアノが", "piano", False), ("できます。", "biết chơi", True)]),
        S("わたしは百メートル泳ぐことができます。", "Watashi wa hyaku meetoru oyogu koto ga dekimasu.", "Tôi có thể bơi 100 mét.", [("わたしは", "tôi thì", False), ("百メートル泳ぐことが", "việc bơi 100 mét", False), ("できます。", "có thể", True)]),
        S("漢字を読むことができません。", "Kanji o yomu koto ga dekimasen.", "Tôi không thể đọc Kanji.", [("漢字を読むことが", "việc đọc Kanji", False), ("できません。", "không thể", True)]),
        S("趣味は写真を撮ることです。", "Shumi wa shashin o toru koto desu.", "Sở thích của tôi là chụp ảnh.", [("趣味は", "sở thích thì", False), ("写真を撮ることです。", "là chụp ảnh", True)]),
        S("父の趣味は車を運転することです。", "Chichi no shumi wa kuruma o unten suru koto desu.", "Sở thích của bố tôi là lái xe.", [("父の趣味は", "sở thích của bố thì", False), ("車を運転することです。", "là lái xe", True)]),
        S("母の趣味は花を集めることです。", "Haha no shumi wa hana o atsumeru koto desu.", "Sở thích của mẹ tôi là sưu tầm hoa.", [("母の趣味は", "sở thích của mẹ thì", False), ("花を集めることです。", "là sưu tầm hoa", True)]),
        S("弟の趣味は歌を歌うことです。", "Otouto no shumi wa uta o utau koto desu.", "Sở thích của em trai tôi là hát.", [("弟の趣味は", "sở thích của em trai thì", False), ("歌を歌うことです。", "là hát", True)]),
        S("毎晩寝る前に日記を書きます。", "Maiban neru mae ni nikki o kakimasu.", "Mỗi tối trước khi ngủ tôi viết nhật ký.", [("毎晩", "mỗi tối", False), ("寝る前に", "trước khi ngủ", True), ("日記を書きます。", "viết nhật ký", False)]),
        S("食事の前に手を洗います。", "Shokuji no mae ni te o araimasu.", "Trước bữa ăn tôi rửa tay.", [("食事の前に", "trước bữa ăn", True), ("手を洗います。", "rửa tay", False)]),
        S("会議の前に資料をコピーします。", "Kaigi no mae ni shiryou o kopii shimasu.", "Trước cuộc họp tôi sao chép tài liệu.", [("会議の前に", "trước cuộc họp", True), ("資料をコピーします。", "sao chép tài liệu", False)]),
        S("日本へ来る前に日本語を勉強しました。", "Nihon e kuru mae ni Nihongo o benkyou shimashita.", "Trước khi đến Nhật tôi đã học tiếng Nhật.", [("日本へ来る前に", "trước khi đến Nhật", True), ("日本語を勉強しました。", "đã học tiếng Nhật", False)]),
        S("国へ帰る前にお土産を買います。", "Kuni e kaeru mae ni omiyage o kaimasu.", "Trước khi về nước tôi mua quà.", [("国へ帰る前に", "trước khi về nước", True), ("お土産を買います。", "mua quà", False)]),
        S("三年前に日本語の勉強を始めました。", "Sannen mae ni Nihongo no benkyou o hajimemashita.", "Tôi đã bắt đầu học tiếng Nhật ba năm trước.", [("三年前に", "ba năm trước", True), ("日本語の勉強を始めました。", "đã bắt đầu học tiếng Nhật", False)]),
        S("ホテルを予約する前に課長に聞きます。", "Hoteru o yoyaku suru mae ni kachou ni kikimasu.", "Trước khi đặt khách sạn tôi hỏi trưởng phòng.", [("ホテルを予約する前に", "trước khi đặt khách sạn", True), ("課長に聞きます。", "hỏi trưởng phòng", False)]),
        S("古い切手を新しい切手に換えることができます。", "Furui kitte o atarashii kitte ni kaeru koto ga dekimasu.", "Có thể đổi tem cũ sang tem mới.", [("古い切手を", "tem cũ", False), ("新しい切手に換えることが", "việc đổi sang tem mới", False), ("できます。", "có thể", True)]),
        S("ここにごみを捨てることができません。", "Koko ni gomi o suteru koto ga dekimasen.", "Không thể vứt rác ở đây.", [("ここに", "ở đây", False), ("ごみを捨てることが", "việc vứt rác", False), ("できません。", "không thể", True)]),
        S("なかなか馬に乗ることができません。", "Nakanaka uma ni noru koto ga dekimasen.", "Tôi mãi vẫn chưa cưỡi ngựa được.", [("なかなか", "mãi vẫn chưa", True), ("馬に乗ることが", "việc cưỡi ngựa", False), ("できません。", "không thể", False)]),
        S("ぜひ牧場へ遊びに来てください。", "Zehi bokujou e asobi ni kite kudasai.", "Nhất định hãy đến trang trại chơi nhé.", [("ぜひ", "nhất định", True), ("牧場へ", "đến trang trại", False), ("遊びに来てください。", "hãy đến chơi", False)]),
        S("へえ、それはおもしろいですね。", "Hee, sore wa omoshiroi desu ne.", "Ồ, điều đó thú vị nhỉ.", [("へえ、", "ồ", False), ("それはおもしろいですね。", "điều đó thú vị nhỉ", True)]),
    ],
    19: [
        S("富士山に登ったことがあります。", "Fujisan ni nobotta koto ga arimasu.", "Tôi đã từng leo núi Phú Sĩ.", [("富士山に", "núi Phú Sĩ", False), ("登ったことがあります。", "đã từng leo", True)]),
        S("北海道へ行ったことがあります。", "Hokkaidou e itta koto ga arimasu.", "Tôi đã từng đi Hokkaido.", [("北海道へ", "đến Hokkaido", False), ("行ったことがあります。", "đã từng đi", True)]),
        S("日本の旅館に泊まったことがあります。", "Nihon no ryokan ni tomatta koto ga arimasu.", "Tôi đã từng ở nhà trọ kiểu Nhật.", [("日本の旅館に", "ở nhà trọ Nhật", False), ("泊まったことがあります。", "đã từng ở", True)]),
        S("馬に乗ったことがあります。", "Uma ni notta koto ga arimasu.", "Tôi đã từng cưỡi ngựa.", [("馬に", "ngựa", False), ("乗ったことがあります。", "đã từng cưỡi", True)]),
        S("歌舞伎を見たことがあります。", "Kabuki o mita koto ga arimasu.", "Tôi đã từng xem Kabuki.", [("歌舞伎を", "Kabuki", False), ("見たことがあります。", "đã từng xem", True)]),
        S("生け花をしたことがあります。", "Ikebana o shita koto ga arimasu.", "Tôi đã từng cắm hoa Ikebana.", [("生け花を", "cắm hoa Ikebana", False), ("したことがあります。", "đã từng làm", True)]),
        S("相撲を見たことがありません。", "Sumou o mita koto ga arimasen.", "Tôi chưa từng xem Sumo.", [("相撲を", "Sumo", False), ("見たことがありません。", "chưa từng xem", True)]),
        S("外国に住んだことがありません。", "Gaikoku ni sunda koto ga arimasen.", "Tôi chưa từng sống ở nước ngoài.", [("外国に", "ở nước ngoài", False), ("住んだことがありません。", "chưa từng sống", True)]),
        S("日曜日は掃除したり、洗濯したりします。", "Nichiyoubi wa souji shitari, sentaku shitari shimasu.", "Chủ nhật tôi dọn dẹp, giặt giũ, v.v.", [("日曜日は", "Chủ nhật thì", False), ("掃除したり、", "dọn dẹp", True), ("洗濯したりします。", "giặt giũ, v.v.", False)]),
        S("休みの日は本を読んだり、映画を見たりします。", "Yasumi no hi wa hon o yondari, eiga o mitari shimasu.", "Ngày nghỉ tôi đọc sách, xem phim, v.v.", [("休みの日は", "ngày nghỉ thì", False), ("本を読んだり、", "đọc sách", True), ("映画を見たりします。", "xem phim, v.v.", False)]),
        S("夏休みは泳いだり、山に登ったりしました。", "Natsuyasumi wa oyoidari, yama ni nobottari shimashita.", "Kỳ nghỉ hè tôi đã bơi, leo núi, v.v.", [("夏休みは", "kỳ nghỉ hè thì", False), ("泳いだり、", "bơi", True), ("山に登ったりしました。", "leo núi, v.v.", False)]),
        S("京都でお寺を見たり、写真を撮ったりしました。", "Kyouto de otera o mitari, shashin o tottari shimashita.", "Ở Kyoto tôi đã thăm chùa, chụp ảnh, v.v.", [("京都で", "ở Kyoto", False), ("お寺を見たり、", "thăm chùa", True), ("写真を撮ったりしました。", "chụp ảnh, v.v.", False)]),
        S("毎晩音楽を聞いたり、日記を書いたりします。", "Maiban ongaku o kiitari, nikki o kaitari shimasu.", "Mỗi tối tôi nghe nhạc, viết nhật ký, v.v.", [("毎晩", "mỗi tối", False), ("音楽を聞いたり、", "nghe nhạc", True), ("日記を書いたりします。", "viết nhật ký, v.v.", False)]),
        S("これからだんだん暑くなります。", "Korekara dandan atsuku narimasu.", "Từ giờ trời sẽ dần nóng lên.", [("これから", "từ giờ", False), ("だんだん", "dần dần", False), ("暑くなります。", "trở nên nóng", True)]),
        S("秋になると、涼しくなります。", "Aki ni naru to, suzushiku narimasu.", "Khi sang thu, trời trở nên mát.", [("秋になると、", "khi sang thu", False), ("涼しくなります。", "trở nên mát", True)]),
        S("日本語が上手になりました。", "Nihongo ga jouzu ni narimashita.", "Tiếng Nhật của tôi đã trở nên giỏi hơn.", [("日本語が", "tiếng Nhật", False), ("上手になりました。", "đã trở nên giỏi", True)]),
        S("部屋がきれいになりました。", "Heya ga kirei ni narimashita.", "Căn phòng đã trở nên sạch đẹp.", [("部屋が", "căn phòng", False), ("きれいになりました。", "đã trở nên sạch đẹp", True)]),
        S("息子は十八歳になりました。", "Musuko wa juuhassai ni narimashita.", "Con trai tôi đã tròn 18 tuổi.", [("息子は", "con trai tôi thì", False), ("十八歳になりました。", "đã tròn 18 tuổi", True)]),
        S("来年、父は六十歳になります。", "Rainen, chichi wa rokujussai ni narimasu.", "Năm sau bố tôi sẽ tròn 60 tuổi.", [("来年、", "năm sau", False), ("父は", "bố tôi thì", False), ("六十歳になります。", "sẽ tròn 60 tuổi", True)]),
        S("最近、日が長くなりました。", "Saikin, hi ga nagaku narimashita.", "Gần đây ngày đã dài hơn.", [("最近、", "gần đây", False), ("日が", "ngày", False), ("長くなりました。", "đã trở nên dài", True)]),
        S("体の調子がよくなりました。", "Karada no choushi ga yoku narimashita.", "Tình trạng sức khỏe đã tốt hơn.", [("体の調子が", "tình trạng sức khỏe", False), ("よくなりました。", "đã tốt hơn", True)]),
        S("一度すしを作ったことがあります。", "Ichido sushi o tsukutta koto ga arimasu.", "Tôi đã từng làm sushi một lần.", [("一度", "một lần", False), ("すしを作ったことがあります。", "đã từng làm sushi", True)]),
        S("ぜひ一度遊びに来てください。", "Zehi ichido asobi ni kite kudasai.", "Nhất định hãy đến chơi một lần nhé.", [("ぜひ一度", "nhất định một lần", True), ("遊びに来てください。", "hãy đến chơi", False)]),
        S("そうですね。わたしも行きたいです。", "Sou desu ne. Watashi mo ikitai desu.", "Đúng nhỉ. Tôi cũng muốn đi.", [("そうですね。", "đúng nhỉ", True), ("わたしも", "tôi cũng", False), ("行きたいです。", "muốn đi", False)]),
    ],
    20: [
        S("あした東京へ行く。", "Ashita Toukyou e iku.", "Ngày mai tôi đi Tokyo.", [("あした", "ngày mai", False), ("東京へ", "đến Tokyo", False), ("行く。", "đi", True)]),
        S("きょうはどこへも行かない。", "Kyou wa doko e mo ikanai.", "Hôm nay tôi không đi đâu cả.", [("きょうは", "hôm nay thì", False), ("どこへも", "không đâu cả", False), ("行かない。", "không đi", True)]),
        S("きのう映画を見た。", "Kinou eiga o mita.", "Hôm qua tôi đã xem phim.", [("きのう", "hôm qua", False), ("映画を", "phim", False), ("見た。", "đã xem", True)]),
        S("朝御飯を食べなかった。", "Asagohan o tabenakatta.", "Tôi đã không ăn sáng.", [("朝御飯を", "bữa sáng", False), ("食べなかった。", "đã không ăn", True)]),
        S("毎日忙しい。", "Mainichi isogashii.", "Mỗi ngày đều bận.", [("毎日", "mỗi ngày", False), ("忙しい。", "bận", True)]),
        S("この本はおもしろくない。", "Kono hon wa omoshirokunai.", "Quyển sách này không thú vị.", [("この本は", "quyển sách này thì", False), ("おもしろくない。", "không thú vị", True)]),
        S("きのうは寒かった。", "Kinou wa samukatta.", "Hôm qua trời lạnh.", [("きのうは", "hôm qua thì", False), ("寒かった。", "đã lạnh", True)]),
        S("試験は難しくなかった。", "Shiken wa muzukashikunakatta.", "Bài thi đã không khó.", [("試験は", "bài thi thì", False), ("難しくなかった。", "đã không khó", True)]),
        S("この町は静かだ。", "Kono machi wa shizuka da.", "Thành phố này yên tĩnh.", [("この町は", "thành phố này thì", False), ("静かだ。", "yên tĩnh", True)]),
        S("あの人は学生じゃない。", "Ano hito wa gakusei ja nai.", "Người kia không phải học sinh.", [("あの人は", "người kia thì", False), ("学生じゃない。", "không phải học sinh", True)]),
        S("きのうは休みだった。", "Kinou wa yasumi datta.", "Hôm qua là ngày nghỉ.", [("きのうは", "hôm qua thì", False), ("休みだった。", "đã là ngày nghỉ", True)]),
        S("パーティーはにぎやかじゃなかった。", "Paatii wa nigiyaka ja nakatta.", "Bữa tiệc đã không nhộn nhịp.", [("パーティーは", "bữa tiệc thì", False), ("にぎやかじゃなかった。", "đã không nhộn nhịp", True)]),
        S("夏休み、国へ帰る？", "Natsuyasumi, kuni e kaeru?", "Nghỉ hè cậu về nước à?", [("夏休み、", "kỳ nghỉ hè", False), ("国へ帰る？", "về nước à", True)]),
        S("うん、帰る。", "Un, kaeru.", "Ừ, mình về.", [("うん、", "ừ", False), ("帰る。", "về", True)]),
        S("パスポートが要る？", "Pasupooto ga iru?", "Có cần hộ chiếu không?", [("パスポートが", "hộ chiếu", False), ("要る？", "có cần không", True)]),
        S("ううん、要らない。", "Uun, iranai.", "Không, không cần.", [("ううん、", "không", False), ("要らない。", "không cần", True)]),
        S("日曜日、何をした？", "Nichiyoubi, nani o shita?", "Chủ nhật cậu đã làm gì?", [("日曜日、", "Chủ nhật", False), ("何をした？", "đã làm gì", True)]),
        S("友達とサッカーをした。", "Tomodachi to sakkaa o shita.", "Mình đã chơi bóng đá với bạn.", [("友達と", "với bạn", False), ("サッカーを", "bóng đá", False), ("した。", "đã chơi", True)]),
        S("コーヒー、飲む？", "Koohii, nomu?", "Uống cà phê không?", [("コーヒー、", "cà phê", False), ("飲む？", "uống không", True)]),
        S("うん、飲む。", "Un, nomu.", "Ừ, uống.", [("うん、", "ừ", False), ("飲む。", "uống", True)]),
        S("その自転車、どうしたの？", "Sono jitensha, dou shita no?", "Chiếc xe đạp đó làm sao vậy?", [("その自転車、", "chiếc xe đạp đó", False), ("どうしたの？", "làm sao vậy", True)]),
        S("友達がくれた。", "Tomodachi ga kureta.", "Bạn đã tặng mình.", [("友達が", "bạn", False), ("くれた。", "đã tặng mình", True)]),
        S("ちょっと言葉の意味を調べる。", "Chotto kotoba no imi o shiraberu.", "Mình tra nghĩa của từ một chút.", [("ちょっと", "một chút", False), ("言葉の意味を", "nghĩa của từ", False), ("調べる。", "tra cứu", True)]),
        S("壊れた自転車を直す。", "Kowareta jitensha o naosu.", "Mình sửa chiếc xe đạp bị hỏng.", [("壊れた自転車を", "xe đạp bị hỏng", False), ("直す。", "sửa", True)]),
    ],
}


LESSON_PASSAGES = {
    16: {"title": "ATMの使い方 — Cách sử dụng ATM", "content": [
        {"text":"まず、キャッシュカードを入れます。","furigana":"まず、キャッシュカードをいれます","meaning":"Trước tiên, cho thẻ ATM vào.","note":"まず nêu bước đầu tiên."},
        {"text":"次に、暗証番号を押します。","furigana":"つぎに、あんしょうばんごうをおします","meaning":"Tiếp theo, bấm mã PIN.","note":"Vて nối các bước theo trình tự."},
        {"text":"金額を押してから、確認ボタンを押します。","furigana":"きんがくをおしてから、かくにんボタンをおします","meaning":"Sau khi nhập số tiền, bấm nút xác nhận.","note":"Vてから nhấn mạnh hành động trước hoàn tất rồi mới làm hành động sau."},
        {"text":"カードとお金を取ります。","furigana":"カードとおかねをとります","meaning":"Lấy thẻ và tiền.","note":"と nối hai danh từ được lấy."},
        {"text":"このATMは新しくて、便利です。","furigana":"このエーティーエムはあたらしくて、べんりです","meaning":"Máy ATM này mới và tiện lợi.","note":"Aい bỏ い thêm くて để nối tính từ."},
        {"text":"画面も明るくて、大きいです。","furigana":"がめんもあかるくて、おおきいです","meaning":"Màn hình cũng sáng và lớn.","note":"も mang nghĩa cũng."},
        {"text":"操作が分からないとき、銀行員に聞きます。","furigana":"そうさがわからないとき、ぎんこういんにききます","meaning":"Khi không hiểu thao tác, tôi hỏi nhân viên ngân hàng.","note":"Câu chuẩn bị cho mẫu とき ở Bài 23."},
    ]},
    17: {"title": "病院で — Tại bệnh viện", "content": [
        {"text":"朝から頭が痛くて、熱があります。","furigana":"あさからあたまがいたくて、ねつがあります","meaning":"Từ sáng tôi đau đầu và bị sốt.","note":"Aくて nối hai trạng thái."},
        {"text":"医者は「二、三日休んでください」と言いました。","furigana":"いしゃは「に、さんにちやすんでください」といいました","meaning":"Bác sĩ bảo hãy nghỉ hai, ba ngày.","note":"Lời trích dẫn trực tiếp ôn mẫu hội thoại."},
        {"text":"薬を一日三回飲まなければなりません。","furigana":"くすりをいちにちさんかいのまなければなりません","meaning":"Tôi phải uống thuốc ba lần mỗi ngày.","note":"Vなければなりません diễn tả nghĩa vụ."},
        {"text":"今晩はお風呂に入らないでください。","furigana":"こんばんおふろにはいらないでください","meaning":"Tối nay xin đừng tắm bồn.","note":"Vないでください là yêu cầu không làm."},
        {"text":"会社へ行かなくてもいいです。","furigana":"かいしゃへいかなくてもいいです","meaning":"Không cần đến công ty.","note":"Vなくてもいいです nghĩa là không cần làm."},
        {"text":"金曜日までにもう一度病院へ来ます。","furigana":"きんようびまでにもういちどびょういんへきます","meaning":"Trước thứ Sáu tôi sẽ đến bệnh viện lần nữa.","note":"までに chỉ hạn chót."},
        {"text":"保険証を忘れないでください。","furigana":"ほけんしょうをわすれないでください","meaning":"Xin đừng quên thẻ bảo hiểm.","note":"忘れます có ない-form là 忘れない."},
    ]},
    18: {"title": "わたしの趣味 — Sở thích của tôi", "content": [
        {"text":"わたしの趣味は写真を撮ることです。","furigana":"わたしのしゅみはしゃしんをとることです","meaning":"Sở thích của tôi là chụp ảnh.","note":"Vること biến hành động thành danh từ."},
        {"text":"カメラを二台持っています。","furigana":"カメラをにだいもっています","meaning":"Tôi có hai chiếc máy ảnh.","note":"台 là lượng từ cho máy móc."},
        {"text":"きれいな写真を撮ることができます。","furigana":"きれいなしゃしんをとることができます","meaning":"Tôi có thể chụp ảnh đẹp.","note":"Vることができます diễn tả khả năng."},
        {"text":"休みの日は公園やお寺へ行きます。","furigana":"やすみのひはこうえんやおてらへいきます","meaning":"Ngày nghỉ tôi đi công viên, chùa, v.v.","note":"や liệt kê không đầy đủ."},
        {"text":"出かける前にカメラを準備します。","furigana":"でかけるまえにカメラをじゅんびします","meaning":"Trước khi ra ngoài tôi chuẩn bị máy ảnh.","note":"Vる前に diễn tả trước khi làm."},
        {"text":"毎晩寝る前に写真を見ます。","furigana":"まいばんねるまえにしゃしんをみます","meaning":"Mỗi tối trước khi ngủ tôi xem ảnh.","note":"Động từ trước 前に ở dạng từ điển."},
        {"text":"いつか外国でも写真を撮りたいです。","furigana":"いつかがいこくでもしゃしんをとりたいです","meaning":"Một ngày nào đó tôi cũng muốn chụp ảnh ở nước ngoài.","note":"いつか nghĩa là một lúc nào đó."},
    ]},
    19: {"title": "日本での経験 — Trải nghiệm tại Nhật", "content": [
        {"text":"わたしは日本に三年住んでいます。","furigana":"わたしはにほんにさんねんすんでいます","meaning":"Tôi đã sống ở Nhật ba năm.","note":"住んでいます diễn tả trạng thái cư trú."},
        {"text":"富士山に登ったことがあります。","furigana":"ふじさんにのぼったことがあります","meaning":"Tôi đã từng leo núi Phú Sĩ.","note":"Vたことがあります diễn tả trải nghiệm."},
        {"text":"京都で旅館に泊まったこともあります。","furigana":"きょうとでりょかんにとまったこともあります","meaning":"Tôi cũng từng ở nhà trọ Nhật tại Kyoto.","note":"も nhấn mạnh cũng có trải nghiệm."},
        {"text":"休みの日はお寺を見たり、写真を撮ったりします。","furigana":"やすみのひはおてらをみたり、しゃしんをとったりします","meaning":"Ngày nghỉ tôi thăm chùa, chụp ảnh, v.v.","note":"VたりVたりします liệt kê hành động tiêu biểu."},
        {"text":"日本語も少し上手になりました。","furigana":"にほんごもすこしじょうずになりました","meaning":"Tiếng Nhật của tôi cũng đã khá hơn một chút.","note":"Aな + に なります diễn tả thay đổi."},
        {"text":"最近、生活が楽しくなりました。","furigana":"さいきん、せいかつがたのしくなりました","meaning":"Gần đây cuộc sống trở nên vui hơn.","note":"Aい bỏ い thêm くなります."},
        {"text":"これからもいろいろな所へ行きたいです。","furigana":"これからもいろいろなところへいきたいです","meaning":"Từ nay tôi vẫn muốn đi nhiều nơi khác nhau.","note":"これからも nghĩa là từ nay về sau cũng."},
    ]},
    20: {"title": "友達との会話 — Trò chuyện với bạn", "content": [
        {"text":"日曜日、暇？","furigana":"にちようび、ひま","meaning":"Chủ nhật rảnh không?","note":"Hội thoại thân mật có thể lược ですか."},
        {"text":"うん、暇だよ。","furigana":"うん、ひまだよ","meaning":"Ừ, rảnh đấy.","note":"だ là thể thông thường của danh từ/tính từ な."},
        {"text":"いっしょに映画を見ない？","furigana":"いっしょにえいがをみない","meaning":"Cùng xem phim không?","note":"Vない？ có thể dùng như lời rủ thân mật."},
        {"text":"いいね。何を見る？","furigana":"いいね。なにをみる","meaning":"Hay đấy. Xem gì?","note":"見る là thể từ điển của 見ます."},
        {"text":"新しい日本の映画を見たい。","furigana":"あたらしいにほんのえいがをみたい","meaning":"Mình muốn xem phim Nhật mới.","note":"Trong thân mật, たいです bỏ です thành たい."},
        {"text":"切符はもう買った？","furigana":"きっぷはもうかった","meaning":"Đã mua vé chưa?","note":"買った là thể thông thường quá khứ."},
        {"text":"ううん、まだ買っていない。","furigana":"ううん、まだかっていない","meaning":"Chưa, vẫn chưa mua.","note":"Vていない là phủ định thông thường của Vています."},
    ]},
}
