"""Curated Minna no Nihongo learning content for lessons 21 through 25."""

from __future__ import annotations


def _sentence(japanese: str, romaji: str, vietnamese: str, chunks: list[tuple[str, str, bool]]) -> dict[str, object]:
    return {"full_japanese": japanese, "full_romaji": romaji, "full_vietnamese": vietnamese, "chunks": [(i, t, m, k) for i, (t, m, k) in enumerate(chunks, 1)]}


S = _sentence


LESSON_SENTENCES = {
    21: [
        S("あした雨が降ると思います。", "Ashita ame ga furu to omoimasu.", "Tôi nghĩ ngày mai trời sẽ mưa.", [("あした雨が降る", "ngày mai trời sẽ mưa", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("日本は物価が高いと思います。", "Nihon wa bukka ga takai to omoimasu.", "Tôi nghĩ vật giá ở Nhật cao.", [("日本は物価が高い", "vật giá ở Nhật cao", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("この仕事は大変だと思います。", "Kono shigoto wa taihen da to omoimasu.", "Tôi nghĩ công việc này vất vả.", [("この仕事は大変だ", "công việc này vất vả", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("ミラーさんは来ないと思います。", "Miraa-san wa konai to omoimasu.", "Tôi nghĩ anh Miller sẽ không đến.", [("ミラーさんは来ない", "anh Miller sẽ không đến", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("きのう田中さんは休んだと思います。", "Kinou Tanaka-san wa yasunda to omoimasu.", "Tôi nghĩ hôm qua anh Tanaka đã nghỉ.", [("きのう田中さんは休んだ", "hôm qua Tanaka đã nghỉ", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("あの映画はおもしろくなかったと思います。", "Ano eiga wa omoshirokunakatta to omoimasu.", "Tôi nghĩ bộ phim kia đã không thú vị.", [("あの映画はおもしろくなかった", "phim kia đã không thú vị", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("新しい空港は便利だと思います。", "Atarashii kuukou wa benri da to omoimasu.", "Tôi nghĩ sân bay mới tiện lợi.", [("新しい空港は便利だ", "sân bay mới tiện lợi", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("日本についてどう思いますか。", "Nihon ni tsuite dou omoimasu ka.", "Bạn nghĩ thế nào về Nhật Bản?", [("日本について", "về Nhật Bản", False), ("どう思いますか。", "nghĩ thế nào", True)]),
        S("日本は交通が便利だと思います。", "Nihon wa koutsuu ga benri da to omoimasu.", "Tôi nghĩ giao thông Nhật Bản tiện lợi.", [("日本は交通が便利だ", "giao thông Nhật tiện lợi", False), ("と思います。", "tôi nghĩ rằng", True)]),
        S("わたしもそう思います。", "Watashi mo sou omoimasu.", "Tôi cũng nghĩ vậy.", [("わたしも", "tôi cũng", False), ("そう思います。", "nghĩ như vậy", True)]),
        S("わたしはそう思いません。", "Watashi wa sou omoimasen.", "Tôi không nghĩ vậy.", [("わたしは", "tôi thì", False), ("そう思いません。", "không nghĩ vậy", True)]),
        S("先生はあした試験があると言いました。", "Sensei wa ashita shiken ga aru to iimashita.", "Giáo viên nói ngày mai có bài thi.", [("先生はあした試験がある", "giáo viên: ngày mai có bài thi", False), ("と言いました。", "đã nói rằng", True)]),
        S("田中さんは来月大阪へ行くと言いました。", "Tanaka-san wa raigetsu Oosaka e iku to iimashita.", "Anh Tanaka nói tháng sau sẽ đi Osaka.", [("田中さんは来月大阪へ行く", "Tanaka tháng sau đi Osaka", False), ("と言いました。", "đã nói rằng", True)]),
        S("母は「早く帰ってください」と言いました。", "Haha wa hayaku kaette kudasai to iimashita.", "Mẹ nói: Hãy về sớm.", [("母は「早く帰ってください」", "mẹ: hãy về sớm", False), ("と言いました。", "đã nói", True)]),
        S("山田さんは「会議に出ません」と言いました。", "Yamada-san wa kaigi ni demasen to iimashita.", "Anh Yamada nói: Tôi không dự họp.", [("山田さんは「会議に出ません」", "Yamada: không dự họp", False), ("と言いました。", "đã nói", True)]),
        S("寝る前に「お休みなさい」と言います。", "Neru mae ni oyasuminasai to iimasu.", "Trước khi ngủ, chúng ta nói chúc ngủ ngon.", [("寝る前に「お休みなさい」", "trước khi ngủ: chúc ngủ ngon", False), ("と言います。", "nói", True)]),
        S("日本の車は品質がいいでしょう。", "Nihon no kuruma wa hinshitsu ga ii deshou.", "Ô tô Nhật có chất lượng tốt phải không?", [("日本の車は品質がいい", "ô tô Nhật có chất lượng tốt", False), ("でしょう。", "đúng không nhỉ", True)]),
        S("北海道は寒かったでしょう。", "Hokkaidou wa samukatta deshou.", "Hokkaido đã lạnh lắm phải không?", [("北海道は寒かった", "Hokkaido đã lạnh", False), ("でしょう。", "phải không", True)]),
        S("このデザインはすてきでしょう。", "Kono dezain wa suteki deshou.", "Thiết kế này đẹp phải không?", [("このデザインはすてき", "thiết kế này đẹp", False), ("でしょう。", "phải không", True)]),
        S("山田さんは会議に出るでしょう。", "Yamada-san wa kaigi ni deru deshou.", "Anh Yamada sẽ dự họp phải không?", [("山田さんは会議に出る", "Yamada sẽ dự họp", False), ("でしょう。", "phải không", True)]),
        S("日本でいちばん人気があるスポーツは何ですか。", "Nihon de ichiban ninki ga aru supootsu wa nan desu ka.", "Môn thể thao phổ biến nhất ở Nhật là gì?", [("日本でいちばん人気があるスポーツは", "môn thể thao phổ biến nhất ở Nhật", True), ("何ですか。", "là gì", False)]),
        S("相撲だと思います。", "Sumou da to omoimasu.", "Tôi nghĩ là Sumo.", [("相撲だ", "là Sumo", False), ("と思います。", "tôi nghĩ", True)]),
        S("最近のニュースについて話しましょう。", "Saikin no nyuusu ni tsuite hanashimashou.", "Hãy nói về tin tức gần đây.", [("最近のニュースについて", "về tin tức gần đây", True), ("話しましょう。", "hãy nói chuyện", False)]),
        S("この意見は役に立つと思います。", "Kono iken wa yaku ni tatsu to omoimasu.", "Tôi nghĩ ý kiến này hữu ích.", [("この意見は役に立つ", "ý kiến này hữu ích", False), ("と思います。", "tôi nghĩ rằng", True)]),
    ],
    22: [
        S("これはミラーさんが作ったケーキです。", "Kore wa Miraa-san ga tsukutta keeki desu.", "Đây là chiếc bánh anh Miller đã làm.", [("これは", "đây thì", False), ("ミラーさんが作ったケーキです。", "là bánh Miller đã làm", True)]),
        S("これは京都で撮った写真です。", "Kore wa Kyouto de totta shashin desu.", "Đây là bức ảnh được chụp ở Kyoto.", [("これは", "đây thì", False), ("京都で撮った写真です。", "là ảnh chụp ở Kyoto", True)]),
        S("あそこに立っている人はだれですか。", "Asoko ni tatte iru hito wa dare desu ka.", "Người đang đứng ở đằng kia là ai?", [("あそこに立っている人は", "người đang đứng ở kia", True), ("だれですか。", "là ai", False)]),
        S("新聞を読んでいる人は父です。", "Shinbun o yonde iru hito wa chichi desu.", "Người đang đọc báo là bố tôi.", [("新聞を読んでいる人は", "người đang đọc báo", True), ("父です。", "là bố tôi", False)]),
        S("あの眼鏡をかけている人は山田さんです。", "Ano megane o kakete iru hito wa Yamada-san desu.", "Người đeo kính kia là anh Yamada.", [("あの眼鏡をかけている人は", "người đang đeo kính kia", True), ("山田さんです。", "là anh Yamada", False)]),
        S("わたしがいつも買い物する店は駅の前です。", "Watashi ga itsumo kaimono suru mise wa eki no mae desu.", "Cửa hàng tôi thường mua sắm ở trước ga.", [("わたしがいつも買い物する店は", "cửa hàng tôi thường mua sắm", True), ("駅の前です。", "ở trước ga", False)]),
        S("母が作る料理はおいしいです。", "Haha ga tsukuru ryouri wa oishii desu.", "Món mẹ tôi nấu rất ngon.", [("母が作る料理は", "món mẹ nấu", True), ("おいしいです。", "ngon", False)]),
        S("昨日買った靴を履きます。", "Kinou katta kutsu o hakimasu.", "Tôi đi đôi giày đã mua hôm qua.", [("昨日買った靴を", "đôi giày mua hôm qua", True), ("履きます。", "đi/mang", False)]),
        S("友達にもらった時計をなくしました。", "Tomodachi ni moratta tokei o nakushimashita.", "Tôi đã làm mất chiếc đồng hồ nhận từ bạn.", [("友達にもらった時計を", "đồng hồ nhận từ bạn", True), ("なくしました。", "đã làm mất", False)]),
        S("日本で買ったかばんを使っています。", "Nihon de katta kaban o tsukatte imasu.", "Tôi đang dùng chiếc cặp đã mua ở Nhật.", [("日本で買ったかばんを", "chiếc cặp mua ở Nhật", True), ("使っています。", "đang dùng", False)]),
        S("わたしが住んでいる町は静かです。", "Watashi ga sunde iru machi wa shizuka desu.", "Thành phố tôi đang sống yên tĩnh.", [("わたしが住んでいる町は", "thành phố tôi đang sống", True), ("静かです。", "yên tĩnh", False)]),
        S("ミラーさんが働いている会社はIMCです。", "Miraa-san ga hataraite iru kaisha wa IMC desu.", "Công ty anh Miller làm việc là IMC.", [("ミラーさんが働いている会社は", "công ty Miller làm việc", True), ("IMCです。", "là IMC", False)]),
        S("駅の近くにある喫茶店で会いましょう。", "Eki no chikaku ni aru kissaten de aimashou.", "Chúng ta gặp ở quán cà phê gần ga nhé.", [("駅の近くにある喫茶店で", "tại quán cà phê gần ga", True), ("会いましょう。", "hãy gặp nhau", False)]),
        S("庭があるうちが欲しいです。", "Niwa ga aru uchi ga hoshii desu.", "Tôi muốn một căn nhà có sân vườn.", [("庭があるうちが", "căn nhà có sân vườn", True), ("欲しいです。", "muốn có", False)]),
        S("料理を作る台所が広いうちを探しています。", "Ryouri o tsukuru daidokoro ga hiroi uchi o sagashite imasu.", "Tôi đang tìm căn nhà có bếp nấu ăn rộng.", [("料理を作る台所が広いうちを", "căn nhà có bếp nấu ăn rộng", True), ("探しています。", "đang tìm", False)]),
        S("家族が住む部屋が三つ要ります。", "Kazoku ga sumu heya ga mittsu irimasu.", "Tôi cần ba phòng cho gia đình ở.", [("家族が住む部屋が", "phòng gia đình sẽ ở", True), ("三つ要ります。", "cần ba phòng", False)]),
        S("日曜日にする仕事があります。", "Nichiyoubi ni suru shigoto ga arimasu.", "Tôi có việc phải làm vào Chủ nhật.", [("日曜日にする仕事が", "việc làm vào Chủ nhật", True), ("あります。", "có", False)]),
        S("銀行へ行く時間がありません。", "Ginkou e iku jikan ga arimasen.", "Tôi không có thời gian đi ngân hàng.", [("銀行へ行く時間が", "thời gian đi ngân hàng", True), ("ありません。", "không có", False)]),
        S("友達と映画を見る約束があります。", "Tomodachi to eiga o miru yakusoku ga arimasu.", "Tôi có hẹn xem phim với bạn.", [("友達と映画を見る約束が", "cuộc hẹn xem phim với bạn", True), ("あります。", "có", False)]),
        S("旅行で着る服を買いました。", "Ryokou de kiru fuku o kaimashita.", "Tôi đã mua quần áo để mặc khi du lịch.", [("旅行で着る服を", "quần áo mặc khi du lịch", True), ("買いました。", "đã mua", False)]),
        S("パーティーで履く靴を選びます。", "Paatii de haku kutsu o erabimasu.", "Tôi chọn giày để đi trong bữa tiệc.", [("パーティーで履く靴を", "giày đi trong bữa tiệc", True), ("選びます。", "chọn", False)]),
        S("頭がよくて、親切な人と結婚したいです。", "Atama ga yokute, shinsetsu na hito to kekkon shitai desu.", "Tôi muốn kết hôn với người thông minh và tốt bụng.", [("頭がよくて、親切な人と", "với người thông minh, tốt bụng", True), ("結婚したいです。", "muốn kết hôn", False)]),
        S("赤いネクタイをしている人を知っていますか。", "Akai nekutai o shite iru hito o shitte imasu ka.", "Bạn có biết người đang đeo cà vạt đỏ không?", [("赤いネクタイをしている人を", "người đeo cà vạt đỏ", True), ("知っていますか。", "có biết không", False)]),
        S("どんな部屋をお探しですか。", "Donna heya o osagashi desu ka.", "Bạn đang tìm căn phòng như thế nào?", [("どんな部屋を", "căn phòng thế nào", False), ("お探しですか。", "đang tìm", True)]),
    ],
    23: [
        S("図書館で本を借りるとき、カードが要ります。", "Toshokan de hon o kariru toki, kaado ga irimasu.", "Khi mượn sách ở thư viện, cần có thẻ.", [("図書館で本を借りるとき、", "khi mượn sách ở thư viện", True), ("カードが要ります。", "cần thẻ", False)]),
        S("使い方が分からないとき、先生に聞きます。", "Tsukaikata ga wakaranai toki, sensei ni kikimasu.", "Khi không hiểu cách dùng, tôi hỏi giáo viên.", [("使い方が分からないとき、", "khi không hiểu cách dùng", True), ("先生に聞きます。", "hỏi giáo viên", False)]),
        S("暇なとき、音楽を聞きます。", "Hima na toki, ongaku o kikimasu.", "Khi rảnh tôi nghe nhạc.", [("暇なとき、", "khi rảnh", True), ("音楽を聞きます。", "nghe nhạc", False)]),
        S("子どものとき、よく川で泳ぎました。", "Kodomo no toki, yoku kawa de oyogimashita.", "Khi còn nhỏ tôi thường bơi ở sông.", [("子どものとき、", "khi còn nhỏ", True), ("よく川で泳ぎました。", "thường bơi ở sông", False)]),
        S("若いとき、外国を旅行しました。", "Wakai toki, gaikoku o ryokou shimashita.", "Khi còn trẻ tôi đã du lịch nước ngoài.", [("若いとき、", "khi còn trẻ", True), ("外国を旅行しました。", "đã du lịch nước ngoài", False)]),
        S("日本へ来るとき、空港で写真を撮りました。", "Nihon e kuru toki, kuukou de shashin o torimashita.", "Khi đến Nhật, tôi đã chụp ảnh ở sân bay.", [("日本へ来るとき、", "khi đang đến Nhật", True), ("空港で写真を撮りました。", "đã chụp ảnh ở sân bay", False)]),
        S("日本へ来たとき、空港で友達に会いました。", "Nihon e kita toki, kuukou de tomodachi ni aimashita.", "Khi đã đến Nhật, tôi gặp bạn ở sân bay.", [("日本へ来たとき、", "khi đã đến Nhật", True), ("空港で友達に会いました。", "đã gặp bạn ở sân bay", False)]),
        S("道を渡るとき、車に気をつけます。", "Michi o wataru toki, kuruma ni ki o tsukemasu.", "Khi qua đường tôi chú ý ô tô.", [("道を渡るとき、", "khi qua đường", True), ("車に気をつけます。", "chú ý ô tô", False)]),
        S("うちを出るとき、電気を消します。", "Uchi o deru toki, denki o keshimasu.", "Khi ra khỏi nhà tôi tắt điện.", [("うちを出るとき、", "khi ra khỏi nhà", True), ("電気を消します。", "tắt điện", False)]),
        S("疲れたとき、熱いお風呂に入ります。", "Tsukareta toki, atsui ofuro ni hairimasu.", "Khi mệt tôi tắm bồn nước nóng.", [("疲れたとき、", "khi mệt", True), ("熱いお風呂に入ります。", "tắm bồn nước nóng", False)]),
        S("このボタンを押すと、ジュースが出ます。", "Kono botan o osu to, juusu ga demasu.", "Khi bấm nút này, nước trái cây chảy ra.", [("このボタンを押すと、", "khi bấm nút này", True), ("ジュースが出ます。", "nước trái cây chảy ra", False)]),
        S("このつまみを右へ回すと、音が大きくなります。", "Kono tsumami o migi e mawasu to, oto ga ookiku narimasu.", "Khi xoay núm này sang phải, âm thanh lớn hơn.", [("このつまみを右へ回すと、", "khi xoay núm sang phải", True), ("音が大きくなります。", "âm thanh lớn hơn", False)]),
        S("春になると、桜が咲きます。", "Haru ni naru to, sakura ga sakimasu.", "Khi sang xuân, hoa anh đào nở.", [("春になると、", "khi sang xuân", True), ("桜が咲きます。", "hoa anh đào nở", False)]),
        S("雨が降ると、道が暗くなります。", "Ame ga furu to, michi ga kuraku narimasu.", "Khi trời mưa, đường trở nên tối.", [("雨が降ると、", "khi trời mưa", True), ("道が暗くなります。", "đường trở nên tối", False)]),
        S("ここに触ると、機械が止まります。", "Koko ni sawaru to, kikai ga tomarimasu.", "Nếu chạm vào đây, máy sẽ dừng.", [("ここに触ると、", "nếu chạm vào đây", True), ("機械が止まります。", "máy dừng", False)]),
        S("このレバーを引くと、ドアが開きます。", "Kono rebaa o hiku to, doa ga akimasu.", "Khi kéo cần này, cửa mở.", [("このレバーを引くと、", "khi kéo cần này", True), ("ドアが開きます。", "cửa mở", False)]),
        S("信号が青になると、道を渡ります。", "Shingou ga ao ni naru to, michi o watarimasu.", "Khi đèn chuyển xanh, tôi qua đường.", [("信号が青になると、", "khi đèn chuyển xanh", True), ("道を渡ります。", "qua đường", False)]),
        S("どうすると、お釣りが出ますか。", "Dou suru to, otsuri ga demasu ka.", "Làm thế nào thì tiền thừa chảy ra?", [("どうすると、", "làm thế nào thì", True), ("お釣りが出ますか。", "tiền thừa chảy ra", False)]),
        S("駅へ行くとき、この橋を渡ります。", "Eki e iku toki, kono hashi o watarimasu.", "Khi đi tới ga, tôi qua cây cầu này.", [("駅へ行くとき、", "khi đi đến ga", True), ("この橋を渡ります。", "qua cầu này", False)]),
        S("二つ目の角を右へ曲がってください。", "Futatsume no kado o migi e magatte kudasai.", "Hãy rẽ phải ở góc thứ hai.", [("二つ目の角を", "ở góc thứ hai", True), ("右へ曲がってください。", "hãy rẽ phải", False)]),
        S("交差点を渡ると、左に駐車場があります。", "Kousaten o wataru to, hidari ni chuushajou ga arimasu.", "Qua ngã tư thì có bãi đỗ xe bên trái.", [("交差点を渡ると、", "khi qua ngã tư", True), ("左に駐車場があります。", "có bãi đỗ xe bên trái", False)]),
        S("機械が故障したとき、電気屋を呼びます。", "Kikai ga koshou shita toki, denkiya o yobimasu.", "Khi máy bị hỏng, tôi gọi thợ điện.", [("機械が故障したとき、", "khi máy bị hỏng", True), ("電気屋を呼びます。", "gọi thợ điện", False)]),
        S("引っ越しするとき、住所を変えます。", "Hikkoshi suru toki, juusho o kaemasu.", "Khi chuyển nhà, tôi đổi địa chỉ.", [("引っ越しするとき、", "khi chuyển nhà", True), ("住所を変えます。", "đổi địa chỉ", False)]),
        S("道が分からないとき、近くの人に聞きます。", "Michi ga wakaranai toki, chikaku no hito ni kikimasu.", "Khi không biết đường, tôi hỏi người gần đó.", [("道が分からないとき、", "khi không biết đường", True), ("近くの人に聞きます。", "hỏi người gần đó", False)]),
    ],
    24: [
        S("佐藤さんがわたしに花をくれました。", "Satou-san ga watashi ni hana o kuremashita.", "Chị Sato đã tặng hoa cho tôi.", [("佐藤さんがわたしに", "chị Sato cho tôi", False), ("花をくれました。", "đã tặng hoa", True)]),
        S("友達が誕生日に時計をくれました。", "Tomodachi ga tanjoubi ni tokei o kuremashita.", "Bạn đã tặng tôi đồng hồ vào sinh nhật.", [("友達が誕生日に", "bạn vào sinh nhật", False), ("時計をくれました。", "đã tặng tôi đồng hồ", True)]),
        S("母がセーターを送ってくれました。", "Haha ga seetaa o okutte kuremashita.", "Mẹ đã gửi áo len cho tôi.", [("母が", "mẹ", False), ("セーターを送ってくれました。", "đã gửi áo len cho tôi", True)]),
        S("山田さんが駅まで送ってくれました。", "Yamada-san ga eki made okutte kuremashita.", "Anh Yamada đã đưa tôi đến ga.", [("山田さんが", "anh Yamada", False), ("駅まで送ってくれました。", "đã đưa tôi đến ga", True)]),
        S("先生が漢字の読み方を教えてくれました。", "Sensei ga kanji no yomikata o oshiete kuremashita.", "Giáo viên đã dạy tôi cách đọc Kanji.", [("先生が", "giáo viên", False), ("漢字の読み方を教えてくれました。", "đã dạy tôi cách đọc Kanji", True)]),
        S("友達が引っ越しを手伝ってくれました。", "Tomodachi ga hikkoshi o tetsudatte kuremashita.", "Bạn đã giúp tôi chuyển nhà.", [("友達が", "bạn", False), ("引っ越しを手伝ってくれました。", "đã giúp tôi chuyển nhà", True)]),
        S("祖母が弁当を作ってくれました。", "Sobo ga bentou o tsukutte kuremashita.", "Bà đã làm cơm hộp cho tôi.", [("祖母が", "bà", False), ("弁当を作ってくれました。", "đã làm cơm hộp cho tôi", True)]),
        S("ミラーさんが東京を案内してくれました。", "Miraa-san ga Toukyou o annai shite kuremashita.", "Anh Miller đã dẫn tôi tham quan Tokyo.", [("ミラーさんが", "anh Miller", False), ("東京を案内してくれました。", "đã dẫn tôi tham quan Tokyo", True)]),
        S("わたしは妹に本を読んであげました。", "Watashi wa imouto ni hon o yonde agemashita.", "Tôi đã đọc sách cho em gái.", [("わたしは妹に", "tôi cho em gái", False), ("本を読んであげました。", "đã đọc sách giúp", True)]),
        S("おじいさんに道を教えてあげました。", "Ojiisan ni michi o oshiete agemashita.", "Tôi đã chỉ đường cho một ông cụ.", [("おじいさんに", "cho ông cụ", False), ("道を教えてあげました。", "đã chỉ đường giúp", True)]),
        S("友達に写真を送ってあげます。", "Tomodachi ni shashin o okutte agemasu.", "Tôi sẽ gửi ảnh cho bạn.", [("友達に", "cho bạn", False), ("写真を送ってあげます。", "sẽ gửi ảnh giúp", True)]),
        S("子どもを動物園へ連れて行ってあげました。", "Kodomo o doubutsuen e tsurete itte agemashita.", "Tôi đã đưa đứa trẻ đi sở thú.", [("子どもを", "đứa trẻ", False), ("動物園へ連れて行ってあげました。", "đã đưa đi sở thú", True)]),
        S("祖父に手紙を書いてあげました。", "Sofu ni tegami o kaite agemashita.", "Tôi đã viết thư giúp ông.", [("祖父に", "cho ông", False), ("手紙を書いてあげました。", "đã viết thư giúp", True)]),
        S("わたしは先生に作文を直してもらいました。", "Watashi wa sensei ni sakubun o naoshite moraimashita.", "Tôi đã nhờ giáo viên sửa bài văn.", [("わたしは先生に", "tôi nhờ giáo viên", False), ("作文を直してもらいました。", "đã được sửa bài văn", True)]),
        S("友達に旅行の写真を見せてもらいました。", "Tomodachi ni ryokou no shashin o misete moraimashita.", "Tôi đã được bạn cho xem ảnh du lịch.", [("友達に", "từ bạn", False), ("旅行の写真を見せてもらいました。", "đã được cho xem ảnh", True)]),
        S("兄に車で送ってもらいました。", "Ani ni kuruma de okutte moraimashita.", "Tôi đã được anh trai chở bằng ô tô.", [("兄に", "nhờ anh trai", False), ("車で送ってもらいました。", "đã được chở bằng ô tô", True)]),
        S("田中さんに仕事を手伝ってもらいました。", "Tanaka-san ni shigoto o tetsudatte moraimashita.", "Tôi đã nhờ anh Tanaka giúp công việc.", [("田中さんに", "nhờ anh Tanaka", False), ("仕事を手伝ってもらいました。", "đã được giúp công việc", True)]),
        S("駅員に道を説明してもらいました。", "Ekiin ni michi o setsumei shite moraimashita.", "Tôi đã được nhân viên nhà ga giải thích đường đi.", [("駅員に", "nhờ nhân viên ga", False), ("道を説明してもらいました。", "đã được giải thích đường", True)]),
        S("だれがこのお菓子をくれましたか。", "Dare ga kono okashi o kuremashita ka.", "Ai đã tặng bạn bánh kẹo này?", [("だれが", "ai", False), ("このお菓子をくれましたか。", "đã tặng bánh này", True)]),
        S("引っ越しを手伝ってくれませんか。", "Hikkoshi o tetsudatte kuremasen ka.", "Bạn giúp tôi chuyển nhà được không?", [("引っ越しを", "việc chuyển nhà", False), ("手伝ってくれませんか。", "giúp tôi được không", True)]),
        S("駅まで迎えに来てくれませんか。", "Eki made mukae ni kite kuremasen ka.", "Bạn đến ga đón tôi được không?", [("駅まで", "đến ga", False), ("迎えに来てくれませんか。", "đến đón tôi được không", True)]),
        S("この言葉の意味を説明してくれませんか。", "Kono kotoba no imi o setsumei shite kuremasen ka.", "Bạn giải thích nghĩa từ này giúp tôi được không?", [("この言葉の意味を", "nghĩa của từ này", False), ("説明してくれませんか。", "giải thích giúp được không", True)]),
        S("全部自分で準備しました。", "Zenbu jibun de junbi shimashita.", "Tôi đã tự chuẩn bị tất cả.", [("全部", "tất cả", False), ("自分で準備しました。", "đã tự chuẩn bị", True)]),
        S("ほかに何か手伝いましょうか。", "Hoka ni nanika tetsudaimashou ka.", "Tôi giúp thêm gì khác nhé?", [("ほかに何か", "gì khác nữa", False), ("手伝いましょうか。", "tôi giúp nhé", True)]),
    ],
    25: [
        S("雨が降ったら、出かけません。", "Ame ga futtara, dekakemasen.", "Nếu trời mưa, tôi sẽ không ra ngoài.", [("雨が降ったら、", "nếu trời mưa", True), ("出かけません。", "không ra ngoài", False)]),
        S("天気がよかったら、公園へ行きます。", "Tenki ga yokattara, kouen e ikimasu.", "Nếu thời tiết đẹp, tôi sẽ đi công viên.", [("天気がよかったら、", "nếu thời tiết đẹp", True), ("公園へ行きます。", "đi công viên", False)]),
        S("暇だったら、遊びに来てください。", "Hima dattara, asobi ni kite kudasai.", "Nếu rảnh, hãy đến chơi nhé.", [("暇だったら、", "nếu rảnh", True), ("遊びに来てください。", "hãy đến chơi", False)]),
        S("安かったら、このパソコンを買います。", "Yasukattara, kono pasokon o kaimasu.", "Nếu rẻ, tôi sẽ mua máy tính này.", [("安かったら、", "nếu rẻ", True), ("このパソコンを買います。", "mua máy tính này", False)]),
        S("もし百万円あったら、何をしたいですか。", "Moshi hyakuman en attara, nani o shitai desu ka.", "Nếu có một triệu yên, bạn muốn làm gì?", [("もし百万円あったら、", "nếu có một triệu yên", True), ("何をしたいですか。", "muốn làm gì", False)]),
        S("外国を旅行したいです。", "Gaikoku o ryokou shitai desu.", "Tôi muốn du lịch nước ngoài.", [("外国を", "nước ngoài", False), ("旅行したいです。", "muốn du lịch", True)]),
        S("仕事が終わったら、飲みに行きましょう。", "Shigoto ga owattara, nomi ni ikimashou.", "Khi công việc xong, chúng ta đi uống nhé.", [("仕事が終わったら、", "khi công việc xong", True), ("飲みに行きましょう。", "hãy đi uống", False)]),
        S("駅に着いたら、電話してください。", "Eki ni tsuitara, denwa shite kudasai.", "Khi đến ga, hãy gọi điện cho tôi.", [("駅に着いたら、", "khi đến ga", True), ("電話してください。", "hãy gọi điện", False)]),
        S("うちへ帰ったら、すぐ宿題をします。", "Uchi e kaettara, sugu shukudai o shimasu.", "Khi về nhà, tôi sẽ làm bài tập ngay.", [("うちへ帰ったら、", "khi về nhà", True), ("すぐ宿題をします。", "làm bài tập ngay", False)]),
        S("二十歳になったら、車を買いたいです。", "Hatachi ni nattara, kuruma o kaitai desu.", "Khi 20 tuổi, tôi muốn mua ô tô.", [("二十歳になったら、", "khi tròn 20 tuổi", True), ("車を買いたいです。", "muốn mua ô tô", False)]),
        S("日本へ行ったら、富士山に登りたいです。", "Nihon e ittara, Fujisan ni noboritai desu.", "Khi đi Nhật, tôi muốn leo núi Phú Sĩ.", [("日本へ行ったら、", "khi đi Nhật", True), ("富士山に登りたいです。", "muốn leo Phú Sĩ", False)]),
        S("会議が終わったら、資料を片づけてください。", "Kaigi ga owattara, shiryou o katazukete kudasai.", "Khi cuộc họp kết thúc, hãy dọn tài liệu.", [("会議が終わったら、", "khi cuộc họp kết thúc", True), ("資料を片づけてください。", "hãy dọn tài liệu", False)]),
        S("雨が降っても、会社へ行きます。", "Ame ga futte mo, kaisha e ikimasu.", "Dù trời mưa, tôi vẫn đi làm.", [("雨が降っても、", "dù trời mưa", True), ("会社へ行きます。", "đi công ty", False)]),
        S("高くても、この時計を買いたいです。", "Takakute mo, kono tokei o kaitai desu.", "Dù đắt, tôi vẫn muốn mua đồng hồ này.", [("高くても、", "dù đắt", True), ("この時計を買いたいです。", "muốn mua đồng hồ này", False)]),
        S("難しくても、日本語の勉強を続けます。", "Muzukashikute mo, Nihongo no benkyou o tsuzukemasu.", "Dù khó, tôi vẫn tiếp tục học tiếng Nhật.", [("難しくても、", "dù khó", True), ("日本語の勉強を続けます。", "tiếp tục học tiếng Nhật", False)]),
        S("静かでも、あの町には住みたくないです。", "Shizuka demo, ano machi ni wa sumitakunai desu.", "Dù yên tĩnh, tôi không muốn sống ở thành phố kia.", [("静かでも、", "dù yên tĩnh", True), ("あの町には住みたくないです。", "không muốn sống ở thành phố kia", False)]),
        S("日曜日でも、父は働きます。", "Nichiyoubi demo, chichi wa hatarakimasu.", "Dù là Chủ nhật, bố tôi vẫn làm việc.", [("日曜日でも、", "dù là Chủ nhật", True), ("父は働きます。", "bố vẫn làm việc", False)]),
        S("いくら呼んでも、返事がありません。", "Ikura yonde mo, henji ga arimasen.", "Dù gọi bao nhiêu lần cũng không có trả lời.", [("いくら呼んでも、", "dù gọi bao nhiêu", True), ("返事がありません。", "không có trả lời", False)]),
        S("いくら考えても、答えが分かりません。", "Ikura kangaete mo, kotae ga wakarimasen.", "Dù suy nghĩ bao nhiêu tôi vẫn không biết đáp án.", [("いくら考えても、", "dù suy nghĩ bao nhiêu", True), ("答えが分かりません。", "không hiểu đáp án", False)]),
        S("もし仕事が見つかったら、日本で働きたいです。", "Moshi shigoto ga mitsukattara, Nihon de hatarakitai desu.", "Nếu tìm được việc, tôi muốn làm việc ở Nhật.", [("もし仕事が見つかったら、", "nếu tìm được việc", True), ("日本で働きたいです。", "muốn làm việc ở Nhật", False)]),
        S("友達が来なかったら、一人で行きます。", "Tomodachi ga konakattara, hitori de ikimasu.", "Nếu bạn không đến, tôi sẽ đi một mình.", [("友達が来なかったら、", "nếu bạn không đến", True), ("一人で行きます。", "đi một mình", False)]),
        S("体の調子が悪かったら、休んでください。", "Karada no choushi ga warukattara, yasunde kudasai.", "Nếu sức khỏe không tốt, hãy nghỉ ngơi.", [("体の調子が悪かったら、", "nếu sức khỏe không tốt", True), ("休んでください。", "hãy nghỉ", False)]),
        S("転勤しても、また会いましょう。", "Tenkin shite mo, mata aimashou.", "Dù chuyển công tác, chúng ta lại gặp nhau nhé.", [("転勤しても、", "dù chuyển công tác", True), ("また会いましょう。", "hãy gặp lại", False)]),
        S("いろいろお世話になりました。", "Iroiro osewa ni narimashita.", "Cảm ơn bạn đã giúp đỡ tôi nhiều.", [("いろいろ", "nhiều mặt", False), ("お世話になりました。", "đã được giúp đỡ", True)]),
    ],
}


LESSON_PASSAGES = {
    21: {"title":"日本についてどう思いますか — Bạn nghĩ gì về Nhật Bản?","content":[
        {"text":"日本は交通が便利だと思います。","furigana":"にほんはこうつうがべんりだとおもいます","meaning":"Tôi nghĩ giao thông Nhật Bản tiện lợi.","note":"Thể thông thường + と思います nêu ý kiến."},
        {"text":"電車は時間どおりに来ると思います。","furigana":"でんしゃはじかんどおりにくるとおもいます","meaning":"Tôi nghĩ tàu đến đúng giờ.","note":"Động từ trước と ở thể thông thường."},
        {"text":"でも、物価は少し高いと思います。","furigana":"でも、ぶっかはすこしたかいとおもいます","meaning":"Nhưng tôi nghĩ vật giá hơi cao.","note":"Tính từ い bỏ です trước と."},
        {"text":"友達もそう思うと言いました。","furigana":"ともだちもそうおもうといいました","meaning":"Bạn tôi cũng nói rằng nghĩ như vậy.","note":"〜と言いました thuật lại lời nói."},
        {"text":"日本の食べ物はおいしいでしょう。","furigana":"にほんのたべものはおいしいでしょう","meaning":"Đồ ăn Nhật ngon phải không?","note":"でしょう dùng để tìm sự đồng tình."},
        {"text":"特にすしが人気があると思います。","furigana":"とくにすしがにんきがあるとおもいます","meaning":"Tôi nghĩ đặc biệt sushi rất phổ biến.","note":"人気があります nghĩa là được ưa chuộng."},
        {"text":"日本の文化についてもっと勉強したいです。","furigana":"にほんのぶんかについてもっとべんきょうしたいです","meaning":"Tôi muốn học thêm về văn hóa Nhật.","note":"Nについて nghĩa là về chủ đề N."},
    ]},
    22: {"title":"新しい部屋 — Căn phòng mới","content":[
        {"text":"わたしは駅の近くにある部屋を探しています。","furigana":"わたしはえきのちかくにあるへやをさがしています","meaning":"Tôi đang tìm căn phòng ở gần ga.","note":"Mệnh đề thể thông thường đứng trước danh từ 部屋."},
        {"text":"料理を作る台所が広い部屋が欲しいです。","furigana":"りょうりをつくるだいどころがひろいへやがほしいです","meaning":"Tôi muốn căn phòng có bếp nấu ăn rộng.","note":"Cụm bổ nghĩa có thể chứa chủ ngữ với が."},
        {"text":"昨日見た部屋は明るくて、きれいでした。","furigana":"きのうみたへやはあかるくて、きれいでした","meaning":"Căn phòng xem hôm qua sáng và sạch đẹp.","note":"昨日見た bổ nghĩa cho 部屋."},
        {"text":"でも、家族が住む部屋が二つしかありません。","furigana":"でも、かぞくがすむへやがふたつしかありません","meaning":"Nhưng chỉ có hai phòng cho gia đình ở.","note":"家族が住む là mệnh đề bổ nghĩa."},
        {"text":"庭があるうちも見ました。","furigana":"にわがあるうちもみました","meaning":"Tôi cũng đã xem một căn nhà có sân.","note":"庭がある bổ nghĩa cho うち."},
        {"text":"そのうちは駅から少し遠いです。","furigana":"そのうちはえきからすこしとおいです","meaning":"Căn nhà đó hơi xa ga.","note":"その thay cho thông tin đã nêu."},
        {"text":"来週もう一度見る約束があります。","furigana":"らいしゅうもういちどみるやくそくがあります","meaning":"Tuần sau tôi có hẹn xem lại một lần nữa.","note":"見る bổ nghĩa cho 約束."},
    ]},
    23: {"title":"駅までの道 — Đường đến nhà ga","content":[
        {"text":"うちを出るとき、右へ曲がります。","furigana":"うちをでるとき、みぎへまがります","meaning":"Khi ra khỏi nhà, tôi rẽ phải.","note":"Vるとき: tại thời điểm trước hoặc đang làm V."},
        {"text":"大きい道に出たとき、左にコンビニがあります。","furigana":"おおきいみちにでたとき、ひだりにコンビニがあります","meaning":"Khi ra đến đường lớn, bên trái có cửa hàng tiện lợi.","note":"Vたとき: hành động đã hoàn tất."},
        {"text":"一つ目の交差点を渡ります。","furigana":"ひとつめのこうさてんをわたります","meaning":"Tôi đi qua ngã tư thứ nhất.","note":"〜目 biểu thị thứ tự."},
        {"text":"信号が青になると、道を渡ります。","furigana":"しんごうがあおになると、みちをわたります","meaning":"Khi đèn chuyển xanh, tôi qua đường.","note":"Vると nêu kết quả tự nhiên hoặc lặp lại."},
        {"text":"橋を渡ると、右に郵便局があります。","furigana":"はしをわたると、みぎにゆうびんきょくがあります","meaning":"Qua cầu thì có bưu điện bên phải.","note":"〜と thường dùng khi chỉ đường."},
        {"text":"駅は郵便局の隣です。","furigana":"えきはゆうびんきょくのとなりです","meaning":"Nhà ga ở cạnh bưu điện.","note":"隣 chỉ vị trí sát bên."},
        {"text":"道が分からないとき、近くの人に聞いてください。","furigana":"みちがわからないとき、ちかくのひとにきいてください","meaning":"Khi không biết đường, hãy hỏi người gần đó.","note":"Phủ định thể thông thường + とき."},
    ]},
    24: {"title":"引っ越しの日 — Ngày chuyển nhà","content":[
        {"text":"先週、新しいうちへ引っ越しました。","furigana":"せんしゅう、あたらしいうちへひっこしました","meaning":"Tuần trước tôi chuyển đến nhà mới.","note":"引っ越します nghĩa là chuyển nhà."},
        {"text":"友達が荷物を運んでくれました。","furigana":"ともだちがにもつをはこんでくれました","meaning":"Bạn đã mang hành lý giúp tôi.","note":"Vてくれます: người khác làm điều có lợi cho mình."},
        {"text":"兄は車で家具を運んでくれました。","furigana":"あにはくるまでかぐをはこんでくれました","meaning":"Anh trai chở đồ nội thất giúp tôi bằng ô tô.","note":"Người cho sự giúp đỡ là chủ ngữ với は/が."},
        {"text":"わたしは友達に部屋を掃除してもらいました。","furigana":"わたしはともだちにへやをそうじしてもらいました","meaning":"Tôi đã nhờ bạn dọn phòng.","note":"Vてもらいます nhìn từ phía người nhận giúp đỡ."},
        {"text":"母はみんなに弁当を作ってくれました。","furigana":"はははみんなにべんとうをつくってくれました","meaning":"Mẹ đã làm cơm hộp cho mọi người.","note":"くれます dùng khi hành động hướng về phía người nói/nhóm người nói."},
        {"text":"わたしはみんなにコーヒーを入れてあげました。","furigana":"わたしはみんなにコーヒーをいれてあげました","meaning":"Tôi đã pha cà phê cho mọi người.","note":"Vてあげます: làm giúp người khác."},
        {"text":"全部終わってから、みんなでお菓子を食べました。","furigana":"ぜんぶおわってから、みんなでおかしをたべました","meaning":"Sau khi xong hết, mọi người cùng ăn bánh kẹo.","note":"Vてから nêu trình tự."},
    ]},
    25: {"title":"転勤しても忘れません — Dù chuyển công tác vẫn không quên","content":[
        {"text":"来月、大阪へ転勤します。","furigana":"らいげつ、おおさかへてんきんします","meaning":"Tháng sau tôi chuyển công tác đến Osaka.","note":"転勤します nghĩa là chuyển nơi công tác."},
        {"text":"大阪へ行ったら、新しい仕事を始めます。","furigana":"おおさかへいったら、あたらしいしごとをはじめます","meaning":"Khi đến Osaka, tôi bắt đầu công việc mới.","note":"Vたら có thể mang nghĩa sau khi/khi."},
        {"text":"仕事が大変でも、頑張ります。","furigana":"しごとがたいへんでも、がんばります","meaning":"Dù công việc vất vả, tôi vẫn cố gắng.","note":"Aな/N + でも diễn tả nhượng bộ."},
        {"text":"暇だったら、京都へ遊びに行きたいです。","furigana":"ひまだったら、きょうとへあそびにいきたいです","meaning":"Nếu rảnh, tôi muốn đi Kyoto chơi.","note":"Aな + だったら tạo điều kiện."},
        {"text":"駅に着いたら、家族に電話します。","furigana":"えきについたら、かぞくにでんわします","meaning":"Khi đến ga, tôi gọi điện cho gia đình.","note":"Mệnh đề sau chỉ xảy ra sau mệnh đề たら."},
        {"text":"いくら忙しくても、日本語を勉強します。","furigana":"いくらいそがしくても、にほんごをべんきょうします","meaning":"Dù bận đến đâu, tôi vẫn học tiếng Nhật.","note":"いくら〜ても nghĩa là dù đến mức nào."},
        {"text":"遠くに住んでも、友達を忘れません。","furigana":"とおくにすんでも、ともだちをわすれません","meaning":"Dù sống ở xa, tôi sẽ không quên bạn bè.","note":"Vても diễn tả dù hành động xảy ra."},
    ]},
}
