export const kanjiVocabulary41to45 = {
  41: [
    { kanji: "呼びます", reading: "よびます", vietnamese: "gọi" },
    { kanji: "取り替えます", reading: "とりかえます", vietnamese: "đổi lại" },
    { kanji: "親切", reading: "しんせつ", vietnamese: "tốt bụng, giúp đỡ" },
    { kanji: "お祝い", reading: "おいわい", vietnamese: "chúc mừng" },
    { kanji: "お年玉", reading: "おとしだま", vietnamese: "tiền mừng tuổi" },
    { kanji: "お見舞い", reading: "おみまい", vietnamese: "thăm người ốm" },
    { kanji: "興味", reading: "きょうみ", vietnamese: "hứng thú" },
    { kanji: "情報", reading: "じょうほう", vietnamese: "thông tin" },
    { kanji: "文法", reading: "ぶんぽう", vietnamese: "ngữ pháp" },
    { kanji: "発音", reading: "はつおん", vietnamese: "phát âm" },
    { kanji: "猿", reading: "さる", vietnamese: "con khỉ" },
    { kanji: "絵本", reading: "えほん", vietnamese: "truyện tranh thiếu nhi" },
    { kanji: "手袋", reading: "てぶくろ", vietnamese: "găng tay" },
    { kanji: "指輪", reading: "ゆびわ", vietnamese: "nhẫn" },
    { kanji: "祖父", reading: "そふ", vietnamese: "ông của mình" },
    { kanji: "祖母", reading: "そぼ", vietnamese: "bà của mình" },
    { kanji: "孫", reading: "まご", vietnamese: "cháu" },
    { kanji: "靴下", reading: "くつした", vietnamese: "tất" },
    { kanji: "申し訳ありません", reading: "もうしわけありません", vietnamese: "xin lỗi" },
    { kanji: "預かります", reading: "あずかります", vietnamese: "giữ hộ" },
    { kanji: "先日", reading: "せんじつ", vietnamese: "mấy hôm trước" },
    { kanji: "助かります", reading: "たすかります", vietnamese: "được giúp, may quá" },
  ],
  42: [
    { kanji: "包みます", reading: "つつみます", vietnamese: "bọc, gói" },
    { kanji: "沸かします", reading: "わかします", vietnamese: "đun sôi" },
    { kanji: "混ぜます", reading: "まぜます", vietnamese: "trộn" },
    { kanji: "計算します", reading: "けいさんします", vietnamese: "tính toán" },
    { kanji: "厚い", reading: "あつい", vietnamese: "dày" },
    { kanji: "薄い", reading: "うすい", vietnamese: "mỏng, nhạt" },
    { kanji: "弁護士", reading: "べんごし", vietnamese: "luật sư" },
    { kanji: "音楽家", reading: "おんがくか", vietnamese: "nhạc sĩ" },
    { kanji: "教育", reading: "きょういく", vietnamese: "giáo dục" },
    { kanji: "歴史", reading: "れきし", vietnamese: "lịch sử" },
    { kanji: "文化", reading: "ぶんか", vietnamese: "văn hóa" },
    { kanji: "社会", reading: "しゃかい", vietnamese: "xã hội" },
    { kanji: "法律", reading: "ほうりつ", vietnamese: "pháp luật" },
    { kanji: "戦争", reading: "せんそう", vietnamese: "chiến tranh" },
    { kanji: "平和", reading: "へいわ", vietnamese: "hòa bình" },
    { kanji: "目的", reading: "もくてき", vietnamese: "mục đích" },
    { kanji: "安全", reading: "あんぜん", vietnamese: "an toàn" },
    { kanji: "論文", reading: "ろんぶん", vietnamese: "luận văn" },
    { kanji: "関係", reading: "かんけい", vietnamese: "mối quan hệ" },
    { kanji: "栓抜き", reading: "せんぬき", vietnamese: "cái mở nắp chai" },
    { kanji: "体温計", reading: "たいおんけい", vietnamese: "nhiệt kế" },
    { kanji: "材料", reading: "ざいりょう", vietnamese: "nguyên liệu" },
    { kanji: "国連", reading: "こくれん", vietnamese: "Liên Hợp Quốc" },
  ],
  43: [
    { kanji: "増えます", reading: "ふえます", vietnamese: "tăng" },
    { kanji: "減ります", reading: "へります", vietnamese: "giảm" },
    { kanji: "上がります", reading: "あがります", vietnamese: "tăng, lên" },
    { kanji: "下がります", reading: "さがります", vietnamese: "giảm, xuống" },
    { kanji: "切れます", reading: "きれます", vietnamese: "đứt" },
    { kanji: "取れます", reading: "とれます", vietnamese: "tuột, rời ra" },
    { kanji: "落ちます", reading: "おちます", vietnamese: "rơi" },
    { kanji: "丈夫", reading: "じょうぶ", vietnamese: "chắc chắn" },
    { kanji: "変", reading: "へん", vietnamese: "lạ" },
    { kanji: "幸せ", reading: "しあわせ", vietnamese: "hạnh phúc" },
    { kanji: "火", reading: "ひ", vietnamese: "lửa" },
    { kanji: "暖房", reading: "だんぼう", vietnamese: "máy sưởi" },
    { kanji: "冷房", reading: "れいぼう", vietnamese: "máy lạnh" },
    { kanji: "会員", reading: "かいいん", vietnamese: "hội viên" },
    { kanji: "適当", reading: "てきとう", vietnamese: "phù hợp" },
    { kanji: "年齢", reading: "ねんれい", vietnamese: "tuổi tác" },
    { kanji: "収入", reading: "しゅうにゅう", vietnamese: "thu nhập" },
  ],
  44: [
    { kanji: "泣きます", reading: "なきます", vietnamese: "khóc" },
    { kanji: "笑います", reading: "わらいます", vietnamese: "cười" },
    { kanji: "乾きます", reading: "かわきます", vietnamese: "khô" },
    { kanji: "起きます", reading: "おきます", vietnamese: "xảy ra" },
    { kanji: "調節します", reading: "ちょうせつします", vietnamese: "điều chỉnh" },
    { kanji: "安全", reading: "あんぜん", vietnamese: "an toàn" },
    { kanji: "丁寧", reading: "ていねい", vietnamese: "lịch sự, cẩn thận" },
    { kanji: "細かい", reading: "こまかい", vietnamese: "chi tiết, tỉ mỉ" },
    { kanji: "濃い", reading: "こい", vietnamese: "đậm" },
    { kanji: "薄い", reading: "うすい", vietnamese: "nhạt, mỏng" },
    { kanji: "空気", reading: "くうき", vietnamese: "không khí" },
    { kanji: "涙", reading: "なみだ", vietnamese: "nước mắt" },
    { kanji: "和食", reading: "わしょく", vietnamese: "món Nhật" },
    { kanji: "洋食", reading: "ようしょく", vietnamese: "món Âu" },
    { kanji: "量", reading: "りょう", vietnamese: "lượng" },
    { kanji: "倍", reading: "ばい", vietnamese: "lần, gấp" },
    { kanji: "半分", reading: "はんぶん", vietnamese: "một nửa" },
    { kanji: "洗濯物", reading: "せんたくもの", vietnamese: "đồ giặt" },
    { kanji: "理由", reading: "りゆう", vietnamese: "lý do" },
    { kanji: "滑ります", reading: "すべります", vietnamese: "trượt" },
  ],
  45: [
    { kanji: "謝ります", reading: "あやまります", vietnamese: "xin lỗi" },
    { kanji: "会います", reading: "あいます", vietnamese: "gặp tai nạn" },
    { kanji: "信じます", reading: "しんじます", vietnamese: "tin tưởng" },
    { kanji: "用意します", reading: "よういします", vietnamese: "chuẩn bị" },
    { kanji: "保証書", reading: "ほしょうしょ", vietnamese: "giấy bảo hành" },
    { kanji: "領収書", reading: "りょうしゅうしょ", vietnamese: "hóa đơn" },
    { kanji: "贈り物", reading: "おくりもの", vietnamese: "quà tặng" },
    { kanji: "間違い電話", reading: "まちがいでんわ", vietnamese: "điện thoại nhầm" },
    { kanji: "係", reading: "かかり", vietnamese: "người phụ trách" },
    { kanji: "中止", reading: "ちゅうし", vietnamese: "dừng, hủy" },
    { kanji: "点", reading: "てん", vietnamese: "điểm" },
    { kanji: "札", reading: "さつ", vietnamese: "tờ tiền" },
    { kanji: "急に", reading: "きゅうに", vietnamese: "đột nhiên" },
  ],
};

const G = (
  title: string,
  pattern: string,
  explanation: string,
  example: string,
  translation: string,
  question: string,
  answer: string,
  choices: string[],
) => ({ title, pattern, explanation, example, translation, question, answer, choices });

export const grammarPoints41to45 = {
  41: [
    G("Nhận khiêm nhường", "いただきます", "Khi nhận từ người trên hoặc cần nói khiêm nhường, dùng いただきます thay cho もらいます.", "部長に 時計をいただきました。", "Tôi được trưởng phòng tặng đồng hồ.", "先生に 本を ＿＿＿。", "いただきました", ["いただきました", "くださいました", "やりました", "あげました"]),
    G("Người trên cho mình", "くださいます", "Dùng khi người trên hoặc người ngoài làm hành động cho mình.", "社長が お土産をくださいました。", "Giám đốc tặng tôi quà.", "先生が 漢字を教えて ＿＿＿。", "くださいました", ["くださいました", "いただきました", "やりました", "あげました"]),
    G("Cho người dưới/động vật", "やります", "Dùng khi cho người dưới tuổi, cây cối, động vật; trong hội thoại hiện đại với người thường dùng あげます.", "犬に えさをやります。", "Tôi cho chó ăn.", "花に 水を ＿＿＿。", "やります", ["やります", "いただきます", "くださいます", "もらいます"]),
    G("Nhận hành động giúp", "Vていただきます", "Diễn tả mình được người trên/người khác làm giúp một việc.", "先生に 本を貸していただきました。", "Tôi được thầy cho mượn sách.", "部長に 書類を見て ＿＿＿。", "いただきました", ["いただきました", "くださいました", "やりました", "あげました"]),
    G("Người trên làm cho mình", "Vてくださいます", "Nhấn mạnh người trên/người khác làm hành động có lợi cho mình.", "先生が 発音を直してくださいました。", "Thầy sửa phát âm cho tôi.", "社長が 駅まで送って ＿＿＿。", "くださいました", ["くださいました", "いただきました", "やりました", "もらいました"]),
  ],
  42: [
    G("Mục đích", "Vる + ために", "Dùng để chỉ mục đích đã có ý chí rõ ràng của người nói.", "店を持つために、貯金しています。", "Tôi tiết kiệm để mở cửa hàng.", "論文を 書く ＿＿＿、資料を集めます。", "ために", ["ために", "のに", "場合は", "そうです"]),
    G("Vì ai/cái gì", "Nの + ために", "Dùng để nói làm gì vì lợi ích của ai/cái gì.", "家族のために、家を建てます。", "Tôi xây nhà cho gia đình.", "子供たち ＿＿＿、公園を作ります。", "のために", ["のために", "のに", "なら", "のにして"]),
    G("Dùng vào việc", "Vる + のに使います", "Dùng のに để nói công dụng: dùng để làm việc gì.", "このはさみは 花を切るのに使います。", "Cái kéo này dùng để cắt hoa.", "栓抜きは びんを開ける ＿＿＿ 使います。", "のに", ["のに", "ために", "場合は", "そうに"]),
    G("Tốn thời gian/tiền", "Vる + のに + 時間/お金がかかります", "Dùng のに để nói cần bao nhiêu thời gian/tiền cho một việc.", "日本へ来るのに、いくらかかりましたか。", "Đến Nhật tốn bao nhiêu?", "論文を書く ＿＿＿ 半年かかりました。", "のに", ["のに", "ために", "場合は", "なら"]),
    G("Mục đích của đồ vật", "Nは Vるのに便利です", "のに có thể đi với 便利, 必要, 役に立ちます để nói một việc cụ thể.", "この辞書は 漢字を調べるのに便利です。", "Từ điển này tiện để tra Kanji.", "体温計は 熱を測る ＿＿＿ 必要です。", "のに", ["のに", "ために", "のため", "でしょう"]),
  ],
  43: [
    G("Trông có vẻ sắp", "Vます bỏます + そうです", "Dùng khi nhìn tình hình và phán đoán một việc sắp xảy ra.", "雨が降りそうです。", "Trời có vẻ sắp mưa.", "ボタンが 取れ ＿＿＿。", "そうです", ["そうです", "ようです", "でしょう", "のに"]),
    G("Trông có vẻ tính chất", "Aい/Aな + そうです", "Tính từ い bỏ い thêm そう; tính từ な bỏ な thêm そう.", "この料理は辛そうです。", "Món này trông cay.", "このかばんは 丈夫 ＿＿＿。", "そうです", ["そうです", "にくいです", "すぎます", "場合です"]),
    G("Ngoại lệ いい・ない", "よさそう / なさそう", "いい đổi thành よさそう, ない đổi thành なさそう.", "この部屋は よさそうです。", "Phòng này trông có vẻ tốt.", "問題は なさ ＿＿＿。", "そうです", ["そうです", "すぎます", "にくいです", "のに"]),
    G("Đi rồi quay lại", "Vてきます", "Diễn tả đi làm một việc rồi quay lại nơi nói.", "たばこを買って来ます。", "Tôi đi mua thuốc rồi về.", "スーパーで 牛乳を買って ＿＿＿。", "来ます", ["来ます", "行きます", "あります", "しまいます"]),
    G("Nhờ đi làm rồi về", "Vてきてください", "Nhờ người nghe đi làm gì đó rồi quay lại.", "飲み物を買って来てください。", "Hãy đi mua đồ uống rồi về.", "駅で 切符を買って ＿＿＿。", "来てください", ["来てください", "行ってください", "あります", "しまってください"]),
  ],
  44: [
    G("Quá mức", "Vます/A + すぎます", "Diễn tả làm quá hoặc trạng thái vượt mức bình thường.", "お酒を飲みすぎました。", "Tôi uống quá nhiều rượu.", "このスープは 塩を入れ ＿＿＿。", "すぎました", ["すぎました", "やすいです", "にくいです", "そうです"]),
    G("Dễ làm", "Vます bỏます + やすいです", "Dùng để nói một việc dễ làm.", "このパソコンは使いやすいです。", "Máy tính này dễ dùng.", "この説明書は 読み ＿＿＿。", "やすいです", ["やすいです", "にくいです", "すぎます", "そうです"]),
    G("Khó làm", "Vます bỏます + にくいです", "Dùng để nói một việc khó làm.", "東京は住みにくいです。", "Tokyo khó sống.", "この字は 小さくて 読み ＿＿＿。", "にくいです", ["にくいです", "やすいです", "すぎます", "そうです"]),
    G("Làm cho tính từ い", "Aくします", "Biến đổi trạng thái của vật theo tính từ い.", "テレビの音を大きくします。", "Tôi làm âm TV to lên.", "部屋を 明る ＿＿＿。", "くします", ["くします", "にします", "すぎます", "そうです"]),
    G("Làm cho tính từ な/danh từ", "Aな/N + にします", "Biến đổi hoặc quyết định thành trạng thái/danh từ.", "部屋をきれいにします。", "Tôi làm phòng sạch.", "会議室を 静か ＿＿＿。", "にします", ["にします", "くします", "すぎます", "やすいです"]),
  ],
  45: [
    G("Trường hợp động từ", "Vた/Vる + 場合は", "Dùng để nói cách xử lý trong một trường hợp cụ thể.", "パスポートをなくした場合は、連絡してください。", "Nếu mất hộ chiếu, hãy liên lạc.", "事故に ＿＿＿場合は、警察へ電話してください。", "会った", ["会った", "会うのに", "会って", "会えばいい"]),
    G("Trường hợp danh từ", "Nの + 場合は", "Với danh từ, thêm の trước 場合は.", "火事の場合は、119番に電話してください。", "Trường hợp hỏa hoạn, hãy gọi 119.", "雨 ＿＿＿ 場合は、中止です。", "の", ["の", "な", "に", "で"]),
    G("Mặc dù vậy mà", "Thể thường + のに", "Dùng khi kết quả trái với mong đợi, thường có cảm xúc tiếc, bất mãn hoặc ngạc nhiên.", "約束をしたのに、来ませんでした。", "Dù đã hẹn mà không đến.", "毎日 練習している ＿＿＿、上手になりません。", "のに", ["のに", "場合は", "ために", "そうです"]),
    G("のに với danh từ/tính từ な", "N/Aな + なのに", "Danh từ và tính từ な dùng なのに.", "日曜日なのに、仕事をします。", "Dù là Chủ nhật mà vẫn làm việc.", "便利 ＿＿＿、だれも使いません。", "なのに", ["なのに", "のに", "場合は", "ために"]),
    G("Phân biệt ても và のに", "ても: dù... vẫn / のに: vậy mà", "のに nhấn mạnh sự trái kỳ vọng; ても thường trung tính hơn trong điều kiện nhượng bộ.", "高いのに、すぐ壊れました。", "Đắt vậy mà hỏng ngay.", "保証書がある ＿＿＿、取り替えてくれませんでした。", "のに", ["のに", "ても", "ために", "そうで"]),
  ],
};
