export const kanjiVocabulary36to40 = {
  36: [
    { kanji: "届きます", reading: "とどきます", vietnamese: "được gửi đến" },
    { kanji: "出ます", reading: "でます", vietnamese: "tham gia, xuất hiện" },
    { kanji: "打ちます", reading: "うちます", vietnamese: "đánh, gõ" },
    { kanji: "貯金します", reading: "ちょきんします", vietnamese: "tiết kiệm tiền" },
    { kanji: "太ります", reading: "ふとります", vietnamese: "tăng cân" },
    { kanji: "痩せます", reading: "やせます", vietnamese: "giảm cân" },
    { kanji: "過ぎます", reading: "すぎます", vietnamese: "quá, đi qua" },
    { kanji: "慣れます", reading: "なれます", vietnamese: "quen với" },
    { kanji: "硬い", reading: "かたい", vietnamese: "cứng" },
    { kanji: "軟らかい", reading: "やわらかい", vietnamese: "mềm" },
    { kanji: "電子", reading: "でんし", vietnamese: "điện tử" },
    { kanji: "携帯", reading: "けいたい", vietnamese: "cầm tay, di động" },
    { kanji: "工場", reading: "こうじょう", vietnamese: "nhà máy" },
    { kanji: "健康", reading: "けんこう", vietnamese: "sức khỏe" },
    { kanji: "剣道", reading: "けんどう", vietnamese: "kiếm đạo" },
    { kanji: "毎週", reading: "まいしゅう", vietnamese: "hằng tuần" },
    { kanji: "毎月", reading: "まいつき", vietnamese: "hằng tháng" },
    { kanji: "毎年", reading: "まいとし", vietnamese: "hằng năm" },
    { kanji: "必ず", reading: "かならず", vietnamese: "nhất định" },
    { kanji: "絶対に", reading: "ぜったいに", vietnamese: "tuyệt đối" },
    { kanji: "水泳", reading: "すいえい", vietnamese: "môn bơi" },
    { kanji: "気持", reading: "きもち", vietnamese: "cảm xúc, tâm trạng" },
  ],
  37: [
    { kanji: "褒めます", reading: "ほめます", vietnamese: "khen" },
    { kanji: "叱ります", reading: "しかります", vietnamese: "mắng" },
    { kanji: "誘います", reading: "さそいます", vietnamese: "mời, rủ" },
    { kanji: "起こします", reading: "おこします", vietnamese: "đánh thức" },
    { kanji: "招待します", reading: "しょうたいします", vietnamese: "mời" },
    { kanji: "頼みます", reading: "たのみます", vietnamese: "nhờ vả" },
    { kanji: "踏みます", reading: "ふみます", vietnamese: "giẫm lên" },
    { kanji: "壊します", reading: "こわします", vietnamese: "làm hỏng" },
    { kanji: "汚します", reading: "よごします", vietnamese: "làm bẩn" },
    { kanji: "輸出します", reading: "ゆしゅつします", vietnamese: "xuất khẩu" },
    { kanji: "輸入します", reading: "ゆにゅうします", vietnamese: "nhập khẩu" },
    { kanji: "翻訳します", reading: "ほんやくします", vietnamese: "dịch" },
    { kanji: "発明します", reading: "はつめいします", vietnamese: "phát minh" },
    { kanji: "発見します", reading: "はっけんします", vietnamese: "phát hiện" },
    { kanji: "設計します", reading: "せっけいします", vietnamese: "thiết kế" },
    { kanji: "米", reading: "こめ", vietnamese: "gạo" },
    { kanji: "石油", reading: "せきゆ", vietnamese: "dầu mỏ" },
    { kanji: "原料", reading: "げんりょう", vietnamese: "nguyên liệu" },
    { kanji: "材料", reading: "ざいりょう", vietnamese: "vật liệu" },
    { kanji: "泥棒", reading: "どろぼう", vietnamese: "kẻ trộm" },
    { kanji: "警官", reading: "けいかん", vietnamese: "cảnh sát" },
    { kanji: "建築家", reading: "けんちくか", vietnamese: "kiến trúc sư" },
    { kanji: "科学者", reading: "かがくしゃ", vietnamese: "nhà khoa học" },
    { kanji: "世界中", reading: "せかいじゅう", vietnamese: "khắp thế giới" },
  ],
  38: [
    { kanji: "育てます", reading: "そだてます", vietnamese: "nuôi, trồng" },
    { kanji: "運びます", reading: "はこびます", vietnamese: "vận chuyển" },
    { kanji: "亡くなります", reading: "なくなります", vietnamese: "mất, qua đời" },
    { kanji: "入院します", reading: "にゅういんします", vietnamese: "nhập viện" },
    { kanji: "退院します", reading: "たいいんします", vietnamese: "xuất viện" },
    { kanji: "入れます", reading: "いれます", vietnamese: "bật, cho vào" },
    { kanji: "切ります", reading: "きります", vietnamese: "tắt, cắt" },
    { kanji: "掛けます", reading: "かけます", vietnamese: "khóa, treo" },
    { kanji: "気持ち", reading: "きもち", vietnamese: "cảm giác" },
    { kanji: "赤ちゃん", reading: "あかちゃん", vietnamese: "em bé" },
    { kanji: "小学校", reading: "しょうがっこう", vietnamese: "trường tiểu học" },
    { kanji: "中学校", reading: "ちゅうがっこう", vietnamese: "trường trung học cơ sở" },
    { kanji: "駅前", reading: "えきまえ", vietnamese: "trước ga" },
    { kanji: "海岸", reading: "かいがん", vietnamese: "bờ biển" },
    { kanji: "書類", reading: "しょるい", vietnamese: "giấy tờ, tài liệu" },
    { kanji: "電源", reading: "でんげん", vietnamese: "nguồn điện" },
    { kanji: "原爆", reading: "げんばく", vietnamese: "bom nguyên tử" },
    { kanji: "研究室", reading: "けんきゅうしつ", vietnamese: "phòng nghiên cứu" },
    { kanji: "整理します", reading: "せいりします", vietnamese: "sắp xếp, chỉnh lý" },
    { kanji: "冊", reading: "さつ", vietnamese: "quyển" },
    { kanji: "押します", reading: "おします", vietnamese: "ấn, đóng dấu" },
  ],
  39: [
    { kanji: "答えます", reading: "こたえます", vietnamese: "trả lời" },
    { kanji: "倒れます", reading: "たおれます", vietnamese: "đổ, ngã" },
    { kanji: "焼けます", reading: "やけます", vietnamese: "cháy, nướng chín" },
    { kanji: "通ります", reading: "とおります", vietnamese: "đi qua" },
    { kanji: "死にます", reading: "しにます", vietnamese: "chết" },
    { kanji: "安心します", reading: "あんしんします", vietnamese: "yên tâm" },
    { kanji: "遅刻します", reading: "ちこくします", vietnamese: "đến muộn" },
    { kanji: "早退します", reading: "そうたいします", vietnamese: "về sớm" },
    { kanji: "離婚します", reading: "りこんします", vietnamese: "ly hôn" },
    { kanji: "複雑", reading: "ふくざつ", vietnamese: "phức tạp" },
    { kanji: "邪魔", reading: "じゃま", vietnamese: "cản trở" },
    { kanji: "汚い", reading: "きたない", vietnamese: "bẩn" },
    { kanji: "悲しい", reading: "かなしい", vietnamese: "buồn" },
    { kanji: "恥ずかしい", reading: "はずかしい", vietnamese: "xấu hổ" },
    { kanji: "地震", reading: "じしん", vietnamese: "động đất" },
    { kanji: "台風", reading: "たいふう", vietnamese: "bão" },
    { kanji: "火事", reading: "かじ", vietnamese: "hỏa hoạn" },
    { kanji: "事故", reading: "じこ", vietnamese: "tai nạn" },
    { kanji: "電話代", reading: "でんわだい", vietnamese: "tiền điện thoại" },
    { kanji: "汗", reading: "あせ", vietnamese: "mồ hôi" },
    { kanji: "大勢", reading: "おおぜい", vietnamese: "nhiều người" },
    { kanji: "途中", reading: "とちゅう", vietnamese: "giữa đường" },
    { kanji: "並びます", reading: "ならびます", vietnamese: "xếp hàng" },
  ],
  40: [
    { kanji: "数えます", reading: "かぞえます", vietnamese: "đếm" },
    { kanji: "測ります", reading: "はかります", vietnamese: "đo, cân" },
    { kanji: "確かめます", reading: "たしかめます", vietnamese: "xác nhận" },
    { kanji: "合います", reading: "あいます", vietnamese: "vừa, hợp" },
    { kanji: "出発します", reading: "しゅっぱつします", vietnamese: "xuất phát" },
    { kanji: "到着します", reading: "とうちゃくします", vietnamese: "đến nơi" },
    { kanji: "酔います", reading: "よいます", vietnamese: "say" },
    { kanji: "危険", reading: "きけん", vietnamese: "nguy hiểm" },
    { kanji: "必要", reading: "ひつよう", vietnamese: "cần thiết" },
    { kanji: "宇宙", reading: "うちゅう", vietnamese: "vũ trụ" },
    { kanji: "地球", reading: "ちきゅう", vietnamese: "trái đất" },
    { kanji: "忘年会", reading: "ぼうねんかい", vietnamese: "tiệc tất niên" },
    { kanji: "新年会", reading: "しんねんかい", vietnamese: "tiệc tân niên" },
    { kanji: "大会", reading: "たいかい", vietnamese: "đại hội, cuộc thi lớn" },
    { kanji: "表", reading: "おもて", vietnamese: "mặt trước" },
    { kanji: "裏", reading: "うら", vietnamese: "mặt sau" },
    { kanji: "返事", reading: "へんじ", vietnamese: "hồi âm" },
    { kanji: "傷", reading: "きず", vietnamese: "vết thương" },
    { kanji: "長さ", reading: "ながさ", vietnamese: "chiều dài" },
    { kanji: "重さ", reading: "おもさ", vietnamese: "cân nặng" },
    { kanji: "高さ", reading: "たかさ", vietnamese: "độ cao" },
    { kanji: "大きさ", reading: "おおきさ", vietnamese: "kích thước" },
    { kanji: "以上", reading: "いじょう", vietnamese: "trở lên" },
    { kanji: "以下", reading: "いか", vietnamese: "trở xuống" },
    { kanji: "本当", reading: "ほんとう", vietnamese: "sự thật" },
    { kanji: "成績", reading: "せいせき", vietnamese: "thành tích" },
    { kanji: "様子", reading: "ようす", vietnamese: "tình hình, dáng vẻ" },
  ],
};

const G = (
  title: string,
  pattern: string,
  explanation: string,
  example: string,
  translation: string,
  question: string,
  answer: string,
  choices: string[],
) => ({ title, pattern, explanation, example, translation, question, answer, choices });

export const grammarPoints36to40 = {
  36: [
    G("Mục tiêu khả năng", "V可能形 / Vない + ように", "Dùng ように để nói mục tiêu đạt được một trạng thái hoặc khả năng.", "速く泳げるように、練習しています。", "Tôi luyện tập để có thể bơi nhanh.", "漢字を 忘れない ＿＿＿、メモします。", "ように", ["ように", "ために", "ながら", "しか"]),
    G("Trở nên có thể", "V可能形 + ようになりました", "Diễn tả sự thay đổi: trước đây chưa làm được, giờ đã làm được.", "新聞が読めるようになりました。", "Tôi đã có thể đọc báo.", "日本語で 意見が 言える ＿＿＿。", "ようになりました", ["ようになりました", "ようにします", "ことにしました", "つもりです"]),
    G("Không còn làm nữa", "Vない + ようになりました", "Diễn tả sự thay đổi sang trạng thái không còn làm việc gì.", "あまりテレビを見ないようになりました。", "Tôi không còn xem TV nhiều nữa.", "最近 甘い物を ＿＿＿。", "食べないようになりました", ["食べないようになりました", "食べるようにします", "食べたほうがいい", "食べてみます"]),
    G("Cố gắng duy trì", "Vる / Vない + ようにしています", "Diễn tả thói quen hoặc nỗ lực có ý thức.", "毎日 野菜を食べるようにしています。", "Tôi cố gắng ăn rau mỗi ngày.", "健康のために、夜遅く ＿＿＿。", "寝ないようにしています", ["寝ないようにしています", "寝るつもりです", "寝られました", "寝るな"]),
    G("Yêu cầu cố gắng", "Vる / Vない + ようにしてください", "Dùng để nhắc người nghe cố gắng làm hoặc tránh làm.", "忘れないようにしてください。", "Xin hãy cố gắng đừng quên.", "明日は 遅れない ＿＿＿。", "ようにしてください", ["ようにしてください", "ようになりました", "ことがあります", "しかありません"]),
  ],
  37: [
    G("Bị động trực tiếp", "Người は Người に Vられます", "Chủ thể chịu hành động từ người khác.", "私は 先生に 褒められました。", "Tôi được giáo viên khen.", "私は 母に ＿＿＿。", "叱られました", ["叱られました", "叱りました", "叱らせました", "叱れました"]),
    G("Bị động gián tiếp", "Người は Người に N を Vられます", "Diễn tả người nói bị ảnh hưởng bởi hành động của người khác.", "弟に パソコンを 壊されました。", "Tôi bị em trai làm hỏng máy tính.", "私は 泥棒に 財布を ＿＿＿。", "取られました", ["取られました", "取りました", "取れました", "取ります"]),
    G("Bị động tổ chức/sự kiện", "N が Vられます", "Dùng khi sự kiện, lễ hội, triển lãm được tổ chức/mở ra.", "大阪で 展覧会が 開かれます。", "Triển lãm được tổ chức ở Osaka.", "来月 大会が ＿＿＿。", "行われます", ["行われます", "行います", "行けます", "行こう"]),
    G("Tác nhân phát minh", "N は 人 によって Vられました", "によって nêu tác giả, người phát minh hoặc người tạo ra.", "電話は ベルによって 発明されました。", "Điện thoại được Bell phát minh.", "この橋は 有名な建築家 ＿＿＿ 設計されました。", "によって", ["によって", "に", "で", "から"]),
    G("Cách chia bị động", "Vます → Vられます", "Nhóm I đổi âm i sang a + れます; nhóm II bỏ ます thêm られます; します→されます.", "書きます → 書かれます。", "viết → được viết/bị viết.", "読みます → 読 ＿＿＿。", "まれます", ["まれます", "めます", "みられます", "ませます"]),
  ],
  38: [
    G("Danh từ hóa làm chủ đề", "Vる + のは", "Biến cụm động từ thành danh từ để làm chủ đề.", "絵を描くのは 楽しいです。", "Việc vẽ tranh thì vui.", "早く 起きる ＿＿＿ 大変です。", "のは", ["のは", "のが", "のを", "ので"]),
    G("Danh từ hóa với sở thích", "Vる + のが", "Dùng のが với 好き, 嫌い, 上手, 下手.", "星を見るのが 好きです。", "Tôi thích ngắm sao.", "私は 料理を作る ＿＿＿ 好きです。", "のが", ["のが", "のは", "のを", "ので"]),
    G("Danh từ hóa làm tân ngữ", "Vる + のを", "Dùng のを khi cụm danh từ hóa là tân ngữ của 忘れます, 知っています, 覚えています...", "薬を飲むのを 忘れました。", "Tôi quên uống thuốc.", "電気を消す ＿＿＿ 忘れました。", "のを", ["のを", "のは", "のが", "ので"]),
    G("Nhấn mạnh thời điểm/sự việc", "Vた + のは ... です", "Dùng để nêu rõ thời điểm, nơi chốn hoặc người liên quan đến sự việc.", "初めて会ったのは 3年前です。", "Lần đầu gặp là 3 năm trước.", "日本へ来た ＿＿＿ 去年です。", "のは", ["のは", "のが", "のを", "ので"]),
    G("名詞 hóa với が trong mệnh đề", "Sが + Vのを", "Chủ ngữ trong mệnh đề danh từ hóa thường dùng が.", "鈴木さんが結婚したのを知っていますか。", "Bạn có biết Suzuki đã kết hôn không?", "ミラーさん ＿＿＿ 入院したのを 知っていますか。", "が", ["が", "は", "を", "で"]),
  ],
  39: [
    G("Nguyên nhân bằng て", "Vて / Aくて / Nで", "Dùng để nêu nguyên nhân dẫn đến cảm xúc, trạng thái hoặc kết quả không chủ ý.", "ニュースを聞いて、びっくりしました。", "Nghe tin nên ngạc nhiên.", "家族に 会えなく ＿＿＿、寂しいです。", "て", ["て", "ても", "ながら", "なら"]),
    G("Vì không có/không thể", "なくて", "なくて nêu nguyên nhân với phủ định hoặc tính từ ない.", "お金がなくて、買えません。", "Vì không có tiền nên không mua được.", "時間が ＿＿＿、行けません。", "なくて", ["なくて", "ないで", "なければ", "ないように"]),
    G("Nguyên nhân sự cố", "N + で", "Dùng với tai nạn, thiên tai, bệnh tật hoặc sự kiện gây ra kết quả.", "事故で 電車が止まりました。", "Vì tai nạn nên tàu dừng.", "台風 ＿＿＿ 木が倒れました。", "で", ["で", "に", "を", "が"]),
    G("Cảm xúc do nguyên nhân", "原因 + て、感情", "Mẫu này thường đi với びっくりします, 安心します, がっかりします, うれしい, 悲しい...", "試験に合格して、安心しました。", "Thi đỗ nên yên tâm.", "友達に会えて、＿＿＿。", "うれしいです", ["うれしいです", "うれしくて", "うれしいで", "うれしければ"]),
    G("Không dùng cho ý chí mạnh", "原因て + trạng thái", "Mẫu nguyên nhân て thường không dùng để nối với mệnh lệnh, ý chí hoặc nhờ vả trực tiếp.", "病気で 学校を休みました。", "Vì bệnh nên nghỉ học.", "火事 ＿＿＿ 家が焼けました。", "で", ["で", "に", "を", "へ"]),
  ],
  40: [
    G("Câu hỏi lồng WH", "疑問詞 + thể thường + か", "Biến câu hỏi có từ nghi vấn thành một phần trong câu lớn.", "会議は何時に終わるか、わかりません。", "Tôi không biết cuộc họp kết thúc lúc mấy giờ.", "駅まで どうやって 行く ＿＿＿、教えてください。", "か", ["か", "かどうか", "と", "の"]),
    G("Có hay không", "Thể thường + かどうか", "Dùng với câu hỏi Yes/No được lồng vào câu.", "本当かどうか、わかりません。", "Tôi không biết có thật hay không.", "サイズが 合う ＿＿＿、確かめます。", "かどうか", ["かどうか", "か", "とおりに", "ので"]),
    G("Kiểm tra/xác nhận", "かどうか + 確かめます / 調べます", "Hay dùng khi kiểm tra xem đúng sai, có hay không, vừa hay không.", "間違いがないかどうか、調べてください。", "Hãy kiểm tra xem có lỗi không.", "返事が 来た ＿＿＿、見てください。", "かどうか", ["かどうか", "か", "なら", "ように"]),
    G("Thử làm", "Vて + みます", "Dùng khi thử làm một việc để biết kết quả hoặc cảm giác.", "新しい靴を履いてみます。", "Tôi sẽ thử đi giày mới.", "この料理を 食べて ＿＿＿。", "みます", ["みます", "あります", "おきます", "しまいます"]),
    G("Hỏi thử lịch sự", "Vてみてもいいですか", "Kết hợp てみます với xin phép để hỏi có được thử không.", "この服を着てみてもいいですか。", "Tôi mặc thử áo này được không?", "このカメラを 使って ＿＿＿。", "みてもいいですか", ["みてもいいですか", "みなければなりません", "みるな", "みられました"]),
  ],
};
