export const kanjiVocabulary26to30 = {
  26: [
    { kanji: "見ます", reading: "みます", vietnamese: "xem, khám bệnh" },
    { kanji: "探します", reading: "さがします", vietnamese: "tìm kiếm" },
    { kanji: "遅れます", reading: "おくれます", vietnamese: "chậm, muộn" },
    { kanji: "間に合います", reading: "まにあいます", vietnamese: "kịp" },
    { kanji: "参加します", reading: "さんかします", vietnamese: "tham gia" },
    { kanji: "申し込みます", reading: "もうしこみます", vietnamese: "đăng ký" },
    { kanji: "都合", reading: "つごう", vietnamese: "sự thuận tiện" },
    { kanji: "気分", reading: "きぶん", vietnamese: "tâm trạng, cảm giác" },
    { kanji: "新聞社", reading: "しんぶんしゃ", vietnamese: "tòa soạn báo" },
    { kanji: "運動会", reading: "うんどうかい", vietnamese: "hội thao" },
    { kanji: "場所", reading: "ばしょ", vietnamese: "địa điểm" },
    { kanji: "直接", reading: "ちょくせつ", vietnamese: "trực tiếp" },
    { kanji: "子供の日", reading: "こどものひ", vietnamese: "ngày thiếu nhi" },
    { kanji: "柔道", reading: "じゅうどう", vietnamese: "nhu đạo" },
    { kanji: "片付きます", reading: "かたづきます", vietnamese: "được dọn dẹp" },
    { kanji: "置き場", reading: "おきば", vietnamese: "nơi để" },
    { kanji: "横", reading: "よこ", vietnamese: "bên cạnh" },
    { kanji: "瓶", reading: "びん", vietnamese: "chai, lọ" },
    { kanji: "缶", reading: "かん", vietnamese: "lon" },
    { kanji: "連絡します", reading: "れんらくします", vietnamese: "liên lạc" },
    { kanji: "電子メール", reading: "でんしメール", vietnamese: "thư điện tử" },
    { kanji: "宇宙", reading: "うちゅう", vietnamese: "vũ trụ" },
    { kanji: "宇宙船", reading: "うちゅうせん", vietnamese: "tàu vũ trụ" },
    { kanji: "宇宙飛行士", reading: "うちゅうひこうし", vietnamese: "phi hành gia" },
  ],
  27: [
    { kanji: "飼います", reading: "かいます", vietnamese: "nuôi động vật" },
    { kanji: "建てます", reading: "たてます", vietnamese: "xây" },
    { kanji: "走ります", reading: "はしります", vietnamese: "chạy" },
    { kanji: "取ります", reading: "とります", vietnamese: "lấy, xin nghỉ" },
    { kanji: "見えます", reading: "みえます", vietnamese: "có thể nhìn thấy" },
    { kanji: "聞こえます", reading: "きこえます", vietnamese: "có thể nghe thấy" },
    { kanji: "開きます", reading: "ひらきます", vietnamese: "mở" },
    { kanji: "鳥", reading: "とり", vietnamese: "chim" },
    { kanji: "声", reading: "こえ", vietnamese: "giọng nói" },
    { kanji: "波", reading: "なみ", vietnamese: "sóng" },
    { kanji: "花火", reading: "はなび", vietnamese: "pháo hoa" },
    { kanji: "景色", reading: "けしき", vietnamese: "phong cảnh" },
    { kanji: "昼間", reading: "ひるま", vietnamese: "ban ngày" },
    { kanji: "昔", reading: "むかし", vietnamese: "ngày xưa" },
    { kanji: "道具", reading: "どうぐ", vietnamese: "dụng cụ" },
    { kanji: "自動販売機", reading: "じどうはんばいき", vietnamese: "máy bán hàng tự động" },
    { kanji: "通信販売", reading: "つうしんはんばい", vietnamese: "bán hàng qua mạng/điện thoại" },
    { kanji: "関西空港", reading: "かんさいくうこう", vietnamese: "sân bay Kansai" },
    { kanji: "秋葉原", reading: "あきはばら", vietnamese: "Akihabara" },
    { kanji: "日曜大工", reading: "にちようだいく", vietnamese: "tự làm đồ gỗ ngày nghỉ" },
    { kanji: "本棚", reading: "ほんだな", vietnamese: "giá sách" },
    { kanji: "夢", reading: "ゆめ", vietnamese: "giấc mơ" },
    { kanji: "家", reading: "いえ", vietnamese: "nhà" },
    { kanji: "将来", reading: "しょうらい", vietnamese: "tương lai" },
  ],
  28: [
    { kanji: "売れます", reading: "うれます", vietnamese: "bán chạy" },
    { kanji: "踊ります", reading: "おどります", vietnamese: "nhảy, múa" },
    { kanji: "選びます", reading: "えらびます", vietnamese: "chọn" },
    { kanji: "違います", reading: "ちがいます", vietnamese: "khác" },
    { kanji: "通います", reading: "かよいます", vietnamese: "đi đi về về" },
    { kanji: "熱心", reading: "ねっしん", vietnamese: "nhiệt tình" },
    { kanji: "優しい", reading: "やさしい", vietnamese: "hiền lành" },
    { kanji: "偉い", reading: "えらい", vietnamese: "vĩ đại, đáng nể" },
    { kanji: "習慣", reading: "しゅうかん", vietnamese: "thói quen" },
    { kanji: "経験", reading: "けいけん", vietnamese: "kinh nghiệm" },
    { kanji: "力", reading: "ちから", vietnamese: "sức lực" },
    { kanji: "人気", reading: "にんき", vietnamese: "sự yêu thích" },
    { kanji: "形", reading: "かたち", vietnamese: "hình dáng" },
    { kanji: "色", reading: "いろ", vietnamese: "màu sắc" },
    { kanji: "味", reading: "あじ", vietnamese: "vị" },
    { kanji: "品物", reading: "しなもの", vietnamese: "hàng hóa" },
    { kanji: "値段", reading: "ねだん", vietnamese: "giá cả" },
    { kanji: "給料", reading: "きゅうりょう", vietnamese: "lương" },
    { kanji: "番組", reading: "ばんぐみ", vietnamese: "chương trình" },
    { kanji: "小説", reading: "しょうせつ", vietnamese: "tiểu thuyết" },
    { kanji: "歌手", reading: "かしゅ", vietnamese: "ca sĩ" },
    { kanji: "管理人", reading: "かんりにん", vietnamese: "người quản lý" },
    { kanji: "息子", reading: "むすこ", vietnamese: "con trai mình" },
    { kanji: "娘", reading: "むすめ", vietnamese: "con gái mình" },
  ],
  29: [
    { kanji: "開きます", reading: "あきます", vietnamese: "mở" },
    { kanji: "閉まります", reading: "しまります", vietnamese: "đóng" },
    { kanji: "消えます", reading: "きえます", vietnamese: "tắt, biến mất" },
    { kanji: "込みます", reading: "こみます", vietnamese: "đông" },
    { kanji: "壊れます", reading: "こわれます", vietnamese: "hỏng" },
    { kanji: "割れます", reading: "われます", vietnamese: "vỡ" },
    { kanji: "折れます", reading: "おれます", vietnamese: "gãy" },
    { kanji: "破れます", reading: "やぶれます", vietnamese: "rách" },
    { kanji: "汚れます", reading: "よごれます", vietnamese: "bẩn" },
    { kanji: "付きます", reading: "つきます", vietnamese: "được gắn, sáng" },
    { kanji: "外れます", reading: "はずれます", vietnamese: "tuột, bung" },
    { kanji: "止まります", reading: "とまります", vietnamese: "dừng" },
    { kanji: "間違えます", reading: "まちがえます", vietnamese: "nhầm" },
    { kanji: "落とします", reading: "おとします", vietnamese: "đánh rơi" },
    { kanji: "掛かります", reading: "かかります", vietnamese: "được khóa" },
    { kanji: "皿", reading: "さら", vietnamese: "đĩa" },
    { kanji: "袋", reading: "ふくろ", vietnamese: "túi" },
    { kanji: "財布", reading: "さいふ", vietnamese: "ví" },
    { kanji: "枝", reading: "えだ", vietnamese: "cành cây" },
    { kanji: "駅員", reading: "えきいん", vietnamese: "nhân viên nhà ga" },
    { kanji: "忘れ物", reading: "わすれもの", vietnamese: "đồ bỏ quên" },
    { kanji: "網棚", reading: "あみだな", vietnamese: "giá hành lý" },
  ],
  30: [
    { kanji: "掛けます", reading: "かけます", vietnamese: "treo" },
    { kanji: "飾ります", reading: "かざります", vietnamese: "trang trí" },
    { kanji: "並べます", reading: "ならべます", vietnamese: "xếp thành hàng" },
    { kanji: "植えます", reading: "うえます", vietnamese: "trồng" },
    { kanji: "戻します", reading: "もどします", vietnamese: "đưa về, trả về" },
    { kanji: "片付けます", reading: "かたづけます", vietnamese: "dọn dẹp" },
    { kanji: "知らせます", reading: "しらせます", vietnamese: "thông báo" },
    { kanji: "相談します", reading: "そうだんします", vietnamese: "trao đổi, thảo luận" },
    { kanji: "予習します", reading: "よしゅうします", vietnamese: "chuẩn bị bài mới" },
    { kanji: "復習します", reading: "ふくしゅうします", vietnamese: "ôn bài" },
    { kanji: "お子さん", reading: "おこさん", vietnamese: "con của người khác" },
    { kanji: "授業", reading: "じゅぎょう", vietnamese: "giờ học" },
    { kanji: "講義", reading: "こうぎ", vietnamese: "bài giảng" },
    { kanji: "予定", reading: "よてい", vietnamese: "dự định" },
    { kanji: "お知らせ", reading: "おしらせ", vietnamese: "thông báo" },
    { kanji: "案内書", reading: "あんないしょ", vietnamese: "tài liệu hướng dẫn" },
    { kanji: "ごみ箱", reading: "ごみばこ", vietnamese: "thùng rác" },
    { kanji: "人形", reading: "にんぎょう", vietnamese: "búp bê" },
    { kanji: "花瓶", reading: "かびん", vietnamese: "lọ hoa" },
    { kanji: "鏡", reading: "かがみ", vietnamese: "gương" },
    { kanji: "引き出し", reading: "ひきだし", vietnamese: "ngăn kéo" },
    { kanji: "玄関", reading: "げんかん", vietnamese: "cửa ra vào" },
    { kanji: "廊下", reading: "ろうか", vietnamese: "hành lang" },
    { kanji: "壁", reading: "かべ", vietnamese: "tường" },
  ],
};

const G = (
  title: string,
  pattern: string,
  explanation: string,
  example: string,
  translation: string,
  question: string,
  answer: string,
  choices: string[],
) => ({ title, pattern, explanation, example, translation, question, answer, choices });

export const grammarPoints26to30 = {
  26: [
    G("Giải thích với んです", "Thể thông thường + んです", "Dùng khi giải thích lý do, hoàn cảnh hoặc nhấn mạnh thông tin phía sau.", "あしたから 旅行なんです。", "Từ ngày mai tôi đi du lịch.", "頭が 痛い ＿＿＿。", "んです", ["んです", "でしょう", "ながら", "しか"]),
    G("Hỏi lý do với んですか", "どうして + thể thường + んですか", "Mẫu này hỏi nguyên nhân một cách tự nhiên khi người nói thấy có dấu hiệu hoặc muốn biết lý do.", "どうして 遅れたんですか。", "Tại sao bạn đến muộn vậy?", "どうして 会議に 来なかった ＿＿＿。", "んですか", ["んですか", "ていますか", "ながら", "しか"]),
    G("Mở lời nhờ vả", "Vたいんですが、...", "Dùng んですが để trình bày hoàn cảnh trước khi nhờ, hỏi hoặc xin lời khuyên.", "切符を 買いたいんですが、どこで 買ったらいいですか。", "Tôi muốn mua vé, mua ở đâu thì tốt?", "日本語を 勉強したい ＿＿＿、いい学校を 知っていますか。", "んですが", ["んですが", "ながら", "しか", "てあります"]),
    G("Nhờ lịch sự", "Vていただけませんか", "Cách nhờ vả rất lịch sự, mềm hơn Vてください.", "もう一度 説明していただけませんか。", "Bạn có thể giải thích lại giúp tôi được không?", "この漢字を 読んで ＿＿＿。", "いただけませんか", ["いただけませんか", "しまいました", "ありますか", "おきますか"]),
    G("Xin lời khuyên", "疑問詞 + Vたらいいですか", "Dùng khi hỏi nên làm gì, đi đâu, mua ở đâu, nói với ai.", "どこで 買ったらいいですか。", "Nên mua ở đâu thì tốt?", "パスポートを なくしたら、どこへ ＿＿＿。", "行ったらいいですか", ["行ったらいいですか", "行きながら", "行けます", "行ってあります"]),
  ],
  27: [
    G("Thể khả năng", "V可能形", "Nhóm I đổi âm i sang e + ます; nhóm II bỏ ます thêm られます; します→できます.", "日本語の新聞が 読めます。", "Tôi có thể đọc báo tiếng Nhật.", "ここで 写真が ＿＿＿か。", "撮れます", ["撮れます", "撮ります", "撮っています", "撮ってあります"]),
    G("Đối tượng khả năng với が", "N が V可能形", "Khi nói khả năng, đối tượng thường dùng が thay vì を.", "漢字が 書けます。", "Tôi có thể viết Kanji.", "私は 日本語の本 ＿＿＿ 読めます。", "が", ["が", "を", "で", "に"]),
    G("見えます・聞こえます", "N が 見えます / 聞こえます", "Diễn tả tự nhiên nhìn/nghe thấy do điều kiện bên ngoài, không phải cố ý.", "波の音が 聞こえます。", "Nghe thấy tiếng sóng.", "ここから 富士山 ＿＿＿ 見えます。", "が", ["が", "を", "に", "で"]),
    G("Chỉ ... thôi", "N しか + phủ định", "しか luôn đi với phủ định, nghĩa là chỉ có chừng đó, không hơn.", "ローマ字しか 書けません。", "Tôi chỉ viết được Romaji thôi.", "ひらがな ＿＿＿ 読めません。", "しか", ["しか", "だけ", "も", "と"]),
    G("So sánh は và が trong khả năng", "N は chủ đề / N が đối tượng khả năng", "は nêu chủ đề, が đánh dấu thứ làm được hoặc nhìn/nghe thấy.", "私は 日本語が 少し話せます。", "Tôi nói được một chút tiếng Nhật.", "田中さんは 英語 ＿＿＿ 話せます。", "が", ["が", "を", "に", "へ"]),
  ],
  28: [
    G("Vừa làm vừa làm", "Vます bỏ ます + ながら", "Diễn tả hai hành động xảy ra đồng thời; hành động chính đứng sau.", "音楽を 聞きながら 勉強します。", "Tôi vừa nghe nhạc vừa học.", "テレビを 見 ＿＿＿ ご飯を 食べます。", "ながら", ["ながら", "たり", "し", "ても"]),
    G("Thói quen với ています", "Vています", "Ngoài hành động đang diễn ra, ています còn dùng cho thói quen hoặc việc lặp lại.", "毎朝 ジョギングを しています。", "Mỗi sáng tôi chạy bộ.", "妹は 大学に ＿＿＿。", "通っています", ["通っています", "通ってあります", "通れます", "通いますか"]),
    G("Liệt kê lý do với し", "Thể thường + し、...", "Dùng để nêu nhiều lý do hoặc đặc điểm, thường có sắc thái còn lý do khác nữa.", "この店は 安いし、おいしいし、便利です。", "Quán này vừa rẻ, vừa ngon, lại tiện.", "あの先生は 優しい ＿＿＿、説明も 上手です。", "し", ["し", "ながら", "しか", "たら"]),
    G("Cũng... cũng...", "N も ... し、N も ...", "Dùng も trong các mệnh đề với し để nhấn mạnh nhiều điểm cùng đúng.", "英語も わかるし、中国語も わかります。", "Hiểu cả tiếng Anh lẫn tiếng Trung.", "この部屋は 広い ＿＿＿、明るいです。", "し", ["し", "ながら", "ので", "たら"]),
    G("Chọn vì nhiều lý do", "S1し、S2し、それで...", "Có thể dùng し để đưa lý do cho quyết định hoặc đánh giá.", "駅から近いし、家賃も安いし、それでこの部屋にしました。", "Vì gần ga và tiền thuê rẻ nên tôi chọn phòng này.", "便利だ ＿＿＿、ここに住みたいです。", "し", ["し", "ながら", "しか", "てしまう"]),
  ],
  29: [
    G("Tự động từ + ています", "N が V自動詞て います", "Diễn tả trạng thái còn lại sau một thay đổi tự nhiên.", "ドアが 開いています。", "Cửa đang mở.", "電気が ＿＿＿。", "消えています", ["消えています", "消しています", "消してあります", "消せます"]),
    G("Tự động từ và tha động từ", "開きます / 開けます", "Tự động từ nói trạng thái của vật; tha động từ nói ai đó tác động vào vật.", "窓が 閉まっています。", "Cửa sổ đang đóng.", "窓を ＿＿＿ください。", "閉めて", ["閉めて", "閉まって", "閉まれて", "閉まりて"]),
    G("Lỡ mất với てしまいました", "Vて しまいました", "Diễn tả việc đã xảy ra xong, thường kèm tiếc nuối hoặc hối hận.", "電車に 傘を 忘れてしまいました。", "Tôi lỡ quên ô trên tàu.", "財布を 落として ＿＿＿。", "しまいました", ["しまいました", "あります", "おきました", "います"]),
    G("Làm xong hẳn", "Vて しまいます", "Ngoài hối tiếc, てしまいます còn diễn tả hoàn thành hết một việc.", "宿題を 全部やってしまいました。", "Tôi đã làm xong hết bài tập.", "この本を 今晩 読んで ＿＿＿。", "しまいます", ["しまいます", "あります", "います", "おきます"]),
    G("Trạng thái đồ vật", "N は V自動詞て います", "Khi nêu vật làm chủ đề, dùng は; động từ vẫn là tự động từ.", "このパソコンは 壊れています。", "Máy tính này bị hỏng.", "この皿は ＿＿＿。", "割れています", ["割れています", "割っています", "割ってあります", "割れますか"]),
  ],
  30: [
    G("Trạng thái chuẩn bị sẵn", "N が Vて あります", "Diễn tả trạng thái của vật sau khi ai đó đã tác động vào có mục đích.", "壁に カレンダーが 張ってあります。", "Trên tường có dán lịch.", "机の上に 書類が ＿＿＿。", "置いてあります", ["置いてあります", "置いています", "置けます", "置きながら"]),
    G("Vị trí với に + てあります", "Địa điểm に N が Vてあります", "に đánh dấu nơi trạng thái được chuẩn bị sẵn tồn tại.", "玄関に 花が 飾ってあります。", "Ở cửa ra vào có trang trí hoa.", "壁 ＿＿＿ ポスターが はってあります。", "に", ["に", "で", "を", "へ"]),
    G("Chuẩn bị trước", "Vて おきます", "Làm trước một việc để chuẩn bị cho tương lai.", "旅行の前に 切符を 買っておきます。", "Trước chuyến đi tôi mua sẵn vé.", "会議の前に 資料を コピーして ＿＿＿。", "おきます", ["おきます", "あります", "います", "しまいます"]),
    G("Để nguyên như vậy", "そのままにしておきます", "ておきます cũng dùng khi giữ nguyên trạng thái hiện tại.", "窓は そのままにしておいてください。", "Xin cứ để cửa sổ nguyên như vậy.", "電気は つけたままにして ＿＿＿ください。", "おいて", ["おいて", "あって", "しまって", "ながら"]),
    G("Dọn sau khi dùng", "Vたら、元の所に Vておいてください", "Dùng để yêu cầu người khác đưa đồ về trạng thái/vị trí ban đầu sau khi dùng.", "使ったら、元の所に戻しておいてください。", "Dùng xong hãy trả về chỗ cũ.", "読んだら、本棚に ＿＿＿ください。", "戻しておいて", ["戻しておいて", "戻っていて", "戻してあって", "戻れます"]),
  ],
};
