export const kanjiVocabulary46to50 = {
  46: [
    { kanji: "焼きます", reading: "やきます", vietnamese: "nướng, rán" },
    { kanji: "渡します", reading: "わたします", vietnamese: "đưa cho, giao cho" },
    { kanji: "帰ってきます", reading: "かえってきます", vietnamese: "quay về, trở lại" },
    { kanji: "出ます", reading: "でます", vietnamese: "xuất phát, đi ra" },
    { kanji: "留守", reading: "るす", vietnamese: "vắng nhà" },
    { kanji: "宅配便", reading: "たくはいびん", vietnamese: "dịch vụ giao hàng tận nhà" },
    { kanji: "注射", reading: "ちゅうしゃ", vietnamese: "tiêm" },
    { kanji: "食欲", reading: "しょくよく", vietnamese: "cảm giác muốn ăn" },
    { kanji: "知識", reading: "ちしき", vietnamese: "kiến thức" },
    { kanji: "宝庫", reading: "ほうこ", vietnamese: "kho báu" },
    { kanji: "例えば", reading: "たとえば", vietnamese: "ví dụ" },
    { kanji: "具合", reading: "ぐあい", vietnamese: "tình trạng, sức khỏe" },
    { kanji: "向かいます", reading: "むかいます", vietnamese: "hướng đến" },
  ],
  47: [
    { kanji: "集まります", reading: "あつまります", vietnamese: "tập trung" },
    { kanji: "別れます", reading: "わかれます", vietnamese: "chia tay, tách ra" },
    { kanji: "長生きします", reading: "ながいきします", vietnamese: "sống lâu" },
    { kanji: "怖い", reading: "こわい", vietnamese: "đáng sợ" },
    { kanji: "天気予報", reading: "てんきよほう", vietnamese: "dự báo thời tiết" },
    { kanji: "発表", reading: "はっぴょう", vietnamese: "phát biểu, công bố" },
    { kanji: "実験", reading: "じっけん", vietnamese: "thí nghiệm" },
    { kanji: "人口", reading: "じんこう", vietnamese: "dân số" },
    { kanji: "科学", reading: "かがく", vietnamese: "khoa học" },
    { kanji: "医学", reading: "いがく", vietnamese: "y học" },
    { kanji: "文学", reading: "ぶんがく", vietnamese: "văn học" },
    { kanji: "救急車", reading: "きゅうきゅうしゃ", vietnamese: "xe cấp cứu" },
    { kanji: "賛成", reading: "さんせい", vietnamese: "tán thành" },
    { kanji: "反対", reading: "はんたい", vietnamese: "phản đối" },
    { kanji: "男性", reading: "だんせい", vietnamese: "nam giới" },
    { kanji: "女性", reading: "じょせい", vietnamese: "nữ giới" },
    { kanji: "恋人", reading: "こいびと", vietnamese: "người yêu" },
    { kanji: "婚約します", reading: "こんやくします", vietnamese: "đính hôn" },
    { kanji: "相手", reading: "あいて", vietnamese: "đối phương" },
    { kanji: "脳", reading: "のう", vietnamese: "não" },
    { kanji: "知り合います", reading: "しりあいます", vietnamese: "quen biết" },
  ],
  48: [
    { kanji: "降ろします", reading: "おろします", vietnamese: "hạ xuống, cho xuống" },
    { kanji: "届けます", reading: "とどけます", vietnamese: "giao đến, gửi đến" },
    { kanji: "世話", reading: "せわ", vietnamese: "chăm sóc" },
    { kanji: "嫌", reading: "いや", vietnamese: "khó chịu, không thích" },
    { kanji: "厳しい", reading: "きびしい", vietnamese: "nghiêm khắc" },
    { kanji: "塾", reading: "じゅく", vietnamese: "lớp học thêm" },
    { kanji: "生徒", reading: "せいと", vietnamese: "học sinh" },
    { kanji: "入管", reading: "にゅうかん", vietnamese: "cục quản lý nhập cảnh" },
    { kanji: "再入国", reading: "さいにゅうこく", vietnamese: "tái nhập cảnh" },
    { kanji: "自由", reading: "じゆう", vietnamese: "tự do" },
    { kanji: "久しぶり", reading: "ひさしぶり", vietnamese: "lâu rồi" },
    { kanji: "世紀", reading: "せいき", vietnamese: "thế kỷ" },
    { kanji: "心", reading: "こころ", vietnamese: "trái tim, tâm hồn" },
    { kanji: "間", reading: "かん", vietnamese: "khoảng thời gian" },
    { kanji: "営業", reading: "えいぎょう", vietnamese: "kinh doanh" },
    { kanji: "楽しみます", reading: "たのしみます", vietnamese: "tận hưởng" },
  ],
  49: [
    { kanji: "勤めます", reading: "つとめます", vietnamese: "làm việc ở" },
    { kanji: "休みます", reading: "やすみます", vietnamese: "nghỉ, ngủ" },
    { kanji: "掛けます", reading: "かけます", vietnamese: "ngồi, treo" },
    { kanji: "過ごします", reading: "すごします", vietnamese: "trải qua" },
    { kanji: "寄ります", reading: "よります", vietnamese: "ghé qua" },
    { kanji: "召し上がります", reading: "めしあがります", vietnamese: "ăn/uống (tôn kính)" },
    { kanji: "ご覧になります", reading: "ごらんになります", vietnamese: "xem/nhìn (tôn kính)" },
    { kanji: "ご存知です", reading: "ごぞんじです", vietnamese: "biết (tôn kính)" },
    { kanji: "挨拶", reading: "あいさつ", vietnamese: "chào hỏi" },
    { kanji: "灰皿", reading: "はいざら", vietnamese: "gạt tàn" },
    { kanji: "旅館", reading: "りょかん", vietnamese: "nhà trọ kiểu Nhật" },
    { kanji: "会場", reading: "かいじょう", vietnamese: "hội trường" },
    { kanji: "貿易", reading: "ぼうえき", vietnamese: "thương mại" },
    { kanji: "様", reading: "さま", vietnamese: "ngài, quý vị" },
    { kanji: "遠慮", reading: "えんりょ", vietnamese: "khách sáo, ngại" },
    { kanji: "熱", reading: "ねつ", vietnamese: "sốt, nhiệt" },
    { kanji: "失礼いたします", reading: "しつれいいたします", vietnamese: "xin phép thất lễ" },
  ],
  50: [
    { kanji: "参ります", reading: "まいります", vietnamese: "đi/đến (khiêm nhường)" },
    { kanji: "申します", reading: "もうします", vietnamese: "nói, tên là (khiêm nhường)" },
    { kanji: "いたします", reading: "いたします", vietnamese: "làm (khiêm nhường)" },
    { kanji: "拝見します", reading: "はいけんします", vietnamese: "xem/nhìn (khiêm nhường)" },
    { kanji: "存じます", reading: "ぞんじます", vietnamese: "biết (khiêm nhường)" },
    { kanji: "伺います", reading: "うかがいます", vietnamese: "hỏi/đến thăm (khiêm nhường)" },
    { kanji: "私", reading: "わたくし", vietnamese: "tôi (trang trọng)" },
    { kanji: "お宅", reading: "おたく", vietnamese: "nhà người khác" },
    { kanji: "郊外", reading: "こうがい", vietnamese: "ngoại ô" },
    { kanji: "再来週", reading: "さらいしゅう", vietnamese: "tuần sau nữa" },
    { kanji: "再来月", reading: "さらいげつ", vietnamese: "tháng sau nữa" },
    { kanji: "再来年", reading: "さらいねん", vietnamese: "năm sau nữa" },
    { kanji: "最初", reading: "さいしょ", vietnamese: "đầu tiên" },
    { kanji: "最後", reading: "さいご", vietnamese: "cuối cùng" },
    { kanji: "江戸東京博物館", reading: "えどとうきょうはくぶつかん", vietnamese: "bảo tàng Edo Tokyo" },
    { kanji: "緊張します", reading: "きんちょうします", vietnamese: "căng thẳng" },
    { kanji: "放送します", reading: "ほうそうします", vietnamese: "phát sóng" },
    { kanji: "自然", reading: "しぜん", vietnamese: "tự nhiên" },
    { kanji: "象", reading: "ぞう", vietnamese: "con voi" },
    { kanji: "夢", reading: "ゆめ", vietnamese: "giấc mơ" },
    { kanji: "協力します", reading: "きょうりょくします", vietnamese: "hợp tác" },
    { kanji: "感謝します", reading: "かんしゃします", vietnamese: "cảm ơn, biết ơn" },
  ],
};

const G = (
  title: string,
  pattern: string,
  explanation: string,
  example: string,
  translation: string,
  question: string,
  answer: string,
  choices: string[],
) => ({ title, pattern, explanation, example, translation, question, answer, choices });

export const grammarPoints46to50 = {
  46: [
    G("Sắp làm", "Vる + ところです", "Diễn tả hành động sắp bắt đầu ngay trước thời điểm nói.", "今から 昼ごはんを食べるところです。", "Tôi đang chuẩn bị ăn trưa.", "今から 出かける ＿＿＿。", "ところです", ["ところです", "ばかりです", "はずです", "そうです"]),
    G("Đang làm đúng lúc", "Vている + ところです", "Nhấn mạnh hành động đang diễn ra đúng vào thời điểm nói.", "今、資料を作っているところです。", "Tôi đang trong lúc làm tài liệu.", "今、電話している ＿＿＿。", "ところです", ["ところです", "ばかりです", "ようです", "ためです"]),
    G("Vừa mới làm xong", "Vた + ところです", "Diễn tả hành động vừa kết thúc ngay lúc nãy.", "たった今、バスが出たところです。", "Xe buýt vừa mới khởi hành.", "会議は 今 終わった ＿＿＿。", "ところです", ["ところです", "はずです", "そうです", "のに"]),
    G("Vừa mới", "Vた + ばかりです", "Nói việc vừa xảy ra theo cảm nhận của người nói; không nhất thiết là ngay lập tức.", "このパンは 焼いたばかりです。", "Bánh mì này vừa mới nướng.", "日本へ 来た ＿＿＿です。", "ばかり", ["ばかり", "ところ", "はず", "よう"]),
    G("Chắc là", "Thể thường + はずです", "Dùng để nói suy đoán chắc chắn dựa trên căn cứ.", "田中さんは 留守のはずです。", "Anh Tanaka chắc là đi vắng.", "荷物は もう 届いた ＿＿＿。", "はずです", ["はずです", "ところです", "ばかりです", "そうです"]),
  ],
  47: [
    G("Nghe nói", "Thể thường + そうです", "Truyền đạt lại thông tin nghe/đọc được từ nguồn khác.", "明日は 寒くなるそうです。", "Nghe nói ngày mai sẽ lạnh.", "ニュースによると、人口が 減った ＿＿＿。", "そうです", ["そうです", "ようです", "ところです", "はずです"]),
    G("Theo nguồn tin", "N によると", "Đặt trước thông tin được truyền đạt để nêu nguồn.", "天気予報によると、雨が降るそうです。", "Theo dự báo thời tiết, nghe nói sẽ mưa.", "新聞 ＿＿＿、事故があったそうです。", "によると", ["によると", "のために", "について", "にして"]),
    G("Hình như", "Thể thường + ようです", "Suy đoán từ điều mình thấy, nghe, cảm nhận hoặc từ tình huống.", "事故のようです。", "Hình như là tai nạn.", "隣の部屋に だれか いる ＿＿＿。", "ようです", ["ようです", "そうです", "ばかりです", "ためです"]),
    G("Có mùi/âm thanh/vị", "におい/音/味 がします", "Dùng します để nói cảm giác như mùi, âm thanh, vị.", "この料理は 変なにおいがします。", "Món này có mùi lạ.", "外で 大きい音 ＿＿＿。", "がします", ["がします", "をします", "にします", "でします"]),
    G("Có vẻ từ nhiều dấu hiệu", "どうも + ようです", "どうも đi với ようです để nói suy đoán khá mạnh từ dấu hiệu.", "どうも風邪を引いたようです。", "Hình như tôi bị cảm rồi.", "頭が痛いです。どうも 風邪 ＿＿＿。", "のようです", ["のようです", "そうです", "ばかりです", "ところです"]),
  ],
  48: [
    G("Thể sai khiến nhóm 1", "Vない bỏない + せます", "Động từ nhóm 1 đổi sang thể sai khiến bằng cách chuyển âm a rồi thêm せます.", "母は弟に部屋を掃除させました。", "Mẹ bắt em trai dọn phòng.", "行きます → 行か ＿＿＿。", "せます", ["せます", "させます", "します", "られます"]),
    G("Thể sai khiến nhóm 2/3", "Vます bỏます + させます", "Nhóm 2 thêm させます; します→させます, 来ます→来させます.", "先生は生徒に意見を言わせました。", "Thầy cho học sinh phát biểu.", "食べます → 食べ ＿＿＿。", "させます", ["させます", "せます", "します", "られます"]),
    G("Bắt/cho người làm", "Ngườiを/に Vさせます", "Dùng để nói ai đó bắt hoặc cho phép người khác làm một hành động.", "部長は私を出張させました。", "Trưởng phòng bắt tôi đi công tác.", "母は 子どもに 野菜を食べ ＿＿＿。", "させます", ["させます", "ます", "られます", "そうです"]),
    G("Xin phép được làm", "Vさせていただけませんか", "Mẫu rất lịch sự để xin phép mình được làm việc gì.", "明日休ませていただけませんか。", "Ngày mai cho phép tôi nghỉ được không ạ?", "ここに 荷物を置か ＿＿＿。", "せていただけませんか", ["せていただけませんか", "せますか", "られますか", "そうですか"]),
    G("Xin cho phép", "Vさせてください", "Dùng để xin người nghe cho phép mình/người thuộc phía mình làm gì.", "子どもを塾に行かせてください。", "Xin hãy cho con tôi đi học thêm.", "少し 考え ＿＿＿。", "させてください", ["させてください", "してください", "てもいいです", "られてください"]),
  ],
  49: [
    G("Tôn kính お〜になります", "お/ご + gốc Vます + になります", "Dùng để nâng hành động của người trên/người nghe.", "社長はお帰りになりました。", "Giám đốc đã về rồi ạ.", "先生は もう お帰り ＿＿＿。", "になりました", ["になりました", "しました", "いたしました", "です"]),
    G("Động từ tôn kính đặc biệt", "いらっしゃいます / 召し上がります / おっしゃいます", "Một số động từ có dạng tôn kính riêng, cần học như từ vựng.", "先生は何を召し上がりますか。", "Thầy dùng món gì ạ?", "先生は 何と ＿＿＿か。", "おっしゃいました", ["おっしゃいました", "申しました", "いたしました", "参りました"]),
    G("Tôn kính bị động", "Vられます", "Có thể dùng dạng bị động để nói tôn kính ở mức nhẹ hơn.", "部長はアメリカへ出張されます。", "Trưởng phòng sẽ đi công tác Mỹ ạ.", "社長は いつ 来 ＿＿＿か。", "られます", ["られます", "させます", "いたします", "します"]),
    G("Yêu cầu tôn kính", "お/ご + gốc Vます + ください", "Dùng khi yêu cầu người trên/người nghe làm gì một cách lịch sự.", "こちらにお座りください。", "Xin mời ngài ngồi ở đây.", "少々 お待ち ＿＿＿。", "ください", ["ください", "します", "いたします", "になります"]),
    G("Danh xưng kính trọng", "方 / 様", "方 là cách nói kính trọng của 人; 様 dùng sau tên/khách hàng.", "あの方は松本先生です。", "Vị kia là thầy Matsumoto.", "お客様は 三階に ＿＿＿。", "いらっしゃいます", ["いらっしゃいます", "おります", "参ります", "申します"]),
  ],
  50: [
    G("Khiêm nhường お〜します", "お/ご + gốc Vます + します", "Hạ hành động của mình để thể hiện sự tôn trọng người nghe.", "私が荷物をお持ちします。", "Để tôi mang hành lý cho ạ.", "資料を お送り ＿＿＿。", "します", ["します", "になります", "ください", "です"]),
    G("Khiêm nhường lịch sự hơn", "お/ご + gốc Vます + いたします", "いたします là dạng khiêm nhường/lịch sự hơn của します.", "心から感謝いたします。", "Tôi xin chân thành cảm ơn.", "スケジュールを お送り ＿＿＿。", "いたします", ["いたします", "になります", "ください", "です"]),
    G("Động từ khiêm nhường đặc biệt", "参ります / 申します / 伺います / 拝見します", "Các động từ khiêm nhường đặc biệt dùng khi nói hành động của mình.", "私はグエンと申します。", "Tôi tên là Nguyễn ạ.", "明日、先生のお宅へ ＿＿＿。", "伺います", ["伺います", "いらっしゃいます", "召し上がります", "ご覧になります"]),
    G("Lịch sự trang trọng", "ございます / でございます", "Dạng lịch sự trang trọng của あります và です.", "こちらは会議室でございます。", "Đây là phòng họp ạ.", "資料は こちら ＿＿＿。", "でございます", ["でございます", "でいらっしゃいます", "でおります", "で申します"]),
    G("Từ xưng hô trang trọng", "わたくし / 皆様", "Dùng trong tình huống trang trọng, phát biểu, tiếp khách hoặc công việc.", "皆様のご協力に感謝いたします。", "Xin cảm ơn sự hợp tác của quý vị.", "＿＿＿は ハノイから参りました。", "わたくし", ["わたくし", "あなた", "きみ", "おまえ"]),
  ],
};
