export const kanjiVocabulary31to35 = {
  31: [
    { kanji: "始まります", reading: "はじまります", vietnamese: "bắt đầu" },
    { kanji: "続けます", reading: "つづけます", vietnamese: "tiếp tục" },
    { kanji: "見つけます", reading: "みつけます", vietnamese: "tìm thấy" },
    { kanji: "受けます", reading: "うけます", vietnamese: "thi, dự thi" },
    { kanji: "入学します", reading: "にゅうがくします", vietnamese: "nhập học" },
    { kanji: "卒業します", reading: "そつぎょうします", vietnamese: "tốt nghiệp" },
    { kanji: "出席します", reading: "しゅっせきします", vietnamese: "tham dự" },
    { kanji: "休憩します", reading: "きゅうけいします", vietnamese: "nghỉ giải lao" },
    { kanji: "連休", reading: "れんきゅう", vietnamese: "kỳ nghỉ liền ngày" },
    { kanji: "作文", reading: "さくぶん", vietnamese: "bài văn" },
    { kanji: "展覧会", reading: "てんらんかい", vietnamese: "triển lãm" },
    { kanji: "結婚式", reading: "けっこんしき", vietnamese: "lễ cưới" },
    { kanji: "お葬式", reading: "おそうしき", vietnamese: "lễ tang" },
    { kanji: "本社", reading: "ほんしゃ", vietnamese: "trụ sở chính" },
    { kanji: "支店", reading: "してん", vietnamese: "chi nhánh" },
    { kanji: "教会", reading: "きょうかい", vietnamese: "nhà thờ" },
    { kanji: "大学院", reading: "だいがくいん", vietnamese: "cao học" },
    { kanji: "動物園", reading: "どうぶつえん", vietnamese: "vườn thú" },
    { kanji: "温泉", reading: "おんせん", vietnamese: "suối nước nóng" },
    { kanji: "残ります", reading: "のこります", vietnamese: "ở lại, còn lại" },
  ],
  32: [
    { kanji: "運動します", reading: "うんどうします", vietnamese: "vận động" },
    { kanji: "成功します", reading: "せいこうします", vietnamese: "thành công" },
    { kanji: "失敗します", reading: "しっぱいします", vietnamese: "thất bại" },
    { kanji: "合格します", reading: "ごうかくします", vietnamese: "thi đỗ" },
    { kanji: "晴れます", reading: "はれます", vietnamese: "trời nắng" },
    { kanji: "曇ります", reading: "くもります", vietnamese: "trời nhiều mây" },
    { kanji: "吹きます", reading: "ふきます", vietnamese: "thổi" },
    { kanji: "治します", reading: "なおします", vietnamese: "chữa khỏi, sửa" },
    { kanji: "続きます", reading: "つづきます", vietnamese: "tiếp diễn" },
    { kanji: "冷やします", reading: "ひやします", vietnamese: "làm lạnh" },
    { kanji: "心配", reading: "しんぱい", vietnamese: "lo lắng" },
    { kanji: "十分", reading: "じゅうぶん", vietnamese: "đủ" },
    { kanji: "空", reading: "そら", vietnamese: "bầu trời" },
    { kanji: "太陽", reading: "たいよう", vietnamese: "mặt trời" },
    { kanji: "星", reading: "ほし", vietnamese: "ngôi sao" },
    { kanji: "月", reading: "つき", vietnamese: "mặt trăng" },
    { kanji: "風", reading: "かぜ", vietnamese: "gió" },
    { kanji: "北", reading: "きた", vietnamese: "bắc" },
    { kanji: "南", reading: "みなみ", vietnamese: "nam" },
    { kanji: "東", reading: "ひがし", vietnamese: "đông" },
    { kanji: "西", reading: "にし", vietnamese: "tây" },
    { kanji: "水道", reading: "すいどう", vietnamese: "nước máy" },
  ],
  33: [
    { kanji: "逃げます", reading: "にげます", vietnamese: "chạy trốn" },
    { kanji: "騒ぎます", reading: "さわぎます", vietnamese: "làm ồn" },
    { kanji: "諦めます", reading: "あきらめます", vietnamese: "từ bỏ" },
    { kanji: "投げます", reading: "なげます", vietnamese: "ném" },
    { kanji: "守ります", reading: "まもります", vietnamese: "bảo vệ, tuân thủ" },
    { kanji: "上げます", reading: "あげます", vietnamese: "nâng lên" },
    { kanji: "下げます", reading: "さげます", vietnamese: "hạ xuống" },
    { kanji: "伝えます", reading: "つたえます", vietnamese: "truyền đạt" },
    { kanji: "注意します", reading: "ちゅういします", vietnamese: "chú ý" },
    { kanji: "席", reading: "せき", vietnamese: "chỗ ngồi" },
    { kanji: "洗濯機", reading: "せんたくき", vietnamese: "máy giặt" },
    { kanji: "規則", reading: "きそく", vietnamese: "quy tắc" },
    { kanji: "使用禁止", reading: "しようきんし", vietnamese: "cấm sử dụng" },
    { kanji: "立ち入り禁止", reading: "たちいりきんし", vietnamese: "cấm vào" },
    { kanji: "入口", reading: "いりぐち", vietnamese: "cửa vào" },
    { kanji: "出口", reading: "でぐち", vietnamese: "cửa ra" },
    { kanji: "非常口", reading: "ひじょうぐち", vietnamese: "cửa thoát hiểm" },
    { kanji: "無料", reading: "むりょう", vietnamese: "miễn phí" },
    { kanji: "営業中", reading: "えいぎょうちゅう", vietnamese: "đang mở cửa" },
    { kanji: "警察", reading: "けいさつ", vietnamese: "cảnh sát" },
    { kanji: "罰金", reading: "ばっきん", vietnamese: "tiền phạt" },
  ],
  34: [
    { kanji: "磨きます", reading: "みがきます", vietnamese: "đánh, mài" },
    { kanji: "組み立てます", reading: "くみたてます", vietnamese: "lắp ráp" },
    { kanji: "折ります", reading: "おります", vietnamese: "gấp, bẻ" },
    { kanji: "見つかります", reading: "みつかります", vietnamese: "được tìm thấy" },
    { kanji: "質問します", reading: "しつもんします", vietnamese: "hỏi" },
    { kanji: "細い", reading: "ほそい", vietnamese: "thon, mảnh" },
    { kanji: "太い", reading: "ふとい", vietnamese: "to, dày" },
    { kanji: "盆踊り", reading: "ぼんおどり", vietnamese: "múa lễ Bon" },
    { kanji: "家具", reading: "かぐ", vietnamese: "đồ nội thất" },
    { kanji: "説明書", reading: "せつめいしょ", vietnamese: "sách hướng dẫn" },
    { kanji: "図", reading: "ず", vietnamese: "sơ đồ" },
    { kanji: "線", reading: "せん", vietnamese: "đường kẻ" },
    { kanji: "矢印", reading: "やじるし", vietnamese: "mũi tên" },
    { kanji: "黒", reading: "くろ", vietnamese: "màu đen" },
    { kanji: "白", reading: "しろ", vietnamese: "màu trắng" },
    { kanji: "赤", reading: "あか", vietnamese: "màu đỏ" },
    { kanji: "青", reading: "あお", vietnamese: "màu xanh" },
    { kanji: "黄色", reading: "きいろ", vietnamese: "màu vàng" },
    { kanji: "茶道", reading: "さどう", vietnamese: "trà đạo" },
    { kanji: "苦い", reading: "にがい", vietnamese: "đắng" },
  ],
  35: [
    { kanji: "咲きます", reading: "さきます", vietnamese: "nở" },
    { kanji: "変わります", reading: "かわります", vietnamese: "thay đổi" },
    { kanji: "困ります", reading: "こまります", vietnamese: "gặp khó khăn" },
    { kanji: "付けます", reading: "つけます", vietnamese: "đánh dấu, gắn" },
    { kanji: "拾います", reading: "ひろいます", vietnamese: "nhặt" },
    { kanji: "楽", reading: "らく", vietnamese: "thoải mái" },
    { kanji: "正しい", reading: "ただしい", vietnamese: "đúng" },
    { kanji: "珍しい", reading: "めずらしい", vietnamese: "hiếm, lạ" },
    { kanji: "向こう", reading: "むこう", vietnamese: "phía bên kia" },
    { kanji: "島", reading: "しま", vietnamese: "đảo" },
    { kanji: "村", reading: "むら", vietnamese: "làng" },
    { kanji: "港", reading: "みなと", vietnamese: "cảng" },
    { kanji: "近所", reading: "きんじょ", vietnamese: "hàng xóm, vùng gần nhà" },
    { kanji: "屋上", reading: "おくじょう", vietnamese: "sân thượng" },
    { kanji: "海外", reading: "かいがい", vietnamese: "nước ngoài" },
    { kanji: "山登り", reading: "やまのぼり", vietnamese: "leo núi" },
    { kanji: "機会", reading: "きかい", vietnamese: "cơ hội" },
    { kanji: "許可", reading: "きょか", vietnamese: "giấy phép, sự cho phép" },
    { kanji: "操作", reading: "そうさ", vietnamese: "thao tác" },
    { kanji: "方法", reading: "ほうほう", vietnamese: "phương pháp" },
    { kanji: "設備", reading: "せつび", vietnamese: "thiết bị" },
    { kanji: "葉", reading: "は", vietnamese: "lá cây" },
    { kanji: "曲", reading: "きょく", vietnamese: "bài hát" },
    { kanji: "旅行社", reading: "りょこうしゃ", vietnamese: "công ty du lịch" },
  ],
};

const G = (
  title: string,
  pattern: string,
  explanation: string,
  example: string,
  translation: string,
  question: string,
  answer: string,
  choices: string[],
) => ({ title, pattern, explanation, example, translation, question, answer, choices });

export const grammarPoints31to35 = {
  31: [
    G("Thể ý chí", "V意向形", "Dùng để nói ý định hoặc rủ rê thân mật: 行きます→行こう, 食べます→食べよう, します→しよう.", "そろそろ 休憩しよう。", "Nghỉ một chút thôi.", "明日 早く ＿＿＿。", "起きよう", ["起きよう", "起きろ", "起きれば", "起きるな"]),
    G("Dự định đang giữ", "V意向形 + と思っています", "Diễn tả ý định đã hình thành và vẫn còn trong đầu người nói.", "週末は 海へ 行こうと思っています。", "Cuối tuần tôi định đi biển.", "来月から 日本語を 続け ＿＿＿。", "ようと思っています", ["ようと思っています", "るつもりですか", "たほうがいい", "ればいい"]),
    G("Dự định làm", "Vる + つもりです", "Dùng khi người nói đã quyết định sẽ làm một việc.", "大学院の試験を 受けるつもりです。", "Tôi định thi cao học.", "来年 日本へ ＿＿＿つもりです。", "行く", ["行く", "行った", "行こう", "行け"]),
    G("Dự định không làm", "Vない + つもりです", "Dùng khi quyết định sẽ không làm một việc.", "今年は 国へ 帰らないつもりです。", "Năm nay tôi định không về nước.", "もう タバコを ＿＿＿つもりです。", "吸わない", ["吸わない", "吸った", "吸える", "吸え"]),
    G("Kế hoạch chính thức", "Vる / Nの + 予定です", "予定です dùng cho lịch trình, kế hoạch đã được sắp xếp.", "会議は 10時からの予定です。", "Cuộc họp dự kiến từ 10 giờ.", "来週 支店へ ＿＿＿予定です。", "行く", ["行く", "行こう", "行ったら", "行け"]),
  ],
  32: [
    G("Nên làm", "Vた + ほうがいいです", "Dùng để khuyên người nghe nên làm gì.", "毎日 運動したほうがいいです。", "Nên vận động mỗi ngày.", "熱が ありますから、病院へ ＿＿＿ほうがいいです。", "行った", ["行った", "行く", "行かない", "行けば"]),
    G("Không nên làm", "Vない + ほうがいいです", "Dùng để khuyên không nên làm điều gì.", "今日は お風呂に 入らないほうがいいです。", "Hôm nay không nên tắm.", "咳が 出ますから、無理を ＿＿＿ほうがいいです。", "しない", ["しない", "した", "する", "すれば"]),
    G("Phỏng đoán khá chắc", "Thể thường + でしょう", "Dùng khi dự đoán dựa trên thông tin hoặc cảm giác, mức chắc cao hơn かもしれません.", "明日は 晴れるでしょう。", "Có lẽ ngày mai trời nắng.", "このチームは ＿＿＿でしょう。", "勝つ", ["勝つ", "勝て", "勝つな", "勝ったら"]),
    G("Có thể, không chừng", "Thể thường + かもしれません", "Diễn tả khả năng có thể xảy ra nhưng chưa chắc.", "午後は 雨が 降るかもしれません。", "Chiều có thể mưa.", "試験は ＿＿＿かもしれません。", "難しい", ["難しい", "難しく", "難しければ", "難しさ"]),
    G("Có lẽ với danh từ/tính từ な", "N/Aな + かもしれません", "Danh từ và tính từ な bỏ だ trước かもしれません.", "明日は 雪かもしれません。", "Ngày mai có thể có tuyết.", "田中さんは 今日 休み ＿＿＿。", "かもしれません", ["かもしれません", "でしょうです", "ほうがいい", "つもりです"]),
  ],
  33: [
    G("Mệnh lệnh", "命令形", "Dạng ra lệnh mạnh: 行け, 読め, 起きろ, しろ, 来い. Chủ yếu gặp ở biển báo, khẩu lệnh, trích dẫn.", "早く 起きろ。", "Dậy mau.", "ここで ＿＿＿。", "止まれ", ["止まれ", "止まるな", "止まれば", "止まった"]),
    G("Cấm chỉ", "辞書形 + な", "Dùng để cấm mạnh, thường gặp ở biển báo hoặc lời quát.", "ここに 車を 止めるな。", "Không được đỗ xe ở đây.", "危ないですから、そこへ ＿＿＿。", "行くな", ["行くな", "行け", "行けば", "行った"]),
    G("Trích nội dung viết", "「...」と 書いてあります", "Dùng để nói trên biển báo, giấy tờ có viết nội dung gì.", "あそこに「止まれ」と書いてあります。", "Ở kia có viết 'Dừng lại'.", "入口に「無料」＿＿＿。", "と書いてあります", ["と書いてあります", "と言います", "と思います", "と読みます"]),
    G("Giải nghĩa", "A は B という意味です", "Dùng để giải thích ý nghĩa của từ, biển báo hoặc ký hiệu.", "使用禁止は 使うなという意味です。", "Cấm sử dụng nghĩa là không được dùng.", "立入禁止は 入るな ＿＿＿。", "という意味です", ["という意味です", "と思っています", "とおりです", "という予定です"]),
    G("Thuật lại lời nói", "Thể thường + と言っていました", "Dùng khi kể lại điều ai đó đã nói.", "田中さんは 明日休むと言っていました。", "Tanaka nói mai sẽ nghỉ.", "先生は 宿題を出せ ＿＿＿。", "と言っていました", ["と言っていました", "という意味です", "と書いてあります", "と思っています"]),
  ],
  34: [
    G("Làm theo hành động", "Vる / Vた + とおりに", "Dùng khi làm đúng theo điều ai nói/làm hoặc theo mẫu có sẵn.", "私が 言うとおりに 書いてください。", "Hãy viết đúng như tôi nói.", "先生が した ＿＿＿、やってください。", "とおりに", ["とおりに", "あとで", "ないで", "なら"]),
    G("Làm theo danh từ", "Nの + とおりに", "Khi danh từ đứng trước とおりに thì thêm の.", "線のとおりに 紙を切ってください。", "Hãy cắt giấy theo đường kẻ.", "説明書 ＿＿＿ 組み立てます。", "のとおりに", ["のとおりに", "をとおりに", "のあとで", "ないで"]),
    G("Sau khi làm", "Vた + あとで", "Diễn tả hành động sau xảy ra sau khi hành động trước hoàn tất.", "仕事が 終わったあとで 飲みに行きます。", "Sau khi xong việc sẽ đi uống.", "歯を 磨いた ＿＿＿、寝ます。", "あとで", ["あとで", "とおりに", "ないで", "なら"]),
    G("Sau danh từ", "Nの + あとで", "Với danh từ, dùng のあとで.", "授業のあとで 質問します。", "Sau giờ học tôi sẽ hỏi.", "会議 ＿＿＿、電話してください。", "のあとで", ["のあとで", "あとで", "とおりに", "ないで"]),
    G("Không làm mà...", "Vないで + V", "Diễn tả làm hành động sau trong trạng thái không làm hành động trước.", "砂糖を 入れないで コーヒーを飲みます。", "Uống cà phê không cho đường.", "朝ご飯を ＿＿＿ 会社へ行きました。", "食べないで", ["食べないで", "食べなくて", "食べるな", "食べれば"]),
  ],
  35: [
    G("Điều kiện động từ", "Vば", "Nhóm I đổi âm u sang eba; nhóm II bỏ る thêm れば; します→すれば, 来ます→来れば.", "ボタンを 押せば、窓が開きます。", "Nếu bấm nút thì cửa sổ mở.", "ここを ＿＿＿、駅があります。", "曲がれば", ["曲がれば", "曲がるな", "曲がろう", "曲がった"]),
    G("Điều kiện tính từ い", "Aければ", "Bỏ い thêm ければ; いい đổi thành よければ.", "天気が よければ、山が見えます。", "Nếu trời đẹp thì thấy núi.", "安 ＿＿＿、買います。", "ければ", ["ければ", "くて", "かったら", "いなら"]),
    G("Điều kiện phủ định", "Vない / Aくない → なければ", "Dạng phủ định đổi ない thành なければ.", "時間が なければ、行きません。", "Nếu không có thời gian thì không đi.", "薬を 飲ま ＿＿＿、治りません。", "なければ", ["なければ", "ないで", "なくて", "ないなら"]),
    G("Nên làm thế nào", "疑問詞 + Vばいいですか", "Dùng để xin lời khuyên nên làm gì, mua ở đâu, hỏi ai.", "どこで 買えばいいですか。", "Nên mua ở đâu?", "この漢字は だれに ＿＿＿いいですか。", "聞けば", ["聞けば", "聞くな", "聞こう", "聞いた"]),
    G("Nếu là...", "Nなら", "Dùng để nêu chủ đề giả định hoặc giới hạn phạm vi trước khi đưa ý kiến.", "温泉なら、白馬がいいですよ。", "Nếu là suối nước nóng thì Hakuba tốt.", "安いホテル ＿＿＿、駅の近くにあります。", "なら", ["なら", "ば", "と", "ても"]),
  ],
};
