"""Generate the read-only edge dataset from the canonical Python seed data."""

from __future__ import annotations

import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from seed import SEED_PASSAGES, SEED_SENTENCES  # noqa: E402


def build_sentences() -> dict[int, list[dict[str, object]]]:
    result: dict[int, list[dict[str, object]]] = {}
    for lesson_id, items in SEED_SENTENCES.items():
        rows: list[dict[str, object]] = []
        for position, item in enumerate(items, start=1):
            sentence_id = lesson_id * 1000 + position
            chunks = [
                {
                    "id": sentence_id * 10 + order_index,
                    "order_index": order_index,
                    "japanese": japanese,
                    "vietnamese": vietnamese,
                    "is_grammar_key": is_grammar_key,
                }
                for order_index, japanese, vietnamese, is_grammar_key in item["chunks"]
            ]
            rows.append(
                {
                    "id": sentence_id,
                    "lesson_id": lesson_id,
                    "passage_id": None,
                    "full_japanese": item["full_japanese"],
                    "full_romaji": item["full_romaji"],
                    "full_vietnamese": item["full_vietnamese"],
                    "audio_url": None,
                    "chunks": chunks,
                }
            )
        result[lesson_id] = rows
    return result


def build_passages() -> dict[int, list[dict[str, object]]]:
    return {
        lesson_id: [
            {
                "id": lesson_id * 100 + position,
                "lesson_id": lesson_id,
                "title": item["title"],
                "content": item["content"],
            }
            for position, item in enumerate(items, start=1)
        ]
        for lesson_id, items in SEED_PASSAGES.items()
    }


def main() -> None:
    sentences = json.dumps(build_sentences(), ensure_ascii=False, indent=2)
    passages = json.dumps(build_passages(), ensure_ascii=False, indent=2)
    output = (
        "/* Auto-generated by scripts/export_edge_data.py. Do not edit manually. */\n"
        f"export const generatedSentences = {sentences} as const;\n\n"
        f"export const generatedPassages = {passages} as const;\n"
    )
    target = PROJECT_ROOT / "worker" / "lesson-data.generated.ts"
    target.write_text(output, encoding="utf-8", newline="\n")
    print(f"Generated {target.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
